### ISSUE TITLE
CSS color not working on InLineCssTextArea

### ISSUE THREAD

**Issue by ghost** [FXMisc/RichTextFX#10]
Hi Tomas, The InlineCssTextArea text do not seem to update its color based on the the passed CSS style string. Other properties work fine (font, size, weight, etc). 

The same CSS style string works on the regular javafx TextArea.

This is what I am using for color:
"-fx-text-fill: " + getColor() + " ;" 

getColor() return a color value for sure (it works fine on TextArea).

Using  latest JAR 20140122
Thanks,
Maher

**Comment by nazmuddin** [comment]
Hi @TomasMikula , i have two queries. 

1. How to set different style of words in same paragraph or line of `GenericStyledArea` ? I am doing it like this ....

      `area.setStyle(area.getText().lastIndexOf(text), area.getText().length(),  
                TextStyle.EMPTY.updateTextColor(color)); `
This works only for first word, but when i append the second word with different style like 

      `area.setStyle(area.getText().lastIndexOf(text), area.getText().length(),  
                TextStyle.EMPTY.updateTextColor(color).updateBold(true); 

it also changes the style of first text. Now how to do it ?

2. How to add different objects in same `GenericStyledArea` . What i mean to say is if i define the area like this 
`final GenericStyledArea<ParStyle, Either<StyledText<TextStyle>, LinkedImage<TextStyle>>, TextStyle> area`  . i can insert only `LinkedImage` objects into this.  But if i have to add lets say an `Text` or `Hyperlink` Object then how to do it. I can manage the hyperlink with styling as you explained in some pull request but if i have to add Hyperlink and I mage in area then how to do it ?

Thank you.
