### ISSUE TITLE
how can make one typescript editor? do the typescript provided the code syntax ast?

### ISSUE THREAD

**Issue by qq1053831109** [FXMisc/RichTextFX#1003]
how can make one typescript editor? do the typescript provided the code syntax ast?

**Comment by Jugen** [comment]
RichTextFX doesn't have any language syntax editing or highlighting built in.
To do syntax highlighting in RichTextFX have a look at the [JavaKeyWordsDemo](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/JavaKeywordsDemo.java)
[Here is a screenshot](../tree/master/richtextfx-demos/screenshots/JavaKeywordsDemo.jpg)
