### ISSUE TITLE
How to tell RichTextFX to apply a style to what is about to be typed?

### ISSUE THREAD

**Issue by SKeeneCode** [FXMisc/RichTextFX#1004]
If you load up most rich text editors such as Microsoft word you can toggle the bold button and then start typing in bold text. You can then deselect the bold button and continue typing in regular text.

In my own editor, segments are styled with a `TextStyle` which uses Optionals for bold, itallic and so on (pretty much used the structure the richtextdemo uses). Here is what I've tried:

When the user clicks the bold button, we change the `initialSegStyle` of the GenericTextArea with `initialSegStyle.bold = style.bold` and then request focus back into the text area.

This so far works:

![image](https://user-images.githubusercontent.com/32420836/107793965-c979a000-6d4e-11eb-957b-7a82ecaa9f9a.png)

Now if I deselect bold, I'm expecting all previous text to stay bold and when I start typing the text will be normal. This happens instead:

![image](https://user-images.githubusercontent.com/32420836/107794101-ef06a980-6d4e-11eb-885d-dbab2d66a513.png)

Upon typing a letter (a in this case) the entire paragraph becomes regular. Likewise I can now press the bold button and type anything for it all to become bold again.

Some suggestions on how to implement this would be great!

**Comment by Jugen** [comment]
The problem is that you are actually changing the style object that is being applied to the previously type text. To change the style of future text without affecting past text you need to assign a new style object. Maybe something like this:
```java
initialSegStyle = initialSegStyle.copy();  // first replace segment style with new style object
initialSegStyle.bold = style.bold;
```
or like this: `initialSegStyle = initialSegStyle.updateBold( style.bold );` where updateBold is:
```java
public TextStyle updateBold( boolean boldValue ) {
    return new TextStyle( boldValue, italic, underline, strikethrough, fontSize, fontFamily, textColor, backgroundColor );
}
```

**Comment by SKeeneCode** [comment]
I wasn't able to get it to work for a while. Looked into the code and saw I could set:

`useInitialStyleForInsertion = true`

Which looks like it would do the job, but it doesn't looks like `initialTextStyle` has any public setters and it is final, so I am unable to do `initialTextStyle= initialTextStyle.updateBold( style.bold );`.

I was however able to set `textInsertionStyle = style` which appears to have given me the functionality I wanted.

**Comment by Jugen** [comment]
Yeah, the formal method for that is `setTextInsertionStyle( style )`
