### ISSUE TITLE
Question: How to make the StyleClassedTextField look like a Label?

### ISSUE THREAD

**Issue by MrKuip** [FXMisc/RichTextFX#1009]
I'm currently converting JMeld to javaFx. (JMeld is a tool to diff files)
JMeld used the swing library and I created a component looked like a JLabel and  I used it to 
show differences in the path of the 2 files that were diffed.

I'm now trying to accomplish the same thing with RichTextFx and I got it working but I really
want to have a richtext in a Label. Is that possible? 

This is what I have now in JavaFx:
![JavaFXDiffLabel](https://user-images.githubusercontent.com/15797225/112208094-3dde1380-8c18-11eb-8500-f4d064e23550.png)

And this is what it was in Swing:
![SwingDiffLabel](https://user-images.githubusercontent.com/15797225/112208357-8f869e00-8c18-11eb-8b0e-a6a14a6408a2.png)

**Comment by MrKuip** [comment]
I now subclass CodeArea and set the background to Background.EMPTY.
Exactly what I want

**Comment by Jugen** [comment]
You can also try using: `InlineCssTextField` or `StyleClassedTextField`

**Comment by Jugen** [comment]
Sorry I misread your issue.
