### ISSUE TITLE
? Cannot resolve symbol 'javafx' - I'm trying to run the demos locally but cannot due to JavaFX missing

### ISSUE THREAD

**Issue by hutcni** [FXMisc/RichTextFX#1010]
**Environment:**
- JDK 11
- OS: Windows 10 Home - 20H2
- RichTextFX: cloned from master branch
- Gradle Version: 5.2.1
- IDE: IntelliJ IDEA 2020.2.4

**My aim:** I want to be able to run the demos locally and debug through them to help me understand the code.

**The problem:** JavaFX seems to be missing so when I run the "gradlew RichTextDemo" command the compilation fails. Looking through the source code I can see any reference to javafx highlighted in red and upon hovering my mouse over said references I see "Cannot resolve symbol 'javafx'"

**Context:** I've cloned the source code from the master branch on GitHub and the initial build was successful, although I did notice the following message: "Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings."

**What I've tried:** 
- I have javafx-sdk-15.0.1 installed and I've tried adding the lib folder as a library manually via Project Structure > Libraries > Plus Button > Java > Select javafx-sdk-15.0.1 lib folder. This changes the error to be "Cannot resolve symbol 'Path'" for example, instead of the previous error in which it could not find javafx.
- I've also tried changing the project SDK under Project Structure > Project SDK > Add SDK > Select javafx-sdk-15.0.1 folder - but Intellij throws this error: "The selected directory is not a valid home for JDK"

I know this problem is trivial and most likely a result of my ignorance however I'm on a tight deadline and would appreciate any help massively.

**Comment by Jugen** [comment]
Hi, so currently gradle is setup to compile RichTextFX against Java 8 or 9, where JavaFX is part of the JDK.
You have two options I think:
1.  Download a JDK that includes JavaFX, like [Azul](https://www.azul.com/downloads/zulu-community/?version=java-15-mts&os=windows&architecture=x86-64-bit&package=jdk-fx), or
2.  Change gradle to include JavaFX dependencies.

Unfortunately I cannot help with option 2 as my gradle foo is weak, but if you do get it right I'd really appreciate feedback.

**Comment by hutcni** [comment]
Went with option 1 for speed's sake and it worked - much appreciated @Jugen

**Comment by hutcni** [comment]
The syntax highlighting looks all normal after I switched to JDK 8 however the compile/build still fails: 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':richtextfx:compileJava'

Other errros:
error: cannot find symbol
    @Override public final BooleanProperty editableProperty() { return editable; }

It seems to not be recognising the JavaFX package although the IDE does as I can CTRL+click into the JavaFX classes. Any ideas?

**Comment by hutcni** [comment]
I tried adding the Gradle configs specified here: https://openjfx.io/openjfx-docs/#gradle
But it still didn't work.

I've now tried switching to JDK 9 and still no luck when I run "gradlew RichTextDemo"

**Comment by hutcni** [comment]
Update: had to manually change the JAVA_HOME environment variable and restart IntelliJ

Now works, thanks @Jugen!
