### ISSUE TITLE
RichtextFx codearea set certain lines uneditable

### ISSUE THREAD

**Issue by Bibek1998** [FXMisc/RichTextFX#1011]
I'm trying to create a cmd like console using codearea I want previous lines to be uneditable after enter key pressed also want certain parts of the lines like pre written text by console to be uneditable

**Comment by Jugen** [comment]
One way to do this is to put a listener on the currentParagraphProperty() and to then forcibly move the cursor back to the last line.

You could try the same thing for "certain parts" but using caretPositionProperty(), this will be a lot more complicated though.

**Comment by Bibek1998** [comment]
> One way to do this is to put a listener on the currentParagraphProperty() and to then forcibly move the cursor back to the last line.
> 
> You could try the same thing for "certain parts" but using caretPositionProperty(), this will be a lot more complicated though.

Sir, please share some pseudo code, I'm new to richtextfx

**Comment by Bibek1998** [comment]
> One way to do this is to put a listener on the currentParagraphProperty() and to then forcibly move the cursor back to the last line.
> 
> You could try the same thing for "certain parts" but using caretPositionProperty(), this will be a lot more complicated though.

Thank You Sir it worked
