### ISSUE TITLE
How to move set caret position in CodeArea

### ISSUE THREAD

**Issue by DacianGoina** [FXMisc/RichTextFX#1014]
Hello! I work for a spell checker app.
I found that CodeArea is a nice class to use for highlight wrong words (it can highlight the text from a range, codeArea.setStyleClass(start, end, style) ). But I have some problems with caret:

When I use left click I can get caret position, but also I want to move caret when press right click (on mouse) - I know how to get mouse position and to use this for caret, but question is how to move effective the caret.

codeArea.positionCaret(int) don't exists.

I use java 8, I integrated richtext jars (0.10.6) with maven

Also, how can I enable horizontally and vertical scroll in Code Area?

**Comment by Jugen** [comment]
To move the caret try using `codeArea.moveTo( int, SelectionPolicy )`

To get scroll bars try using: `new VirtualizedScrollPane( area );`

**Comment by DacianGoina** [comment]
@Jugen thank you! codeArea.moveTo(int pos) works fine
But about second suggestion, how exactly should I use new VirtualizedScrollPane(codeArea) ?

**Comment by Jugen** [comment]
Instead of adding RichTextFX directly to a layout container, you wrap it in a VirtualizedScrollPane and add that instead.
This can be done either in FXML or in code.  The import required is: `org.fxmisc.flowless.VirtualizedScrollPane`
Also you don't need to keep any references to the scroll pane, you just interact with the textarea.

**Comment by DacianGoina** [comment]
Thank you! @Jugen 
Also, I have another question (if you have some free time to help me): how can I move caret to a position given by mouse coordonates?

Textarea provide getSkin(), and I can use this:

```
TextAreaSkin skin = (TextAreaSkin) area.getSkin();
int insertionPoint = skin.getInsertionPoint(event.getX(),  event.getY());
area.positionCaret( insertionPoint);
```

For CodeArea, instead of positionCaret() I can use moveTo(), but how about getSkin()? How can I do this with CodeArea?

**Comment by Jugen** [comment]
Have a look at the [tooltip demo](https://github.com/FXMisc/RichTextFX/tree/master/richtextfx-demos#custom-tooltips) and see if that helps you ?
