### ISSUE TITLE
How to vertically center text?

### ISSUE THREAD

**Issue by mgroth0** [FXMisc/RichTextFX#1015]
First of all to the creators/contributors, thanks so much for a great library.

I have create a `GenericStyledArea` that incorporates both text (using the default `TextExt`) and custom nodes. For example, one custom node renders some math:

<img width="651" alt="Screen Shot 2021-05-28 at 4 49 55 AM" src="https://user-images.githubusercontent.com/12831489/119957549-27359f00-bf70-11eb-86d0-2198c605a040.png">

Problem is they are not vertically aligned.

The rendered math is a `Canvas`. If it were translated up or down, this introduces possible clipping.  So I think the `TextExt` needs to be vertically centered, possible with an additional offset as well. 

However, using the `translateYProperty` for the `TextExt` would also possibly cause clipping, unless it were bound to the height of the `ParagraphBox`. Even if it were bound to the height of the `ParagraphBox`, it would also need to consider how many line-wraps there are. This is way more complicated than setting the `alignmentProperty` of an `HBox`, for example.

Also, the vertical alighment method needs to be segment by segment, and generalize to multi-line cases.

I couldn't find any vertical alignment property and a search for "vertical alignment" here [comes up empty](https://github.com/FXMisc/RichTextFX/search?q=vertical+aligment), so maybe not thinking about this correctly or maybe I'm searching the wrong terms.

Any ideas?

Here's a more extreme case:
<img width="483" alt="Screen Shot 2021-05-28 at 5 09 36 AM" src="https://user-images.githubusercontent.com/12831489/119960390-e7bc8200-bf72-11eb-9580-f6a57a7a1886.png">

**Comment by Jugen** [comment]
Also try looking [here](https://github.com/FXMisc/RichTextFX/wiki/RichTextFX-CSS-Reference-Guide#the-missing-textflow-css-guide) in the Wiki, maybe this helps ....

**Comment by mgroth0** [comment]
Thanks @Jugen!

Looking into this, I found [this JDK bug report](https://bugs.openjdk.java.net/browse/JDK-8098128). According to that, the best way to solve this issue seems to be by overriding `TextFlow::getBaselineOffset`.

From looking around the code I've learned that RichTextFX subclasses `TextFlow` as `TextFlowExt` and `ParagraphText`. The `ParagraphText` is created inside constructed as a `ParagraphBox` is constructed. And the `ParagraphBox` is constructed inside the private method `GenericStyledArea::createCell`.

Therefore, subclassing `ParagraphText` seems like it would involve adapting a huge amount of internal richtextfx code. I think I might be up for it, but it would be awesome if someone with more experience could help me with a few step by step instructions on how best to do this.

**Comment by Jugen** [comment]
Hi @mgroth0, ummm .... I think you misread the solution the JDK bug report offers ?

It's not the TextFlow's baseline offset that gets overridden it's your `Canvas` _getBaselineOffset_ that you need to override.

Apparently something like the following (according to Christian) will _roughly_ center the canvas on the line:
```java
public double getBaselineOffset()
{
    return getHeight() * 0.75;
}
```
Note that according to Felipe:

> To center it at the middle of the line I think the math is: imageHeight/2 + textBaseline - textHeight/2 (where textBaseline and textHeight can be extract from a text node).

**Comment by mgroth0** [comment]
Excellent @Jugen, you are completely right!

This was from the `height * 0.75` approach.

<img width="546" alt="Screen Shot 2021-06-06 at 12 37 12 PM" src="https://user-images.githubusercontent.com/12831489/120932480-f0742d00-c6c3-11eb-9519-fb22728da30b.png">

I understand if I need even more precision (for example to try to line up "sum of squares" with the equals sine on the second example) I can try Felipe's approach. However, I'm not sure of the best way to get `textBaseline` and `textHeight`. Especially since my textflow has multiple types of segments with different heights, and some are text and some are not.

**Comment by Jugen** [comment]
Hey, that's great :-)

Okay, so I have two suggestions on how to go about this:

1.  The parent of Canvas is TextFlow so just grab the first Text item from its children:
```java
public double getBaselineOffset()
{
    // Hopefully the canvas is a child of TextFlow at this point ?
    // Change, if you may want to find a more specific Text node ....
    Optional<Text> text = getParent().getChildrenUnmodifiable().stream()
            .filter( n -> n instanceof Text )
            .map( n -> (Text) n )
            .findFirst();

    if ( text.isPresent() )
    {
        double txtBase = text.get().getBaselineOffset();
        double txtHeight = text.get().getLayoutBounds().getHeight();
        // This is my own untested calculation and probably isn't right ?
        return txtBase + (txtHeight - txtBase)/2 - getHeight() / 2;
    }

    return getHeight() * 0.75;
}
```
2.  If the Canvas doesn't have a parent when getBaselineOffset() is invoked then I think you'll need to create a local dummy Text object with the same font characteristics as what is being displayed and use that.

**Comment by Jugen** [comment]
@mgroth0 hope you came right with this .... please reopen if not.
