### ISSUE TITLE
How to save text from StyleClassedTextArea

### ISSUE THREAD

**Issue by Ppsoft1991** [FXMisc/RichTextFX#1020]
I define some css and use StyleClassedTextArea to display some colorful text.How can I save already displayed text with color?

now I used 
```
this.styleClassedTextArea.getText()
```

**Comment by Jugen** [comment]
You can either process each styled part yourself with for example:
```java
area.getParagraphs().stream()
    .flatMap( p -> p.getStyledSegments().stream() )
    .forEach( ss -> System.out.println( ss.getStyle() +" text: "+ ss.getSegment() ) );
```
or you could save in binary format using the codecs, see the [RichTextDemo](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext/RichTextDemo.java)

**Comment by Ppsoft1991** [comment]
It's a good plan.But it doesn't know whitch is Enter.

such as, I have a text:

![image](https://user-images.githubusercontent.com/18442117/121661329-ada4c180-cad6-11eb-9218-db113a00aab3.png)

it will output:
1.[black] text: My 
2.[red] text: dog
3.[black] text: so
4.[green] text: cute
5.[black] text: .
6.[black] text: My dog so cute.

there is a Enter between 5 and 6

**Comment by Jugen** [comment]
Yeah, you're right - so then the stream needs to be expanded into two for loops:
```java
for ( Paragraph<Collection<String>,String,Collection<String>> p : area.getParagraphs() )
{
    for ( StyledSegment<String,Collection<String>> ss : p.getStyledSegments() )
    {
        System.out.println( ss.getStyle() +" text: "+ ss.getSegment() ) );
    }
    System.out.println();
}
```
