### ISSUE TITLE
Question: how to get font size from CodeArea

### ISSUE THREAD

**Issue by hibonda** [FXMisc/RichTextFX#1023]
Not sure if this is a request for a feature or I just can't find it, if so then:
Desired Feature
-ability to get font size
-ability to get font family
-ability to get font style

On my program I create a CodeArea to act as a logger(console out is redirected to this window) with syntax highlighting, at the moment there isn't any syntax highlighting, apart from the basic CSS definitions on startup.
CSS definitions for CodeArea object
````css
.code-area-logger {
    -fx-background-color: derive(-fx-m-base-green, -10%);
    -fx-font-size: 1.1em;
    -fx-font-family: 'Source Sans Pro', sans-serif;
}
````
The font is a resource as .ttf and is loaded and registered at program startup.

The issue I am facing is that I need to auto-scroll down to last line on the logger (similar to other loggers behaviour out there, e.g.: Chrome console, IntelliJ) everytime a new line is added, to do this I need to calculate the font size so I could know the height of one line, then set the scroll to pixel based on the amount of lines.
The closest thing I could do is get the style class and hardcode match it against what I have defined in the CSS
````java
for (String s : codeArea.getStyleClass()) {
    if (s.equals("code-area-logger")) {
        foundStyleClass = true;
        break;
    }
}
````
but then I cannot get the font size, as I am working with EM sizes in CSS, because of the different screen sizes; I believe the EM gets calculated from the screen DPI.
Now things start to get complicated, I am scanning on my style sheet to find the style code block, then I am scanning for font size, then I extract the em value. This solution is only partially useful as in the future I plan to give to the user the ability to change font size, which will include the logger - thus my CSS value for EM font size is going to be irrelevant and I will have to read back the style from the CodeArea.

**Surely there must be a more simplistic way to get the existing font size which has alreay been written to the CodeArea, with its corresponding style..**

## Environment info:

- RichTextFX Version:  0.9.3
- Operating System:  Win 10, MacOs HighSierra
- Java version: 1.8.0_291-b10

**Comment by Jugen** [comment]
> The issue I am facing is that I need to auto-scroll down to last line

Just use `area.requestFollowCaret()` after appending, and it'll happen for you :-)

**Comment by hibonda** [comment]
Fair enough. Reasonable solution.
