### ISSUE TITLE
Caret position and custom segments

### ISSUE THREAD

**Issue by tchudyk** [FXMisc/RichTextFX#1024]
I see problem with caret position when I have custom segments inside editor.

For example let's say I have custom segment which is a (not editable) Label with text "[Section]".

This segment has overiden `BaseSegment` methods like this:

```
@Override
public int length() {
    return label.getText().length();
}

@Override
public String getText() {
    return label.getText();
}
```

When I invoke method `GenericStyleArea.getText()` I receive correct text from editor with this component like:
**"Text before [Section] text after"** - and this is cool. When I want only part of this text, I can use `getText(from, to)` and this also works awesome.

But there is a problem with caret when I'm editing text in editor - it looks like caret try to treat this "[Section]" segment/label like one-char segment not like 9 chars segment. 
When I listening on caret position change: 
```
area.caretPositionProperty().addListener((observableValue, oldValue, newValue) -> {
            System.out.println(newValue);
});
```
It returns "visual" position, not the actual position inside text.
When I want to for example break line on caret position, or replaceText - it do it on wrong position.

---

Edit (3 hours later).
When I'm looking at `CaretNode` implementation - model seems to be ready to handle that situations - there are separate properties for `paragraphIndex`, `columnPosition` and `position`. From the perspective of my problem `paragraphIndex` and `columnIndex` has correct values - caret visually is in that place, but `position` property is wrong because it has other position in source code.

---

Edit 2:
As some kind of workaround - I can change in segment to return always it's length as `1`:
```
@Override
public int length() {
    return 1;
}
```

But then I had some problems with `ReadOnlyStyledDocument.offsetToPosition(...)` - sometimes it throws in that case `IndexOutOfBoundsException`, when calculating caret position in `CaretNode` class for attributes `paragraphIndex` and `columnPosition`.

To solve this problem, I have overriden implementation of `GenericStyledArea.offsetToPosition(...)` to return position of the last char in document when position is out of bounds:

```
@Override
public Position offsetToPosition(int charOffset, Bias bias) {
    if (charOffset > getLength()) {
        return getContent().offsetToPosition(getLength(), bias);
    } else {
        return getContent().offsetToPosition(charOffset, bias);
    }
}
```

But this all (length==1) generates me more other problems... - I use `RichTextFx` as "rendering" layer... all "business" logic about formating is in anotherLayer (which do not know anything about what part of text is displayed as this labeled-read-only-components), and (for example) when I generate in that layer informations about additional styles to apply to parts of text, it's apply them to wrong "spans" because all that "custom segments" have other length in display layer. :/

**Comment by Jugen** [comment]
@tchudyk sorry for the late response to this, it somehow slipped through the cracks .....
I'm not sure if this will help but have a look at the [hyperlink demo](https://github.com/FXMisc/RichTextFX/tree/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/hyperlink) which I think behaves in the way that you want.
(PS: Sorry I should have posted this sooner but I wanted to look into the demo so I could give you more directed guidance but unfortunately I haven't found the time.)

**Comment by tchudyk** [comment]
Hyperlink demo is not exactly solution for my problem - hyperlink is text segment - we can put caret anywhere inside it. The problem is when we want insert something that is not a text segment and is larger then 1 char in source `length() > 1` and we want this to be represented as 1 segment (cursor can appear only before and after segment).

Another example here can be pointers list in markdown... We can have text like:
```
 - point 1
- point 2
  - point 3
```

and we want to represent pointers as image, but "under" this image we have text ` - ` (3 chars with spaces). `getText()` method will return this ` - ` text, and length of this text will be 3.

Visual representation using segments will be:
```
[*][point 1]
[*][point 2]
[*][point 3]
```
But source segment representation will be:
```
[ - ][point1]
[- ][point2]
[  - ][point3]
```

I think the problem is that caret position is related with a "visual position" not with "source" position computed using `BaseSegment.length()` and `BaseSegment.getText()` where non-text segments (bigger than 1 char) cannot have caret inside segment.

But currently changing the approach in RichTextFx at this stage already seems (to me) quite complicated.

**Comment by Jugen** [comment]
Okay, so if I understand correctly there's a difference between the source position and the visual position like:
```
Some text [a label] more text.
0123456789012345678901234
          1         2
```
So from a source perspective to style `more` as **bold** would be, eg: &nbsp; _setStyle( 20, 24, bold );_
but visually from RichTextFX's perspective we have: 
```
Some text L more text.
012345678901234567890
          1         2
```
so it's actually supposed to be, eg: &nbsp; setStyle( **12**, 16, bold );  &nbsp; _// that is 12 and not 20_

Then maybe what you need is a method to convert from a source position to the visual position, something like:
```java
// Untested concept code ....
int sourceToVisualPos( int target ) // So 20 should return 12
{
   int sourcePos = 0, visualPos = 0;

   for( var p : getParagraphs() )
   {
      if ( sourcePos == target ) return visualPos;

      for( var s : p.getSegments() )
      {
         if ( s instanceof String ) // or TextExt ?
         {
            var len = s.length();
            if ( sourcePos + len > target ) len = target - sourcePos;
            sourcePos += len;
            visualPos += len;
         }
         else // some other segment type
         {
            sourcePos += s.toString().length();
            visualPos += 1;
         }

         if ( sourcePos == target ) return visualPos;
      }

      // Plus 1 for paragraph and line breaks ?
      sourcePos++;
      visualPos++;
   }

   return visualPos;
}
```

**Comment by Jugen** [comment]
FYI, I've added and tested this method in my [StyledSegmentTextArea](https://github.com/Jugen/StyledSegmentTextArea/tree/master/lightware/richtext) project.

**Comment by tchudyk** [comment]
Ok, I changed the model by separating the presentation logic from the data and calculating the position between data and presentation with something like this example above.
