### ISSUE TITLE
How to put the placeholder at the top of a GenericStyledArea?

### ISSUE THREAD

**Issue by garybentley** [FXMisc/RichTextFX#1025]
I'm setting a TextFlow placeholder on my GenericStyledArea with the following code:

```
TextFlow tf = new TextFlow (new Text (myText));
tf.prefWidthProperty ().bind (this.widthProperty ());
tf.maxHeightProperty ().bind (tf.heightProperty ());
tf.minHeightProperty ().bind (tf.heightProperty ());
tf.setCenterShape (false);
area.setPlaceholder (tf);
```

How even with the constraints above it is placing the placeholder text about half-way down the visible area of the text area.  As shown below:

![placeholder-location](https://user-images.githubusercontent.com/921991/123012025-da28d980-d404-11eb-92ef-b920ab781c39.jpg)

Is there any way (in a GenericStyledArea) to force the placeholder to be at the top of the area so it looks like "normal" (albeit differently styled) text?

**Comment by Jugen** [comment]
Hi Gary

You'll need to override `GenericStyledArea.configurePlaceholder( Node )`  and make it a no-op or put your code in there:
```java
    protected void configurePlaceholder( Node placeholder )
    {
        placeholder.prefWidthProperty().bind( widthProperty() );
        placeholder.maxHeightProperty().bind( placeholder.heightProperty() );
        placeholder.minHeightProperty().bind( placeholder.heightProperty() );
        placeholder.setCenterShape( false );
    }
```

**Comment by garybentley** [comment]
Thanks that worked, although I had to cast the Node to a Region to get access to the properties.

Also, is it possible to get the online javadoc updated?  I had found the configurePlaceholder method in the javadoc but there was no method comment.  When I check the source though there is a method comment that would have told me what I needed to do :)

**Comment by Jugen** [comment]
Updated JavaDoc as requested :-)

**Comment by garybentley** [comment]
Thank you, that's great :)
