### ISSUE TITLE
Upgrade gradle to 7.x

### ISSUE THREAD

**Issue by afester** [FXMisc/RichTextFX#1027]
RichtextFX currently uses Gradle 5.2.1, and the build scripts are using deprecated features. In order to keep up with latest Gradle features, the Gradle wrapper and the build scripts should be upgraded to 7.1.1.

**Comment by afester** [comment]
There are some issues with Gradle 7.1.1, in particular with the Eclipse buildship plugin (https://github.com/eclipse/buildship/issues/1091). This was fixed in the upcoming 7.2 release, but for the time being its probably best to upgrade to 7.0.2 first

**Comment by Jugen** [comment]
Thanks @afester :-)  Are you working on submitting a PR for this ?

**Comment by afester** [comment]
Yes, I am currently working on that - hope to have it ready soon ;-)

**Comment by Jugen** [comment]
Great :-)  While you are at it, can you please bump the flowless dependency to version 0.6.4 ?
Unless you think that should be a separate commit ?

**Comment by Jugen** [comment]
In the meantime I've also had a look at this but couldn't get OSGi working as the `biz.aQute.bnd.builder` plugin [can't handle](https://github.com/bndtools/bnd/issues/2227) multi-release Jars ?

**Comment by afester** [comment]
> Great :-) While you are at it, can you please bump the flowless dependency to version 0.6.4 ?
> Unless you think that should be a separate commit ?

Yes, I planned to check the external dependencies anyway - I would do that separately though, after I finished the Gradle upgrade

**Comment by afester** [comment]
> In the meantime I've also had a look at this but couldn't get OSGi working as the `biz.aQute.bnd.builder` plugin [can't handle](https://github.com/bndtools/bnd/issues/2227) multi-release Jars ?

Yes I just came across the same ... I tried to use the `biz.aQute.bnd.builder` plugin but got `error  : Classes found in the wrong directory: ...`. There are some suggestions in the link above which I will try.
Besides that the build seems to work fine with Gradle 7.0.2 so far ... integration tests are executing, and the demos can be launched

**Comment by afester** [comment]
I have completed the adjustments of the build scripts and checked that the main tasks (assemble, build) are working and that the generated jar files contain the proper set of files.
The creation of the OSGi related MANIFEST entries works, but there are some (minor) differences:

1. The `Bundle-SymbolicName` attribute changed from `org.fxmisc.richtext.fx` to `richtextfx`.

2. In the `Export-Package` attribute, the `SNAPSHOT` suffix has been removed from the version strings:

```
org.fxmisc.richtext;version="1.0.0.SNAPSHOT";uses:=...
org.fxmisc.richtext.event;version="1.0.0.SNAPSHOT";uses:=...
org.fxmisc.richtext.model;version="1.0.0.SNAPSHOT";uses:=...
org.fxmisc.richtext.util;version="1.0.0.SNAPSHOT";uses:=...
```
becomes

```
org.fxmisc.richtext;version="1.0.0";uses:=...
org.fxmisc.richtext.event;version="1.0.0";uses:=...
org.fxmisc.richtext.model;version="1.0.0";uses:=...
org.fxmisc.richtext.util;version="1.0.0";uses:=...
```

3. In the `Import-Package` attribute, `com.sun.javafx.css.converters` has been added, and the version string has been removed from the `org.fxmisc.richtext` packages:

```
...
org.fxmisc.richtext;version="[1.0,2)"
org.fxmisc.richtext.event;version="[1.0,2)"
org.fxmisc.richtext.model;version="[1.0,2)"
org.fxmisc.richtext.util;version="[1.0,2)"
...
```

becomes

```
com.sun.javafx.css.converters
...
org.fxmisc.richtext
org.fxmisc.richtext.event
org.fxmisc.richtext.model
org.fxmisc.richtext.util
...
```
I am not very familiar with OSGi, so I do not know if these changes might have any negative side effect - if anyone is more familiar with OSGi, I would appreciate any feedback ;-)

**Comment by njbartlett** [comment]
I'm replying here purely as somebody who knows something about OSGi, but nothing about this Github project, so I apologise for the lack of context (I saw this question posted on Twitter because I follow the OSGi hashtag).

> I have completed the adjustments of the build scripts and checked that the main tasks (assemble, build) are working and that the generated jar files contain the proper set of files.
> The creation of the OSGi related MANIFEST entries works, but there are some (minor) differences:
> 
>     1. The `Bundle-SymbolicName` attribute changed from `org.fxmisc.richtext.fx` to `richtextfx`.

This is the core identity of the bundle, so changing it is probably not good because somebody might depend on the original identity.

> 
>     2. In the `Export-Package` attribute, the `SNAPSHOT` suffix has been removed from the version strings:
> 
> 
> ```
> org.fxmisc.richtext;version="1.0.0.SNAPSHOT";uses:=...
> org.fxmisc.richtext.event;version="1.0.0.SNAPSHOT";uses:=...
> org.fxmisc.richtext.model;version="1.0.0.SNAPSHOT";uses:=...
> org.fxmisc.richtext.util;version="1.0.0.SNAPSHOT";uses:=...
> ```
> 
> becomes
> 
> ```
> org.fxmisc.richtext;version="1.0.0";uses:=...
> org.fxmisc.richtext.event;version="1.0.0";uses:=...
> org.fxmisc.richtext.model;version="1.0.0";uses:=...
> org.fxmisc.richtext.util;version="1.0.0";uses:=...
> ```
> 

This is a good change. SNAPSHOT has no meaning in a package version.

>     1. In the `Import-Package` attribute, `com.sun.javafx.css.converters` has been added, and the version string has been removed from the `org.fxmisc.richtext` packages:
> 
> 
> ```
> ...
> org.fxmisc.richtext;version="[1.0,2)"
> org.fxmisc.richtext.event;version="[1.0,2)"
> org.fxmisc.richtext.model;version="[1.0,2)"
> org.fxmisc.richtext.util;version="[1.0,2)"
> ...
> ```
> 
> becomes
> 
> ```
> com.sun.javafx.css.converters
> ...
> org.fxmisc.richtext
> org.fxmisc.richtext.event
> org.fxmisc.richtext.model
> org.fxmisc.richtext.util
> ...
> ```
> 

The package import on `com.sun.javafx.css.converters` has been detected because some part of of your bundle uses that package. This presents problems because, like most `com.sun.*` packages, it is internal and not supported API. Also anybody using your bundle would need to find another bundle that exports that package.

Removing the version ranges from the imports is not good because it means your bundle can import *any* version, which could include incompatible versions.

> I am not very familiar with OSGi, so I do not know if these changes might have any negative side effect - if anyone is more familiar with OSGi, I would appreciate any feedback ;-)

**Comment by Jugen** [comment]
Wow @njbartlett  thanks very much for the input, it's very much appreciated.

@afester thanks for the PR so far, looks good.

`com.sun.javafx.css.converters` only gets used in [JavaFXCompatibilty](https://github.com/FXMisc/RichTextFX/blob/17bdba2cf9bcb04771dbabe7c544f92ec8400c12/richtextfx/src/main/java/org/fxmisc/richtext/JavaFXCompatibility.java#L68) when running with Java 8. In the multi-release jar there is an alternative JavaFXCompatibilty for Java 9 and higher (where the com.sun...converter isn't used).

I suppose at the very least the `Bundle-SymbolicName` attribute changed from `org.fxmisc.richtext.fx` to `richtextfx` needs to be reverted. A bonus would be to keep the version ranges as well.

**Comment by afester** [comment]
Thanks a lot @njbartlett - this is excellent feedback :-)

I will check if I can do something about the symbolic name and the version ranges (looks like the BND gradle task behaves differently from the previous OSGi plugin ...)

**Comment by afester** [comment]
I have moved the configuration of the OSGi bundle from build.gradle into a "bnd.bnd" file in the richtextfx sub project.
This allows a simpler tweaking of the bundle MANIFEST attributes. With that, the same MANIFEST entries are now created as before, the only remaining differences are the updated BND tool version and the removal of the SNAPSHOT suffix. 
I think this should now be ready to be merged :-)
