### ISSUE TITLE
How do I change the background color of a line number?

### ISSUE THREAD

**Issue by Richard-Tang** [FXMisc/RichTextFX#1028]
I want to change its background color

![image](https://user-images.githubusercontent.com/30547741/124881841-5f65de00-e002-11eb-9d40-07d591bce59f.png)

**Comment by Jugen** [comment]
You can use CSS to style it: `.styled-text-area .lineno { .... }`

**Comment by Richard-Tang** [comment]
> You can use CSS to style it: `.styled-text-area .lineno { .... }`

ok，thank you very much。
