### ISSUE TITLE
How do I change the background color of the selected area?

### ISSUE THREAD

**Issue by Richard-Tang** [FXMisc/RichTextFX#1029]
Mouse drag and select the default is blue

I want change it

![image](https://user-images.githubusercontent.com/30547741/125170103-d1dfe500-e1df-11eb-90f5-d62649aa3cdd.png)

**Comment by Richard-Tang** [comment]
> 鼠标拖动选择默认为蓝色
> 
> 我想改变它
> 
> ![图像](https://user-images.githubusercontent.com/30547741/125170103-d1dfe500-e1df-11eb-90f5-d62649aa3cdd.png)

I found it in the source code, but it doesn't seem to be described in the wiki.

```css
.main-selection
{
    -fx-fill: black;
}
```

**Comment by Jugen** [comment]
See SelectionPath [here](https://github.com/FXMisc/RichTextFX/wiki/RichTextFX-CSS-Reference-Guide#the-richtextfx-css-reference-guide) :-)
