### ISSUE TITLE
Horizontal Scroll Bar does not work correctly with LineNumberFactory

### ISSUE THREAD

**Issue by atsepushel** [FXMisc/RichTextFX#1030]
## Expected Behavior
CodeArea always showing caret (scrolling to visible) on keyboard moving (left/right buttons)

## Actual Behavior
CodeArea not showing caret on keyboard moving (left/right buttons). Scroll begin moving only after few  keyboard "right" button clicks, looks depended on LineNumberFactory nodes width

## Reproducible Demo
- Your default JavaKeywordsDemo.java
- Run and change window width for showing horizontal scroll bar
- ![photo_2021-07-16_19-46-06](https://user-images.githubusercontent.com/62481461/125981586-97e480bb-fb17-4a92-90e7-3f777bd2a700.jpg)
- Set caret position to the end of the line that is not fully visible and tries move with the keyboard to the right
- Visible area begin moving only after few buttons button clicks

## Environment info:
- RichTextFX Version: 0.10.6
- Operating System: Windows 10
- Java version: 1.8.0_112

**Comment by Jugen** [comment]
@appsofteng thanks very much for this, have submitted a PR in Flowless to fix this.
