### ISSUE TITLE
Add feature to InlineCssTextArea to dynamically change highlight color

### ISSUE THREAD

**Issue by Yossi-77** [FXMisc/RichTextFX#1041]
## Desired Feature

It's currently possible to change dynamically/programmatically the text coloring with the InlineCssTextArea using for example:

``` 
setStyle(startRange, endRange, "-fx-fill:red");
```
Using "-fx-highlight-fill" does not seem to work and I have seen this property discussed elsewhere.  It would be great to be able to also change the coloring of the (mouse) selection highlight on the fly via code, without a dependency on css stylesheets. Ideally you would be able to specify this per range (as you can for the the text fill color in the example above), however just being able to change the single color (from the default DODGERBLUE in the SelectionPath property) for all mouse selections on the fly would also be very useful.  I can see that that Selection and CaretSelectionBind provide a:
```
    void configureSelectionPath(SelectionPath path);
```
method, but it does not seem possible to hook into this (and perhaps that would be the wrong approach anyway).  It may already be possible to achieve this dynamically.  If so, any directions would be much appreciated.

**Comment by Jugen** [comment]
Yeah, so it appears you can't change the MAIN selection highlight on the fly via code.
However you should be able to change the fill color of any custom selection highlights that you add.
The implementation of the _Selection_ interface is `SelectionImpl` which has various constructors.
The ones that take a `Consumer<SelectionPath>` parameter will enable you to customize the selection fill property of the Path.
If you bind the Path's fill property to your own Paint property in the Consumer it should change on the fly.

**Comment by Yossi-77** [comment]
Hi Jurgen, Thanks for the quick reply.

This simple example seems to do what is required at first (it overrides the default mouse selection with a green alternative / gets access to the Path for potential binding of its Fill property):
```
Selection overlaySelection = new SelectionImpl("overlay", this, path -> ((Path) path).setFill(Color.GREEN));  // access to the Path

addSelection(overlaySelection);

selectionBoundsProperty().addListener((obs, oldVal, newVal) -> overlaySelection.selectRange(getSelection().getStart(), getSelection().getEnd()));
```

It breaks however, as soon as I hit enter.  I think the custom Selection is being associated with the original block of text and typing an enter character splits the text and breaks this relationship?  I am hoping that there is a simple solution to this and that it is easy to identify when this happens and perhaps create a new Selection each time?

Thanks again for your help.

**Comment by Jugen** [comment]
Just a wild guess that maybe it's a timing issue ?  Maybe try something like the following and see if this works:

```java
selectionBoundsProperty().addListener( (obs, oldVal, newVal) -> Platform.runLater
(
    () -> overlaySelection.selectRange( getSelection().getStart(), getSelection().getEnd() )
));
```

**Comment by Yossi-77** [comment]
Ok, I tried wrapping in a runLater and didn't seem to help.  I also change made the following change within the selection bounds listener, which seemed to improve things slightly, but the behavior appears to be pretty inconsistent still:

```
Selection underlyingSelection = getCaretSelectionBind().getUnderlyingSelection();
overlaySelection.selectRange(underlyingSelection.getStartParagraphIndex(), underlyingSelection.getStartColumnPosition(), underlyingSelection.getEndParagraphIndex(), underlyingSelection.getEndColumnPosition());
```

I'll dig around a bit more.

**Comment by Jugen** [comment]
An alternative idea to try is to remove the overlay selection and then adding it again with the update, something like:
```java
selectionBoundsProperty().addListener( (obs, oldVal, newVal) ->
{
    removeSelection( overlaySelection );
    overlaySelection.selectRange( getSelection().getStart(), getSelection().getEnd() );
    addSelection( overlaySelection );
});
```

**Comment by Yossi-77** [comment]
Thanks again for the suggestion.  I've tried that, but no luck.  I've also tried putting the addSelection in a runLater (still no luck).  

I have got something that does work though.. It's pretty desperate:

```
public class TestTextArea extends InlineCssTextArea {

	public TestTextArea() {

		final Selection underlyingSelection = getCaretSelectionBind().getUnderlyingSelection();

		Selection overlaySelection = new SelectionImpl("overlay", this, path -> ((Path) path).setFill(Color.GREEN)) {

			@Override
			public int hashCode() {

				return underlyingSelection.hashCode();
			}


			@Override
			public boolean equals(Object o) {

				return underlyingSelection.equals(o);
			}

		};

		selectionProperty().addListener((obs, oldVal, newVal) -> {

			removeSelection(overlaySelection);
			overlaySelection.selectRange(underlyingSelection.getStartParagraphIndex(), underlyingSelection.getStartColumnPosition(), underlyingSelection.getEndParagraphIndex(), underlyingSelection.getEndColumnPosition());
			addSelection(overlaySelection);
		});
	}
}
```

I think I could see in the code that the Selections end up in a set.  There is a check in the code that should prevent the main underlying selection being removed, but given it's going into a set, that check can be circumvented by hacking the equals method of any new Selection.  My theory was that the underlying Selection was being rendered over the overlay Selection (I don't know if that is actually true) and getting rid of the underlying Selection might leave the desired behavior.  

If this gives you any clue as to how to put in place a cleaner solution it would be great to know.  For now, I guess I will keep this in place, given it appears to function robustly, even if pretty terrible code.

**Comment by Jugen** [comment]
LOL that's ingenious, I love it !!!  :-)

If the main-selection is overwriting your's then maybe you can try setting the main-selection to transparent ?

**Comment by Yossi-77** [comment]
Ah, good point, if that works then the solution is much cleaner.

I really struggle with css.  As far as I can tell, I need to set the underlying highlight to be transparent via css stylesheet.  That works, because it's a one-off operation and I can still do what I want in code dynamically.

So I have in a new 'richtextfx' css file: 

```
.styled-text-area {
    -fx-highlight-fill: transparent;
}
```
And added the line to my code : 	getStylesheets().add("css/richtextfx.css");

But it's not being picked up (although I can put other properties in there and they are).  My guess is that I need to further qualify the .styled-text-area part.  I've checked in the RichTextFX-CSS-Reference-Guide, but I don't think this property is covered there.

I am guessing I am missing something obvious?

**Comment by Jugen** [comment]
I think it should be:
```css
.styled-text-area .selection {
    -fx-fill: transparent;
}
```

**Comment by Yossi-77** [comment]
Thank you - that worked.  It also fixed the issue too.  I can now get rid off the equals override and I only need to add the custom overlay selection once (but continue to update its bounds via a listener obviously) and it all works as expected.  So it seems the underlying selection was rendering over the custom selection.  I'll close this issue, but really appreciate your help with this.  Thanks.

**Comment by Yossi-77** [comment]
Solution found - link a custom Selection's range to the underlying selection attached to the CaretSelectionBind and make the underlying selection transparent to prevent it rendering over the custom selection.
