### ISSUE TITLE
Text in FoldableStyledArea or GenericStyledArea looks blurry

### ISSUE THREAD

**Issue by jzlhll** [FXMisc/RichTextFX#1046]
Hi,

Issues:

Devices:
   MacBook Pro (Retina, 15-inch, Mid 2015) 
                      this is retina HD screen, macbook；
   another display device  monitor DELL P2417H
                      this is a normal dp screen, link it to mac.

When I has the same text shown in area, code likes:
`FoldableStyledArea area = new FoldableStyledArea();`
`VirtualizedScrollPane vpane = new VirtualizedScrollPane<>(area);`
`//add vpane to root node.`
`area.replace(xxx)`

show on retain screen mac looks good:

![looksGood](https://user-images.githubusercontent.com/19789292/140472236-f0c68a83-377b-411b-8aba-ce62eb5270d6.jpg)

but dragged the javafx app to second monitor, it will looks blurry and wild colorfu:

![looksUrly](https://user-images.githubusercontent.com/19789292/140472245-81304fe0-97da-4ed0-a03c-300f4499bd55.jpg)

Suggest:
https://github.com/javafxports/openjdk-jfx/issues/225
https://stackoverflow.com/questions/23728517/blurred-text-in-javafx-textarea

I've read some pages, tells that maybe a javafx issue for scrollPane,  or 'cache' , 'Snap To Pixel' skin etc.
and still not fix on openfx16.

While  the GericStyledArea implements Region. Maybe we can fix or has workaround by this project.

Please try it and feedback in free time...
Best wishes.

**Comment by Jugen** [comment]
Could you please try this with the latest version of RichTextFX 0.10.7 and see if it still happens.
I tried on Windows 10 with 150% scaling, JRE 11 as well as 17, and it was crisp.

**Comment by jzlhll** [comment]
I've with richtextFX 0.10.7 already, JDK is 16.0.1, openfx 16.

Maybe you could try it on retina mac os; and link another monitor.
Drag to main mac to the monitor.

I think it maybe javafx default issue. I'am seeking for a workaound.
Still I want to report to openjfx.
Because the other control or label, editText is same with this issue

**Comment by jzlhll** [comment]
I will try it and feed back.

**Comment by jzlhll** [comment]
Finally, i figure it out.
Two ways to fix it:

define two config:  boolean  hd1, hd2.
1.          
if (hd1) {
        scene = new Scene(rootView, info.width, info.height);
        //scene = new Scene(rootView);
} else {
        //according to your config `isDefault` to use it to new scene
        scene = new Scene(rootView, info.width, info.height, true, SceneAntialiasing.BALANCED);
}

2.
    if (!hd2)) {
      System.setProperty("prism.lcdtext", "false");
      //System.setProperty("prism.subpixeltext", "false"); 
  }
