### ISSUE TITLE
Question: how to setStyle by batch?

### ISSUE THREAD

**Issue by jzlhll** [FXMisc/RichTextFX#1047]
Hi, 
Just like replace, it has MultiChangeBuilder.java
We can use multiply replaceText(int start, int end, String text),
and last commit().

Some like that.

I want to setStyle(int paragraph, int from, int to, S style)
to custom color for multi-lines key words.
But one bye one is too slow.

Can it implement like MultiChangeBuilder as a transaction(batch action)?

**Comment by Jugen** [comment]
You could try `StyleSpansBuilder`, see the [JavaKeywordsDemo](https://github.com/FXMisc/RichTextFX/blob/cb963f71390edffaee346f09e46c06d240be224f/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/JavaKeywordsDemo.java#L153-L170) on how to use. Something like:
```java
var ssb = new StyleSpansBuilder<....>();
ssb.add( style1, length1 );
ssb.add( emptyStyle, length );
ssb.add( style2, length2 );
area.setStyleSpans( paragraphNo, columnNo, ssb );
```
Note: that this **replaces** any existing style spans for the range of text affected by the builder.

**Comment by jzlhll** [comment]
thanks, It is done.
