### ISSUE TITLE
Is overtype/insert mode possible?

### ISSUE THREAD

**Issue by garybentley** [FXMisc/RichTextFX#1050]
I've had a request to support overtype or insert mode, where you press the "Insert" key on the keyboard and it will overwrite the text.  Is it possible to do this in the GenericStyledArea or does it need something new to be added?

**Comment by Jugen** [comment]
Hi Gary, I've added this to `GenericStyledAreaBehavior`. 
Please have a look at PR #1051 and give feedback if needed.

**Comment by garybentley** [comment]
Thanks that looks like it will be perfect.
