### ISSUE TITLE
showParagraphAtCenter

### ISSUE THREAD

**Issue by DaveJarvis** [FXMisc/RichTextFX#1053]
Feature request:

``` java
  private final StyleClassedTextArea mTextArea =  new StyleClassedTextArea();

  public void moveTo( final int offset ) {
    assert 0 <= offset && offset <= mTextArea.getLength();
    mTextArea.moveTo( offset );
    mTextArea.requestFollowCaret();
    mTextArea.showParagraphAtCenter();
  }
```

Considerations for behaviour:

* If the document height is less than the viewport height, nothing happens.
* If the document height is less than 1.5 times (?) the height of the viewport, behaves like `showParagraphAtBottom` (not sure about this one?).
* If the document height is more than 1.5 times the height of the viewport, then the caret's paragraph is centered on the viewport.

Effectively, when someone is searching for text, it's nice to make the search result centered, which is where people tend to look while editing a document.

Note: When `showParagraphAtTop`, `showParagraphAtBottom`, and `showParagraphAtCenter` are not given a paragraph index, perhaps use the default caret's current paragraph? (This might not make sense if there are multiple carets.)

Here are a couple of screenshots showing the actual and desired behaviours. There doesn't appear to be a way to request that a particular paragraph be aligned to the center of the viewport.

**Actual:**

![keenwrite-search-01](https://user-images.githubusercontent.com/2131950/141696948-629aaed5-39e9-4177-a64c-9fb54fbfb115.png)

**Desired:**

![keenwrite-search-02](https://user-images.githubusercontent.com/2131950/141696949-9bfa3545-a22d-4c3e-889b-640fb479fc96.png)

**Related:** #612 

P.S.
By the way, there was a bug that made the search result always appear just outside of the viewport, forcing the user to scroll to see the match. Thanks for fixing it! Seems like the search text now always appears at the bottom within the viewport, which itself is a great improvement.

**Comment by Jugen** [comment]
Implemented in PR 1054 with simple scroll to center as far as document height allows.
