### ISSUE TITLE
vi emulation

### ISSUE THREAD

**Issue by DaveJarvis** [FXMisc/RichTextFX#1057]
What would be involved in adding rudimentary support for vi emulation?

https://www.adminschoice.com/wp-content/uploads/2009/12/vi-editor-Cheat-Sheet.pdf

Plus support for arrow keys, <kbd>home</kbd>, <kbd>end</kbd>, <kbd>pg dn</kbd>, <kbd>pg up</kbd>, <kbd>insert</kbd>, and <kbd>delete</kbd>?

Minus support for I/O operations (although having events/listeners for saving, opening, and such commands would be useful).

A few Java implementations include:

* https://github.com/IanDarwin/edj (a subset of **ed**, itself a subset of **vi**)
* https://github.com/rsharifnasab/sbu_vi_limited (rudimentary implementation)
* https://github.com/JetBrains/ideavim (GPL v2)
* http://jvi.sourceforge.net/ (MPL)

**Comment by Jugen** [comment]
I think the place to start with this inside RichTextFX would be to have a look at [GenericStyledAreaBehavior](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledAreaBehavior.java).

The _GenericStyledArea_ constructor simply executes: `new GenericStyledAreaBehavior( this );`  to attach key handling to the editor. So my thinking is maybe create a ViAreaBehavior class with the vi key-bindings and actions, that a developer can then invoke in like manner to add the vi key-bindings ?
