### ISSUE TITLE
Styles aren't being copied and/or applied on a copy/paste

### ISSUE THREAD

**Issue by garybentley** [FXMisc/RichTextFX#1062]
When I copy and paste some styled text using the GenericStyledArea.copy/paste methods, when it pastes it doesn't seem to be applying the styles.

The example image below shows this.  I've copied the bold/italic/underlined text and then pasted it below the styled text but of course the styles are missing.

Any idea what I'm doing wrong?  Might it have something to do with the setUseInitialStyleForInsertion method (which I'm setting to false)?
  
![styled-text-copy-paste](https://user-images.githubusercontent.com/921991/147797403-8e7d8fe2-f84f-419d-a071-2740e4d6624e.jpg)

**Comment by Jugen** [comment]
I'm guessing that you've extended GenericStyledArea to make your own custom area, but that you haven't set any style codecs for it. The result is that the paste method in _ClipboardActions_ is just grabbing the text from the clipboard and inserting it as is.

To fix this, if your custom area is using inline styling like in _InlineCssTextArea_ then you need to add:
```java
 area.setStyleCodecs( Codec.STRING_CODEC, Codec.styledTextCodec( Codec.STRING_CODEC ) );
```
Otherwise if it's using CSS styling tags like in _StyleClassedTextArea_ then you need to add:
```java
area.setStyleCodecs(
    Codec.collectionCodec( Codec.STRING_CODEC ),
    Codec.styledTextCodec( Codec.collectionCodec( Codec.STRING_CODEC ) )
);
```
Or if you have your own custom styling like in _RichTextDemo_ then you'll need something like:
```java
area.setStyleCodecs(
    ParStyle.CODEC,
    Codec.styledSegmentCodec( Codec.eitherCodec( Codec.STRING_CODEC, LinkedImage.codec() ), TextStyle.CODEC )
);
```
Here are links to [ParStyle](https://github.com/FXMisc/RichTextFX/blob/f35220fc5d9fbea32ce9a8d1ddd05a8903359b5a/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext/ParStyle.java#L23-L52) and [Codec](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/model/Codec.java) if you need more info and to see how it's done.

**Comment by garybentley** [comment]
Thanks, that worked.

For those who find this, you can also tinker with the copied text before the paste occurs.  I have to do this in my use of GenericStyledArea because the text has a uniform font family and font size and the user may be copying from a different area that is using a different font family/size.  To do this override the "paste" method and do something like the following (note you'll have to modify to use your own paragraph style/text style/segment classes):


```
@Override
public void paste ()
{

        // Copied from richtext/ClipboardActions.paste.
        Clipboard clipboard = Clipboard.getSystemClipboard();

        if(getStyleCodecs().isPresent()) {
            Tuple2<Codec<ParaStyle>, Codec<StyledSegment<AbstractSegment, TextStyle>>> codecs = getStyleCodecs().get();
            Codec<StyledDocument<ParaStyle, AbstractSegment, TextStyle>> codec = ReadOnlyStyledDocument.codec(codecs._1, codecs._2, getSegOps());
            DataFormat format = DataFormat.lookupMimeType(codec.getName ());
            if(format == null) {
                format = new DataFormat(codec.getName ());
            }
            if(clipboard.hasContent(format)) {
                byte[] bytes = (byte[]) clipboard.getContent(format);
                ByteArrayInputStream is = new ByteArrayInputStream(bytes);
                DataInputStream dis = new DataInputStream(is);
                StyledDocument<ParaStyle, AbstractSegment, TextStyle> doc = null;
                try {
                    doc = codec.decode(dis);
                } catch (IOException e) {
                    System.err.println("Codec error: Failed to decode '" + codec.getName() + "':");
                    e.printStackTrace();
                }
                if(doc != null) {

                    // We need to create a new document from the one generated from the codec so 
                    // that the paragraph and text styles can be updated.  You can also set a per paragraph 
                    // style if required, just use a different addParagraph method from the builder.
                    TextStyle ts = getTextInsertionStyle();
                    ReadOnlyStyledDocumentBuilder b = new ReadOnlyStyledDocumentBuilder(getSegOps(), getParagraphInsertionStyle ());

                    for (Paragraph<ParaStyle, AbstractSegment, TextStyle> p : doc.getParagraphs())
                    {
                        b.addParagraph (p.getSegments (),
                                        p.getStyleSpans().mapStyles(ss ->
                                        {
                                            TextStyle s = new TextStyle(ss);
                                            // Modify your style here.
                                            return ss;
                                        }));
                    }

                    replaceSelection(b.build ());
                    return;
                }
            }
            return;
        }

        super.paste ();
}

```
