### ISSUE TITLE
Selection shape is not rectangular when selecting over multiple lines of text

### ISSUE THREAD

**Issue by garybentley** [FXMisc/RichTextFX#1063]
I'm using 0.10.7.  If I have a number of lines of text selected by click and dragging the mouse over the text I get the following selection:

![selection-angle](https://user-images.githubusercontent.com/921991/147866009-2e742fa4-8778-4401-989b-5903648149e1.jpg)

This also happens if I use the keyboard to select across multiple lines.

However if I triple click on a single line of text or click and drag over all the text on a single line I get:

![selection-single](https://user-images.githubusercontent.com/921991/147866029-08a7a1ec-0263-4c24-9dee-353bd68fa082.jpg)

I'm not styling the selection path at all and this only occurs if I select multiple lines.

This ONLY occurs if I select text, if I select/drag at the end of a paragraph (and drag to the next paragraph) the first paragraph selection is a rectangle.  For example:

![selection-multiple-end-of-line](https://user-images.githubusercontent.com/921991/147866072-b657ddeb-6540-47e4-9171-8b9d33ea8138.jpg)

Any idea what's going wrong?

**Comment by Jugen** [comment]
I recall long ago seeing something like this before and thought it had been fixed. I wonder if this a regression or something new ?
It looks like interparagraph spacing is messing up the selection path.  I'll have a look during the week .....

**Comment by garybentley** [comment]
I've tried 0.10.5 and the problem is there too.  It's definitely related to the padding on the paragraph node.  If I don't set any padding (on the bottom) of the node then it draws a rectangle.  I think it's using the text size as the starting height of the selection box rather than the line size + padding.  In the examples I gave each line was a paragraph.

If I try selecting multiple lines within a paragraph then it draws rectangle, it's only on the final line of paragraph (when there's bottom padding) that the problem occurs.

**Comment by Jugen** [comment]
Thanks for checking and the feedback. Can you provide the CSS you're using to set the inter-paragraph spacing as I'm not able to replicate the problem with my efforts. Even better would be a simple demo that show the problem. Thanks.

**Comment by garybentley** [comment]
I'm using the css: 

-fx-text-alignment: left;-fx-line-spacing: 0.0pt;-fx-padding: 0 3px 11.2pt 3px;

for the paragraph.

After doing some testing the culprit seems to be the combination of setting -fx-line-spacing AND -fx-padding.  Setting them individually without the other and things work fine.  The alignment doesn't matter.

Hope this helps, if you still can't reproduce it let me know and I'll try and create a minimum demo for the problem.

**Comment by Jugen** [comment]
Sorry Gary, I've tried various ways of replicating the behavior without success ?  So I'll need the minimum demo from you.
Also having scanned through various sections of code, could you try:  `-fx-line-spacing: 0.01;` instead of 0.0 and see what happens.

**Comment by garybentley** [comment]
When the line spacing is above 0 then the selection is a rectangle, when it is <= 0 then it has the weird shape.  Although even at <= 0 the intra-paragraph selection block is a rectangle.  It's only when you select some text on the last line of the paragraph and select part of another paragraph that it happens.

I'll try and get the demo together.

**Comment by garybentley** [comment]
Just to add a bit more detail.  I dug into what shape the SelectionPath is drawing when the line-spacing is less than 0.  I did this to make sure it wasn't something I was doing that was causing it.

For the image below it drew the following box (via the drawing commands move to and line to), the first number is the X coord, the second is the Y coord:

MOVE: 0.0, 57.400001525878906
LINE: 1316.0, 57.400001525878906
LINE: 1316.0, 96.46666036315105
LINE: 0.0, 78.4000015258789
LINE: 0.0, 57.400001525878906

![selection-block-draw](https://user-images.githubusercontent.com/921991/148137612-c1fd2407-49b7-494b-adf7-526f78ea03a5.jpg)

I believe the problem is in lines:

LINE: 1316.0, 96.46666036315105
LINE: 0.0, 78.4000015258789

here the line is dropping down to Y coord 96 but then a line is being drawn back to Y coord 78.  If I'm reading it right I think the second line should be drawing back to Y coord 96.

**Comment by garybentley** [comment]
Sorry to spam, I haven't had chance to do the demo yet but looking at the ParagraphText code I think the issue may lie in the "getRangeShapeSafely(int, int)" method.  At line 382 it is using getHeight to get the bottom right location of the selection which is the reason why it's using the padding.  However at line 387 it gets the line spacing and applies that but only if the value is positive.

Anyway, just a thought.

**Comment by Jugen** [comment]
Yeah, your observations line up with my analysis. 
So I think the solution is to add the following after line [382](https://github.com/Jugen/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java#L378-L382) in the same code block:

```java
int bottomLeftIndex = bottomRightIndex + 1;
shape[bottomLeftIndex] = new LineTo(0.0, getHeight());
```

**Comment by garybentley** [comment]
Would that mean that bottom line included the padding though?  But I think it's on the right track.

I've also got the minimum demo ready now, see below:

```
import javafx.scene.*;
import javafx.scene.layout.*;
import javafx.scene.control.*;
import javafx.stage.*;
import javafx.application.*;

import org.fxmisc.richtext.*;

public class SelectionTest extends Application
{

    public static void main (String[] args)
    {

        Application.launch (args);

    }

    @Override
    public void start (Stage stage)
    {

        String lorem = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum sollicitudin dui gravida posuere. Vestibulum eros sem, tempor eu diam non, ultrices interdum nunc. Ut facilisis lobortis mi et euismod. Nullam convallis orci nec ornare hendrerit. Nunc a nibh turpis. Proin bibendum dignissim imperdiet. Mauris vitae tincidunt arcu. Donec euismod vitae nibh at vulputate.\n"
        + "Morbi vehicula pretium fermentum. Donec efficitur turpis vel sem placerat, in posuere erat aliquam. Praesent sodales blandit neque, in condimentum nisi vehicula sit amet. Quisque tincidunt quis nulla vel cursus. Nunc quis ex velit. Curabitur libero urna, cursus dignissim mollis eu, tincidunt eu purus. Nulla id ullamcorper ligula.\n"
        + "Donec at ante ut felis feugiat suscipit eget at metus. Mauris sit amet ante sit amet leo vulputate porttitor. Phasellus eget purus lobortis, sodales enim sit amet, fringilla tortor. Duis ac massa quis nisl convallis laoreet vitae quis lorem.\n"
        + "Etiam eu eros accumsan, rhoncus purus vel, dictum odio. Pellentesque velit nisl, interdum ac semper id, cursus sed augue. Curabitur velit sem, accumsan eu purus et, dapibus sagittis odio.\n"
        + "Integer dictum odio eget tellus tempus suscipit. Aliquam id nisl ut massa feugiat ullamcorper. Sed non finibus purus, nec aliquet mi. Vestibulum at ante turpis. Ut at metus euismod odio ultricies tristique at ut arcu. Fusce vestibulum tortor eros, sit amet elementum nunc consequat sit amet. Nullam scelerisque aliquam turpis, at ultricies odio tristique non. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur maximus sodales lectus. Nulla mauris sapien, congue vel felis ut, eleifend egestas lorem. Nulla vitae congue magna.\n"
        + "Etiam ut sapien auctor, cursus ex a, tincidunt lorem. Aliquam aliquam faucibus tortor, nec pretium lorem dapibus eu. Integer faucibus sem id lectus maximus pulvinar. Morbi ex neque, convallis id risus id, varius semper elit. Nunc dapibus semper erat, eget tristique risus posuere sed. Sed ornare tincidunt rhoncus. Cras odio metus, tristique vitae velit in, rhoncus euismod nisi. Nullam justo enim, elementum in mauris at, iaculis vehicula nulla.\n"
        + "Nullam rutrum, metus vitae lobortis elementum, risus augue convallis nisi, non vestibulum sem ipsum nec lacus. Morbi vel nisl vel augue pulvinar placerat. Fusce dignissim, odio eget sagittis molestie, turpis arcu fringilla purus, ullamcorper porttitor elit sapien quis enim. Integer neque metus, accumsan ut diam at, venenatis varius libero. Vivamus porttitor vehicula massa eu porta. Etiam a ipsum sit amet erat placerat dictum. Donec eget metus sed justo tincidunt egestas. Integer at erat elit. Nam ipsum turpis, gravida sit amet suscipit ac, porttitor vulputate nunc. Maecenas luctus rutrum ipsum non blandit.";

        InlineCssTextArea t = new InlineCssTextArea ();

        t.setParagraphInsertionStyle ("-fx-padding: 0 0 50px 0;-fx-line-spacing: -10px;");

        t.replaceText (0, 0, lorem);
        t.setPrefWidth (500);
        t.setPrefHeight (500);

        Scene sc = new Scene (t);
        stage.setScene (sc);
        stage.sizeToScene ();
        stage.show ();

        t.selectAll ();

    }

}
```

**Comment by Jugen** [comment]
Great, thanks for that will submit PR to fix.
