### ISSUE TITLE
Setting GenericStyledArea.setLineHighlighterOn to false does not repaint the area and leaves the writing line highlighted

### ISSUE THREAD

**Issue by garybentley** [FXMisc/RichTextFX#1064]
Difficult to show this one but in 0.10.7 (and previous versions as far as I can tell), setting: GenericStyledArea.setLineHighlighterOn(false) doesn't repaint the text area and the highlight is left in place however if I force a repaint of the line, say by scrolling the line out of view and then back the highlight disappears.

**Comment by Jugen** [comment]
Thanks for reporting, PR has been submitted to fix.
