### ISSUE TITLE
How to use RichTextFx ?

### ISSUE THREAD

**Issue by ondrejurban220** [FXMisc/RichTextFX#1069]
I don't know how to use the RichTextFx in my project. I have tried to somehow put it in my project for hours but without success. I tried to include the fat jar into libraries, and other parth os the RichTextFx repository in my JavaFx application but without success. I couldn't find anywhere on the internet a step by step guide of how to somehow put it into the project. I found some but I am probably not skilled programmer enough to understand it. I don't use maven or gradle. Is there a way of how to use RichTextFx in my project ? It seems to me as it lacks a step by step guide of how to use RichTextFx without maven or gradle for not so skilled programmers.

I use IntelliJ idea.
Windows 10.
Java 11.

**Comment by QazCetelic** [comment]
I recommend using Maven or Gradle it's easier than manually managing JAR's. You can easily add it as dependency with a GUI here:
![screenshot](https://user-images.githubusercontent.com/51381523/177403032-e18620cd-8b67-43c3-89b9-24ddcbb740ee.png)
