### ISSUE TITLE
Feature: Set Lines Visible / Code Folding

### ISSUE THREAD

**Issue by RobertBColton** [FXMisc/RichTextFX#107]
If possible it would be nice if there could be some underlying support to hide or show line(s) n->n2
This would make it possible with paragraph graphic factory for a developer to implement code folding.

**Comment by Col-E** [comment]
Any updates on this? Roadmap?

**Comment by Jugen** [comment]
Am currently looking into maybe implementing this feature, will hopefully know next week sometime ....

**Comment by Col-E** [comment]
I'd love to see this feature in any capacity. Its one of the very few downsides of migrating away from Swing/RSyntaxTextArea.

**Comment by Jugen** [comment]
Thanks for the offer I'm doing okay at this stage :-)

I would like a vote/input on a preferred method name please:  

1.  hideParagraphs  /  unhideParagraphs
2.  collapseParagraphs  /  expandParagraphs
3.  foldParagraphs  /  unfoldParagraphs
4.  other ?

**Comment by Col-E** [comment]
If when the paragraph is collapsed there is still a line preview _(like how IDE's do it)_ then 2 or 3 seem to make the most sense.

**Comment by Jugen** [comment]
I was hoping to submit a PR by now but I'm not yet happy with the API. So this is just to let you know that I've basically got it done and there should be a PR next week sometime. Sorry for the delay ....

**Comment by Col-E** [comment]
Don't worry about the pace, take your time.

**Comment by Jugen** [comment]
Okay, a PR has been submitted. Will merge next week sometime pending any feedback or changes .....
