### ISSUE TITLE
How to start line numbering from other number than 1 ?

### ISSUE THREAD

**Issue by ondrejurban220** [FXMisc/RichTextFX#1072]
Is there a way of numbering lines in RichTextFx starting from different number than 1 ? I used this code "codeArea.setParagraphGraphicFactory(LineNumberFactory.get(codeArea));" for showing number of line in RichTextFx but is there a way of having number 100 for example insted of 1 in that lines numbering ? Like: 

100 for(int i = 0; i < 100; i++)
101 {
102   print("i: " + i);
103 }
104 
105 //...

I know that questions should contain information about my OS, RichTextFx version... but I consideret it redundant here.

**Comment by ondrejurban220** [comment]
Thank You :) . Should it work even if i work with java 11 ? Because i have not done it yet, but i tried.

**Comment by ondrejurban220** [comment]
Now i have this problem
![gitphoto](https://user-images.githubusercontent.com/71831601/150402168-0f97a065-f034-4607-8903-3b46f5f98d97.png)

**Comment by ondrejurban220** [comment]
Or probably i don't know how to make create my own LineNumberFactory that would work.

**Comment by mat4pat** [comment]
![image](https://user-images.githubusercontent.com/85194618/150666397-878dca91-f7e3-4659-82f8-2bf6fe157865.png)

I've tried this, however this doesn't achieve your needs. Hopefully you can mess around with this and find a work-a-round.
Best of luck
