### ISSUE TITLE
Expose moveCaretUpLines/moveCaretDownLines methods in GenericStyledArea

### ISSUE THREAD

**Issue by garybentley** [FXMisc/RichTextFX#1077]
In my application I'm trying to implement a "typewriter scrolling mode" whereby the caret stays on the same line/position in the view and the text scrolls up and down around it.

Getting the caret to stay in the same place is easy, however trying to scroll the caret up/down by a line in response to mouse scroll events is proving difficult.  Essentially when the user scrolls the mouse I want the same behavior as when they press KeyCode.KP_UP/KeyCode.KP_DOWN.

Would it be possible to add methods to GenericStyledArea (or CaretSelectionBind) that allow the caret to be moved up/down by a specific number of lines?  The behavior I'm looking for is essentially GenericStyledAreaBehavior.downLines(SelectionPolicy selectionPolicy, int nLines) but that method is private and you can't get to the behavior from GenericStyledArea.  

I tried copying the code from the behavior and the area but there are too many private objects that I can't access to make it work.

**Comment by Jugen** [comment]
Hi Gary, apologies for not getting back to you sooner on this .....

What I understand you are asking for seems to me to be the same behavior as `nextPage` and `prevPage`, just restricted to lines.
So as a starting point I've added a method `scrollLines( SelectionPolicy, int )` which leverages the same paging code to keep the cursor in the same place visually on screen but to move the lines of text up/down relative to it.

Could you please review and if possible try it out and see if it does what you need it to do.
Otherwise if I've misunderstood just let me know and we can refine, rework, whatever ....

**Comment by Jugen** [comment]
Submitted PR #1086

**Comment by garybentley** [comment]
It's no problem :) I'm sure you're busy!  I haven't been able to try the code, I can't get my local version of richtextfx to compile and because I'm using java 17 gradle won't work either (ironically).

I did look at the code though and it looks like it will do exactly what I need thank you.

Incidentally do you have a timeframe for when version 0.10.8 will be released?

**Comment by Jugen** [comment]
wrt 0.10.8 I would like to get it out by the end of the month latest, hopefully.

Question re API, do you think `scrollLines` is a suitable method name for this ?  My concern is that its behavior is different to the scroll methods. Would maybe `nextLine` and `prevLine` be better as it aligns with the behavior of `nextPage` and `prevPage` ?
Your thoughts would be appreciated, thanks.

**Comment by garybentley** [comment]
Thanks for letting me know about 0.10.8.

I tend to agree that method names "nextLine" and "prevLine" would be better, especially because it will be consistent with "nextPage" and "prevPage".  Anything that reduces the thinking time when looking at an API is a good thing in my view.

**Comment by Jugen** [comment]
Okay, have made the API changes.
Here's release candidate for you to try: [richtextfx-0.10.8-rc1.zip](https://github.com/FXMisc/RichTextFX/files/8031241/richtextfx-0.10.8-rc1.zip)
(just rename zip to jar)

**Comment by Jugen** [comment]
Note that calls to `nextLine` or `prevLine` when the caret isn't visible is a noop.

**Comment by garybentley** [comment]
Thank you for the jar.  I've tested it and can confirm that it fixes a number of issues:

1. The highlighting of the line where the caret is now disappears when you setLineHighlighterOn to false.

2. The selection now uses a rectangle even when the line-spacing and padding is less than 1.

3. The nextLine/prevLine methods work as expected and will move the caret up/down by a single line.

Thanks again for these fixes and features :)
