### ISSUE TITLE
ParagraphBox is not respecting the managed property for the paragraph graphic node

### ISSUE THREAD

**Issue by garybentley** [FXMisc/RichTextFX#1078]
As the title.  ParagraphBox is incorporating the paragraph graphic node into the layout calculations even when the managed property is set to false.

I actually have a use-case for this (rather than just being a property pedant).  In relation to #1077 when I enable the typewriter scrolling mode I want the paragraph graphic to disappear, i.e. so the user is left with just the writing area, no scrollbar, no paragraph graphic.  Essentially it's a "distraction free" mode.  I have the managed property for the graphic bound to the visible property but the graphic is still being laid out when the graphic's visibility is hidden.

There is a workaround in that you can set the width of the graphic to 0.

**Comment by Jugen** [comment]
So then in **ParagraphBox** would changing _getGraphicPrefWidth()_ to the following work:
```java
double getGraphicPrefWidth() {
    return graphic.filter( Node::isManaged )
	.map( n -> n.prefWidth(-1) )
	.getOrElse( 0.0 );
}
```

**Comment by garybentley** [comment]
I think that goes most of the way however the graphic will still be laid out with zero width.  So perhaps ParagraphBox.layoutChildren should also do a isManaged check?

The definition of the managed property is:

"If the node is unmanaged, its parent will ignore the child in both preferred size computations and layout."

(from https://docs.oracle.com/javase/8/javafx/api/javafx/scene/Node.html#managedProperty )

There may be some ramification for the node being laid out with zero width, I'm not sure.  I don't know if it could respond to input events with zero width.  I think user expectation and compliance with the definition would be the main issue.

**Comment by Jugen** [comment]
Note that the _Region_ parent class of _ParagraphBox_ is honoring the graphic's managed property. It's just that the local _layoutChildren_ method wasn't, and thus incorrectly relocating the enclosed _ParagraphText_. Anyways, I have added an additional check in the PR to not try and relocate the graphic if it's not managed. So it should be good now :-)

**Comment by garybentley** [comment]
Thanks, sounds good :)
