### ISSUE TITLE
Line highlighter should not be displayed when a (multiline) selection is present

### ISSUE THREAD

**Issue by effad** [FXMisc/RichTextFX#1082]
## Expected Behavior

When a selection is present, especially if it spans multiple lines, the line highlighter (turned on with `codeArea.setLineHighlighterOn(true)`) looks unnatural and should not be displayed.
If the selection is only a part of a line it could stay.

## Actual Behavior

The line highlighter is always displayed, giving unusual visual patterns.

## Reproducible Demo

Use any of the demos and insert a call to .setHighlighterOn(true), then select two lines.

## Environment info:

- RichTextFX Version: 0.10.7
- Operating System: Linux
- Java version: 17

<hr>

![grafik](https://user-images.githubusercontent.com/4497475/152373492-1772bf48-2df6-44ec-bada-42697b5dbc62.png)

![grafik](https://user-images.githubusercontent.com/4497475/152373748-471efe5c-5a8d-4ad2-9401-b5db41435c6d.png)

**Comment by Jugen** [comment]
Okay, have submitted a PR.
