### ISSUE TITLE
MultiChangeBuilder should not throw new IllegalStateException("Cannot commit multiple changes since none have been added"); when empty

### ISSUE THREAD

**Issue by effad** [FXMisc/RichTextFX#1083]
## Desired Feature

When building a multi change with MultiChangeBuilder it may often occur that no actual changes will be registered (e.g. replace all function with no matching search results).
Either the MultiChangeBuilder should just ignore (i.e. noop) in such a case or at least provide API to allow it's caller to see if there are changes to commit.

## Current Workarounds

At the moment one has to clumsily note if there are actual changes in the MultiChangeBuilder, e.g. like this:
```
	private void replaceAll(ActionEvent e) {
		boolean hasChanges = false;
		MultiChangeBuilder<?, String, ?> multiChange = area.createMultiChange();		
		IndexRange range = getSearchFunction().search(area.getSelectedText(), search.getText(), 0);
		while (range != NOT_FOUND) {			
			multiChange.replaceText(range.getStart(), range.getEnd(), getReplacement(area.getText(range)));
			hasChanges = true;
			range = getSearchFunction().search(area.getSelectedText(), search.getText(), range.getEnd());
		}
		if (hasChanges) {
			multiChange.commit();
		}
	}
```

**Comment by Jugen** [comment]
I have no idea what the thinking is behind MultiChangeBuilder throwing IllegalStateException and it not rather being a noop as suggested.  So I've submitted a PR adding a `hasChanges()` method, which will help.
