### ISSUE TITLE
Thin horizontal lines appear between lines of text at some positions when scrolling vertically

### ISSUE THREAD

**Issue by swpalmer** [FXMisc/RichTextFX#1091]
## Expected Behavior

There should be no visible gaps between lines of text.

## Actual Behavior

When scrolling vertically think horizontal lines appear between the lines of text. Some scroll positions are worse than others, so have no lines.  IT appears to be a single pixel or less, depending on the scroll position.

## Reproducible Demo
CoreArea with a stylesheet that sets the line background to a dark color makes it easier to see.

See attached screenshots, taken from the same program with slightly different scroll positions.

## Environment info:

- RichTextFX Version: 0.10.7
- Operating System: macOS 12.2.1
- Java version: 17.0.2 (Zulu build from Azul that includes JavaFX)
-
<img width="518" alt="Screen Shot 2022-02-15 at 3 32 23 PM" src="https://user-images.githubusercontent.com/757620/154145233-3b30f4d4-13c2-4ca4-ab16-0f1bb34baa70.png">
<img width="523" alt="Screen Shot 2022-02-15 at 3 32 30 PM" src="https://user-images.githubusercontent.com/757620/154145241-4384b082-20b6-433e-9c0d-1d06b8db2dd5.png">

**Comment by Jugen** [comment]
This is a bug in the [Flowless](https://github.com/FXMisc/Flowless) library that RichTextFX uses.
