### ISSUE TITLE
Horizontal scrolling of a CodeArea can result in large empty blocks in the upper right of the viewport

### ISSUE THREAD

**Issue by swpalmer** [FXMisc/RichTextFX#1092]
## Expected Behavior

Viewport rendering should fill consistently regardless of scroll position or direction.

## Actual Behavior

When scrolling content to the left sometimes large blocks in the upper right corner of the viewport are left blank

More visible with a dark background for the text lines.
Blocks start after last character on the line and extend to the edge of the viewport and down to where they hit a longer line.
See attached screenshot.

## Environment info:

- RichTextFX Version: 0.10.7
- Operating System: macOS 12.2.1
- Java version: 17.0.2 with JavaFX 17 modules included (Zulu build from Azul)
<img width="540" alt="Screen Shot 2022-02-15 at 3 58 15 PM" src="https://user-images.githubusercontent.com/757620/154148530-413f3634-109d-474e-bc82-08cc6d1f6fca.png">

**Comment by Jugen** [comment]
I suspect that this due to the behavior/dynamics of the [Flowless](https://github.com/FXMisc/Flowless) library that RichTextFX uses.

**Comment by Jugen** [comment]
Kinda fixed by PR dealing with thin lines between cells, although empty blocks still flash briefly before being filled.
