### ISSUE TITLE
How to higlight a particular line in CodeArea ?

### ISSUE THREAD

**Issue by ondrejurban220** [FXMisc/RichTextFX#1093]
Is there a way of highlighting/changing style of a particular line in CodeArea ?

For example:

line1
line2
line3
line4

would result in line2 being red or highlighted or something similar.

**Comment by Jugen** [comment]
You can add an extra selection/highlight like so:

```java
Selection extra = new SelectionImpl( "extra", codeArea, 29, 38 );
codeArea.addSelection( extra );
```

**Comment by ondrejurban220** [comment]
I was looking more for this solution with usage of style classes.  

codeArea.setStyle(2, Collections.singleton("highlighter"));

But thanks, anyways.
