### ISSUE TITLE
How to make text blink using RichTextFx?

### ISSUE THREAD

**Issue by PashaTurok** [FXMisc/RichTextFX#1099]
I want to make my text blink. So, I did this way. 

CSS:

```
.my-class {
     -fx-animation: blinker 1s linear infinite;
}

@keyframes blinker {
  50% {
    -fx-opacity: 0;
  }
}

```
Java:

```
StyleClassedTextArea textArea = new StyleClassedTextArea();
textArea.append(text, "my_class");

```
But it didn't work. Could anyone help me?

**Comment by Jugen** [comment]
Umm, I've looked in the latest [JavaFX CSS Reference guide](https://openjfx.io/javadoc/18/javafx.graphics/javafx/scene/doc-files/cssref.html) and I don't find either `-fx-animation:` or `@keyframes` in there ?  The latter according to the reference is not supported, see the [limitations section](https://openjfx.io/javadoc/18/javafx.graphics/javafx/scene/doc-files/cssref.html#introlimitations).

If you can figure out how to do this on an ordinary JavaFX [Text node](https://openjfx.io/javadoc/18/javafx.graphics/javafx/scene/text/Text.html) then you should be able to get it to work in StyleClassedTextArea. I suggest asking on [StackOverflow](https://stackoverflow.com/questions/tagged/javafx) to see if somebody maybe knows how to do this on a `Text` node.

**Comment by Jugen** [comment]
There's unfortunately no API in RichTextFX to do that. Here's a method though that'll return the last Node.

_But be **WARNED** that any edits to a paragraph / line or visibility changes (e.g. scrolling out of view and then back) will result in it being recreated and your effects being lost !_

```java
private Optional<Text> getLastTextNode( GenericStyledArea<?,?,?> area )
{
    Parent virtualFlow = (Parent) area.getChildrenUnmodifiable().get(0);
    Parent navigator = (Parent) virtualFlow.getChildrenUnmodifiable().get(0);
    List<Node> boxList = navigator.getChildrenUnmodifiable();
    Parent lastBox = (Parent) boxList.get( boxList.size()-1 );
    Parent lastParagraph = (Parent) lastBox.getChildrenUnmodifiable().get(0);
    List<Node> contents = lastParagraph.getChildrenUnmodifiable();
    
    for ( int n = contents.size()-1; n > -1; n-- )
    {
        Node item = contents.get( n );

        if ( item instanceof Text )
        {
            System.out.println( item );
            return Optional.of( (Text) item );
        }
    }

    return Optional.empty();
}
```

**Comment by PashaTurok** [comment]
@Jugen Thank you very much for your help. An [issue](https://bugs.openjdk.java.net/browse/JDK-8283676) was opened here about adding CSS animation to JavaFX, so , I think I will wait for it - maybe in 5 - 10 years they will do it.
