### ISSUE TITLE
Setting font-family with CSS doesn't work

### ISSUE THREAD

**Issue by PashaTurok** [FXMisc/RichTextFX#1101]
This is my code:
CSS:
```
.message {
    -fx-fill:green;
    -fx-font-family: 'DejaVu Sans Mono';
}

```
Java:

```
StyleClassedTextArea textArea = new StyleClassedTextArea();
...
textArea.append(text, "message");
```
However, I see that text is not monospaced.

But if I do 
```
textArea.setStyle("-fx-font-family: 'DejaVu Sans Mono';");
```
Then text is monospaced. Could anyone say if this is a bug or expected behavior?

**Comment by Jugen** [comment]
It should work ?  Did you attach the style sheet to the text area ?  Something like:
```java
textArea.getStylesheets().add( "path/to/style/sheet.css" );
```

**Comment by PashaTurok** [comment]
@Jugen Thank you. The problem was in fonts.
