### ISSUE TITLE
Wrong results in small text area with mono space.

### ISSUE THREAD

**Issue by PashaTurok** [FXMisc/RichTextFX#1105]
There is some problem when the following code is used:

```
public class JavaFxTest2 extends Application {

    private final StyleClassedTextArea textArea = new StyleClassedTextArea();

    private final VirtualizedScrollPane scrollPane = new VirtualizedScrollPane(textArea);

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
        var s = "org.fxmisc.richtext.StyleClassedTextArea" + System.lineSeparator();
        s += "fxmisc.richtext.StyleClassedTextArea" + System.lineSeparator();
        s += "StyleClassedTextArea" + System.lineSeparator();
        VBox.setVgrow(textArea, Priority.ALWAYS);
        VBox root = new VBox();

        root.getChildren().addAll(textArea);
        textArea.append(s, "base");
        textArea.setWrapText(true);
        var css= this.getClass().getResource("test2.css").toExternalForm();
        var scene = new Scene(root, 150, 150);
        scene.getStylesheets().add(css);
        primaryStage.setScene(scene);
        primaryStage.show();
    }
}
```

And CSS:

```
.base {
    -fx-font-family: 'DejaVu Sans Mono';
    -fx-font-size: 15px;
    -fx-fill:black;
}
```

And this is the result:

![Screenshot from 2022-04-01 22-16-57](https://user-images.githubusercontent.com/10261361/161327643-11b1ac72-9a8d-46d7-91fe-8781ad019e48.png)

At the same time, if you change the size of the window (text area), then everything is ok:

![Screenshot from 2022-04-01 22-18-22](https://user-images.githubusercontent.com/10261361/161327851-f760c950-9b19-4ca5-918f-c64c20b2539b.png)

System Info: openjdk: 14.0.2, JavaFX: 19-ea+3, richtextfx: 0.10.9, OS: Ubuntu 20.04.3

**Comment by PashaTurok** [comment]
@Jugen Could you give just a hint what is the problem here. Is this a bug or I do something wrong?

**Comment by Jugen** [comment]
Try moving `textArea.append( s, "base" );` to after `primaryStage.show();` and it should render correctly.

**Comment by PashaTurok** [comment]
@Jugen Yes, your solution helped for the test I posted. But could you explain the reasons of such behavior? I am asking, as in my real application I have floating window (with text area) in stack pane:
![Screenshot from 2022-05-25 23-20-30](https://user-images.githubusercontent.com/10261361/170360594-ff9cbd48-dee7-4a39-ba8f-e08064e90990.png)

When I scroll up/down in list view text area is cleared and new text is appended. I mean that only one instance of text area is used, it is visible and text is cleared and appended when text area is visible. I can't understand what is wrong here.

**Comment by Jugen** [comment]
Initially I thought that it's just because the RichTextFX component sometimes doesn't like its contents being changed unless its part of a scene/stage. However from your use case/screenshot it's clear that that's not the problem.

Further investigation seems to indicate (I think) that the incorrect rendering only occurs in the 1st paragraph. So if you prefix the text with "\n" then it renders correctly. Strange ???

**Comment by PashaTurok** [comment]
@Jugen Any ideas? Is this a bug? If it is when approximately it can be fixed? I just want to understand what I should do with my project.

**Comment by Jugen** [comment]
Have dug into this a bit more now and the problem is that sometimes the very first Paragraph/Node isn't connected to the `Scene` graph yet which results in the preferred height calculation being incorrect. This is mainly evident when the font **size** is increased.

I unfortunately don't know why this happens so can't fix it, but it can be detected and then corrected with an additional _requestLayout_. So I'm going to evaluate this and see. If you can use a fat jar of RichTextFX then I can provide it for you to evaluate as well ?

**Comment by PashaTurok** [comment]
@Jugen Thank you very much for your help. I am using JPMS framework, so I can work only with modules. This is what I have in my config:

	
	<module groupId="org.fxmisc.richtext" artifactId="richtextfx" version="0.10.9" />
	<module groupId="org.fxmisc.flowless" artifactId="flowless" version="0.6.9" />
	<module groupId="org.fxmisc.undo" artifactId="undofx" version="2.1.1" />
	<module groupId="org.fxmisc.wellbehaved" artifactId="wellbehavedfx" version="0.3.3" />
	<module groupId="org.reactfx" artifactId="reactfx" version="2.0-M5" />

But you can modify any modules and I will test everything you say without any problems.

**Comment by Jugen** [comment]
@PashaTurok Okay, please try changing the `flowless` module to version `0.6.10` and give feedback as to how it behaves.

**Comment by PashaTurok** [comment]
@Jugen I tested. Now it is working. But when text is replaced it a little bit `dancing`. Please, see attached video.

https://user-images.githubusercontent.com/10261361/173555231-2b140318-8fe7-4c33-a8cd-69cfd20156c5.mp4

**Comment by Jugen** [comment]
@PashaTurok  Thanks for video feedback :-) !   Yeah, I thought that might happen :-( was hoping it wouldn't be so bad.
Can you please send me the code for the demo in the video, so I can test alternative solutions.

**Comment by PashaTurok** [comment]
@Jugen Yes, thank you very much. `VirtualizedScrollPane` helped. Maybe that's why it was so difficult to reproduce this `dancing`. So, should I close this issue?
