### ISSUE TITLE
How to disable text dragging in StyleClassedTextArea?

### ISSUE THREAD

**Issue by PashaTurok** [FXMisc/RichTextFX#1106]
I want to disable text dragging in StyleClassedTextArea. I tried:

       textArea.addEventFilter(MouseEvent.MOUSE_DRAGGED, (MouseEvent event) -> {
            event.consume();
        });

But it didn't help. Could anyone say how to do it?

**Comment by Jugen** [comment]
Try the following:
```java
textArea.setOnSelectionDropped( EH -> {} );
```
