### ISSUE TITLE
VirtualizedScrollPane with StyleClassedTextArea does not scroll to bottom with dragging scrollbar

### ISSUE THREAD

**Issue by r-sop** [FXMisc/RichTextFX#1113]
## Expected Behavior

Dragging the Scrollbar to the bottom scrolls the text inside the StyleClassedTextArea to the last line.

## Actual Behavior

This works when using the mouse wheel:
![scroll_with_wheel](https://user-images.githubusercontent.com/106147246/169988938-0e76aea8-357e-473a-a992-e6144b211d08.PNG)

But not when dragging the scrollbar:
![scroll_with_bar_drag](https://user-images.githubusercontent.com/106147246/169988946-4a9fb4cf-15b7-4fe3-847e-b167686a8c73.PNG)

## Environment info:

- RichTextFX Version: 0.10.9
- flowless Version: 0.6.9
- Operating System: Windows 10
- Java version: 11.0.15
- FX version: 18

<hr>

## Current Workarounds

Extend the Text by adding a new line at the end.

**Comment by Jugen** [comment]
Thanks for reporting, can you please provide demo code as I haven't been able to reproduce my side.

**Comment by r-sop** [comment]
Thanks for the fast reply.

Will try. In a first attempt (without css) I also cannot reproduce it..

**Comment by r-sop** [comment]
Finaly had time to reproduce it with a minimal example:

```
<?xml version="1.0" encoding="UTF-8"?>

<?import org.fxmisc.flowless.VirtualizedScrollPane?>
<?import org.fxmisc.richtext.StyleClassedTextArea?>
<?import javafx.scene.layout.BorderPane?>
<BorderPane xmlns="http://javafx.com/javafx/" xmlns:fx="http://javafx.com/fxml" fx:controller="com.example.demo.HelloController">
    <center>
        <VirtualizedScrollPane>
            <content>
                <StyleClassedTextArea fx:id="area" style="-fx-padding: 0.5em;"/>
            </content>
        </VirtualizedScrollPane>
    </center>
</BorderPane>
```

Complete Source: [main.zip](https://github.com/FXMisc/RichTextFX/files/9413327/main.zip)

So the padding seems to be the problem.

**Comment by Jugen** [comment]
@r-sop  Thanks for the test case, have submitted a PR to Flowless to fix.
