### ISSUE TITLE
XMLEditorDemo renders tags in comments as tags

### ISSUE THREAD

**Issue by PashaTurok** [FXMisc/RichTextFX#1120]
XMLEditorDemo renders tags in comments as tags while it should render them as comment. Please, consider the following screen shot:

![Screenshot from 2022-06-20 18-12-46](https://user-images.githubusercontent.com/10261361/174632743-dae0b306-eae5-428e-9365-31eacdf5ff8b.png)

`BAD ITEM` is inside comment, so it is rendered wrongly.

**Comment by Jugen** [comment]
It appears that the author of XMLEditorDemo did this intentionally (???), see line 22: `(?<COMMENT><!--[^<>]+-->)`,
you can however change this to `(?<COMMENT><!--.+-->)` and it will behave more along the lines of what you want.
(_Note this doesn't work for multi-line comments_.)
