### ISSUE TITLE
README contains invalid links

### ISSUE THREAD

**Issue by QazCetelic** [FXMisc/RichTextFX#1128]
Multiple links in the README of projects using RichTextFX are broken.
1. [PsychSQL](http://softbydoc.dx.am/?page_id=135)
![PsychSQL broken page](https://user-images.githubusercontent.com/51381523/177402107-b89c7b4c-1a31-4d0f-9938-9f8fe54dc80c.png)
2. [Alt.Text](http://alttexting.com/)
![Alt.Text broken page](https://user-images.githubusercontent.com/51381523/177402158-97661af9-c433-40a6-aeac-3ab3dc4091b8.png)

**Comment by Jugen** [comment]
Thanks for the report :-)

I have removed the dead links.
