### ISSUE TITLE
Support wavy underlines

### ISSUE THREAD

**Issue by shoaniki** [FXMisc/RichTextFX#1131]
## Desired Feature

When a user is editing text in a StyledTextArea, I wish to indicate typos and other kinds of error using the standard visual representation of a wavy underline.

## Current Workarounds

So far as I can determine, underlines currently can only be solid or dotted straight lines.  Dotted underlines are not unheard-of for marking typos, and that's what the RichTextFX spellchecker demo currently uses, but it is not the most familiar representation and may confuse users, particularly if colors other than red are to be used for different types of annotation.

## Implementation Costs

I have a basic implementation which I am submitting for discussion as a PR.  It involves creating a couple of extra CSS properties and then adding a branch to the code that creates underline shapes.

**Comment by Jugen** [comment]
Thanks a lot for the PR :-)
