### ISSUE TITLE
Caret disappears after opening FileChooser

### ISSUE THREAD

**Issue by DaveJarvis** [FXMisc/RichTextFX#1133]
**Prerequisites**
Install:

* JDK 18
* Gradle 7.3
* git

Make sure both Java and Gradle have their `bin` directory in the `PATH` environment variable.

**Replicate**
I could not create a minimal example. Nevertheless, I've included steps to reproduce the problem 100% of the time using JDK 18 and Gradle 7.3 (do not use Gradle 7.5.1). First, install [ConTeXt](https://wiki.contextgarden.net/Installation) in a new terminal:

``` bash
mkdir -p $HOME/context
cd $HOME/context
wget http://lmtx.pragma-ade.nl/install-lmtx/context-linux-64.zip
unzip *zip
chmod +x install.sh
./install.sh
export PATH=$PATH:$HOME/context/tex/texmf-linux-64/bin
```

ConTeXt is installed in `$HOME/context`.

In the same terminal, continue by installing [KeenWrite](https://github.com/DaveJarvis/keenwrite) as follows:

``` bash
cd /tmp
git clone https://github.com/DaveJarvis/keenwrite
cd keenwrite
sed -i 's#textArea.setShowCaret#//textArea.setShowCaret#' ./src/main/java/com/keenwrite/editors/markdown/MarkdownEditor.java
sed -i 's#keenwrite#build/libs/keenwrite#' keenwrite.sh 
gradle clean jar
./keenwrite.sh
```

After KeenWrite launches, see the problem manifest itself by exporting a document as a PDF (brings up the native `FileChooser` dialog and a confirmation dialog):

1. Click **File → New**.
1. Type in a few lines of text.
1. Press `Control+P`.
1. Set **Name** to: `untitled.pdf`
1. Press `Enter`.
1. Wait for PDF to be typeset.
1. Press `Control+P`.
1. Set **Name** to: `untitled.pdf`
1. Press `Enter`.
1. Press `Enter` to confirm overwriting the existing PDF.

Do not use the mouse to click, always use the keyboard.

**Expected**
Caret appears in the text area, user can resume editing, pressing `Alt+Enter` on a misspelled word shows a context menu.

**Actual**
Caret is invisible, user can edit, pressing `Alt+Enter` on a misspelled word does not show the context menu.

**Work around**
To get the caret back, the user must un-focus the application and return to it.

**Fix**
Calling `setShowCaret( ON )` when the text area is initialized resolves the problem:

``` java
styleClassedTextArea.setShowCaret( ON );
```

This should not be necessary and may be a regression?

**Screenshots**
![caret-01](https://user-images.githubusercontent.com/2131950/183304797-f13a798b-0318-4c74-9411-a262aaf3f3b5.png)

![caret-02](https://user-images.githubusercontent.com/2131950/183304799-06b31cf1-f407-4a9e-af98-38eab2333b7b.png)

Unfortunately, I can't take a screenshot without the caret because as soon as the screenshot application opens, the caret becomes visible again.

**System**

``` bash
$ java -version
openjdk version "18.0.2" 2022-07-19
OpenJDK Runtime Environment (build 18.0.2+10)
OpenJDK 64-Bit Server VM (build 18.0.2+10, mixed mode, sharing)
$ uname -a
Linux hostname 5.18.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 07 Jul 2022 17:18:13 +0000 x86_64 GNU/Linux
$ gradle --version

------------------------------------------------------------
Gradle 7.3
------------------------------------------------------------

Build time:   2021-11-09 20:40:36 UTC
Revision:     96754b8c44399658178a768ac764d727c2addb37

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          18.0.2 (BellSoft 18.0.2+10)
OS:           Linux 5.18.10-arch1-1 amd64
```

**Comment by Jugen** [comment]
Hi, I tried the steps provided above with [RichTextDemo](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext/RichTextDemo.java) without success ?
(Using version 0.10.9, JavaFX 11 & 17 on Windows)

Does `Platform.runLater( () -> area.requestFocus() );` after saving help ?
What versions and OS are you using ?

**Comment by DaveJarvis** [comment]
>  What versions and OS are you using ?

Arch Linux. Java 18.

``` groovy
  // JavaFX
  implementation 'org.controlsfx:controlsfx:11.1.1'
  implementation 'org.fxmisc.richtext:richtextfx:0.10.9'
  implementation 'org.fxmisc.flowless:flowless:0.6.10'
  implementation 'org.fxmisc.wellbehaved:wellbehavedfx:0.3.3'
  implementation 'com.miglayout:miglayout-javafx:11.0'
  implementation 'com.dlsc.preferencesfx:preferencesfx-core:11.9.1'
```

> Hi, I tried the steps provided above 

Try the steps with KeenWrite to see the problem. I created a small demo but couldn't trigger the bug. KeenWrite is rather complex at this point, so figuring out exactly how to replicate the problem with a minimal working example would take days of effort.

> Does Platform.runLater( () -> area.requestFocus() ); after saving help?

Doesn't seem to, no. In `GuiCommands.java`, the `file_export` is called when typesetting a file to PDF. I added the `requestFocus` call both before and after typesetting (`     sExecutor.execute( task );`) and the caret still disappears. Also, when I add logging to the focus change listener, I can see that when the `FileChooser` dialog is closed, the `StyleClassedTextArea` does not receive a focus event. Adding the `setShowCaret(ON)` call reinstates the focus event.

My hunch is that somehow to the caret's visibility mode is either changed to AUTO or OFF when the GTK native code is called and not getting restored properly when focus is handed back to the JavaFX application.

I have a fix that works, but it was a 4-hour dog to debug and then guess at a solution.

Feel free to close if you don't want to investigate further.

**Comment by Jugen** [comment]
I tried the steps in Keenwrite 2.8.0 on Windows and the caret remains visible. So it appears that this is probably related to GTK.

Also noted that the save dialog window in KeenWrite has recently been changed from `jwheatsheaf` to native, which I'm assuming resulted in the caret now disappearing on GTK. Anyways it's hard to tell if this is a Java thing or a GTK one ?

Glad you found a workaround, sorry for the 4-hour hunt though.

**Comment by DaveJarvis** [comment]
> So it appears that this is probably related to GTK.

That'd make sense. They have another focus-related issue:

https://gitlab.gnome.org/GNOME/gtk/-/issues/5087

**Comment by DaveJarvis** [comment]
Closing because there's a work around, not because the problem is fixed.
