### ISSUE TITLE
getParagraphLinesCount() get wrong line count

### ISSUE THREAD

**Issue by Joezeo** [FXMisc/RichTextFX#1134]
#### getParagraphLinesCount() get wrong line count.
![bug1](https://user-images.githubusercontent.com/30520229/187257082-f651cf45-d03b-443d-8131-4368badd6740.png)
#### paragraph 9 and 18's line count should all be 2, but I getting 2 and 3 there.  
![bug2](https://user-images.githubusercontent.com/30520229/187257378-326417c4-3e7d-4452-92f7-e95bebe18609.png)

[There was the demo can reproduce the problem](https://github.com/Joezeo/rich_text_report)

**Comment by Jugen** [comment]
@Joezeo  Thank you very much for reporting and for the demo !!!
Will submit a PR to fix.
