### ISSUE TITLE
Double-clicking a word containing non-ASCII letters doesn't work properly in CodeArea

### ISSUE THREAD

**Issue by alesp** [FXMisc/RichTextFX#1138]
Double-clicking words containing non-ASCII letters doesn't work properly in CodeArea.

For example, German word "zurück": The "ü" acts like a word break here. Double clicking it at the begginning will select "zur". Double clicking it at the end will select "ck".

One way to fix this is to add **Pattern.UNICODE_CHARACTER_CLASS** to WORD_PATTERN definition in CodeArea.

```
protected Pattern WORD_PATTERN = Pattern.compile( "\\w+", Pattern.UNICODE_CHARACTER_CLASS );
```

**Comment by Jugen** [comment]
Thanks for the submission and recommendation. Have submitted a PR to fix  :-)
