### ISSUE TITLE
Your demo app does not have main class

### ISSUE THREAD

**Issue by garawaa** [FXMisc/RichTextFX#1140]
The demo app does not have main class definition in manifest file. So it can not work anyway. Please check and fix it.

**Comment by Jugen** [comment]
Hi @garawaa there isn't a single entry point to the demo apps, so you need to specify which demo you want to run on the command line.

You can see the currently available demos [here](https://github.com/FXMisc/RichTextFX/tree/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo), look at the code, and decide which one you want to give a try.

**Comment by Jugen** [comment]
Fixed via # 1151
