### ISSUE TITLE
Bug: Wrapped text causes screen and scrollbar flickering

### ISSUE THREAD

**Issue by Elmari** [FXMisc/RichTextFX#1141]
As soon as a paragraph with wrapped lines exceeds the size of the text area (and the scrollbar is displayed), the view starts to flicker as soon as you continue typing. The scrollbar then also wobbles up and down.

This can be recreated with the RichTextDemo in the repo:

![Animation](https://user-images.githubusercontent.com/1381848/195796325-edc019c4-4450-403b-8293-34b9e03699fa.gif)

I would also be happy to try to fix the error myself if anyone has a tip on where to start after troubleshooting.

## Environment info:
RichTextFX Version: 0.10.9
Operating System: Windows 11
Java version: Java 17
Tested with JavaFX version: 11 / 17 / 19

**Comment by Jugen** [comment]
This is most probably coming from the [Flowless](https://github.com/FXMisc/Flowless) library, so you can start looking there. In particular the problem I think seems to be with [VirtualizedScrollPane](https://github.com/FXMisc/Flowless/blob/master/src/main/java/org/fxmisc/flowless/VirtualizedScrollPane.java), as this behavior only occurs when the text area is wrapped in one.

**Comment by Elmari** [comment]
I have not been able to solve the problem yet, but may have found the cause of the problem: The VirtualizedScrollPane uses the totalHeightEstimateProperty, which ultimately comes from VirtualFlow#totalHeightEstimateProperty -> orientation.heightEstimateProperty -> virtualFlow#totalLengthEstimateProperty and this length estimate comes from the sizeTracker. the SizeTracker determines the totalLength as multiplying the number of cells by the averageLength. 
However, the cell count is briefly reduced by 1 when editing a paragraph. This can change the average a lot if the other paragraphs are normally shorter and this in turn causes the scrollbar to jump so much. After editing the cell, the cell count is back to the initial value (+1) and the Average is back to "normal". The solution might be that the averageLength and therefore the totalLength are only updated when no text is currently being entered.

Sample values of my tests when a letter is added to the paragraph:

totalLength (old value, new value): 28938.25 -> 1938.75
Average (old value, new value): 1315.375 -> 88.125
Cells: 1

and immediately after that: 

Total: 1938.75 -> 28938.25
Average: 88.125 -> 1315.375
Cells: 2

**Comment by Jugen** [comment]
Thanks a stack for the research and feedback so far !!!
Based on your reported observations and some experimentation I've submitted a PR that I believe fixes this.
Could you maybe try it and see .....

**Comment by Elmari** [comment]
Hm, unfortunately, that doesn't seem to have solved the problem yet (at least for me). When I use the PR's code, the scrollbar in the RichtextDemo still flickers.

**Comment by Elmari** [comment]
This may be because, even though 0 values are filtered out, the average is still temporarily multiplied with a cell count of `cells - 1`, resulting in a smaller totalLength than it should be.
I will hopefully be able to investigate the problem further on Friday at the latest. Maybe then I will have an update on this.

**Comment by Jugen** [comment]
Have made substantial additional changes to the PR to remove the flicker.
Please give it a try when you can, thanks.

**Comment by Elmari** [comment]
Thank you for your support regarding the bug! This improves it, however it sometimes still flickers.

One problem with this solution is that the scrollbar now flickers when the first paragraph is written. This flickering occurs either because the ScrollBarPolicy is "AS_NEEDED". In this case, the scrollbar is displayed temporarily for a short time and then hidden again. In the case of ALWAYS, the thumb of the scrollbar is temporarily at 100% height before it is scaled properly again. This is because totalHeightEstimate is still sometimes temporarily at 0. To illustrate I recorded a gif (I'm pasting the text here, but the same effect occurs if you're typing fast):
![Animation](https://user-images.githubusercontent.com/1381848/197169763-bf8dff41-3053-4a07-aae2-05a60656baeb.gif)

I'm not totally sure why (as the length calculation seems to be based on `cells`) but, while totalHeightEstimate is 0, lengthOffsetEstimate grows when pasting text like shown in the gif. 

Based on that the shown behavior can somewhat be improved by defining totalHeightEstimate as follows: 
```
   this.totalLengthEstimate = Val.combine(
                averageLengthEstimate, cells.sizeProperty(), lengthOffsetEstimate,
                (avg, n, lengthOffset) -> {
                    double total = n * avg;
                    return total > lengthOffset ? total : lengthOffset;
                });
```

This way the total length is never smaller than the length offset, which I think is an assumption we can make. 
However, while this fixes the showing / hiding of the scrollbar, ultimately all combined, it more or less looks the same like the gif posted in the initial comment of the bug report, only less frequent.
Also, if you enter paragraphs quickly the scrollbar lags behind now:
![Animation3](https://user-images.githubusercontent.com/1381848/197179096-47e8eee4-8a87-4a48-9800-9d3bf3b8bc5f.gif)

Unfortunately, I can't really think of a better, concrete solution right now either. It would probably be optimal if the cell did not have to be removed temporarily, but could be updated in place. Then the average and therefore the totalLength would not jump so much. Unfortunately, I don't yet have such a deep understanding of Flowless to be able to judge whether this is possible.

**Comment by Jugen** [comment]
Thanks for the feedback, will continue to look at it tomorrow.

There is an [experimental branch for cell reuse](https://github.com/FXMisc/RichTextFX/tree/virtual_flow_cell_reuse) in RichTextFX, if you want to take a look. (Even though it currently fails some tests, it does work but sometimes has an exception.)

**Comment by Elmari** [comment]
Hi Jugen,
Thank you for your continued support. I just tried around again and am now a bit confused: apparently your PR at Flowless is the solution after all, but with the following change (maybe?):

``` 
                EventStreams.changesOf( knownLengths ).filter( c -> c.getList().size() > 0 )
         ---       // skips spurious events resulting from cell replacement (delete then add again)
         ---       .successionEnds( Duration.ofMillis( 15 ) )
`

When I remove the highlighted lines (and only use your PausableSuccessionStream, line 140), the wobble no longer occurs for me at all. I haven't been able to figure out exactly why that is. Maybe I'm overlooking a test case and the problem still exists. But I still wanted to share this briefly here. Tomorrow I will deal with it again intensively.

**Comment by Jugen** [comment]
Hi Elias, this has been a particularly hard nut to crack but I'm hopeful that with the latest commit that we've mostly got it now.

As you suggested I experimented with RichTextFX cell reuse to see if that would help but it seems that Flowless itself is responsible for the spurious removals and additions, so unfortunately as you've also noticed that didn't help (and yeah it is a bit confusing).

Anyway, over the last two weeks I've become convinced that the solution is to somehow simultaneously update averageLengthEstimate, totalLengthEstimate, and lengthOffsetEstimate (which are interdependent) while at the same time dodging those false events from Flowless cell refreshes.  After much head scratching and experimentation, I believe the latest commit mostly achieves this.

Thanks so much for your continued efforts, input, and troubleshooting this with me. I really appreciate it and hope that your testing will mostly be successful this time round. Looking forward to the results ....

**Comment by Elmari** [comment]
That does indeed seem to fix the problem! Thank you very much for the hard work.
One problem that still remains is the usage in combination with a ScaledVirtualized, there the flickering still occurs (with any zoom factor, but appears that higher zoom factors make the flickering more likely to appear):
![Animation4](https://user-images.githubusercontent.com/1381848/198576848-e4b7600e-96e1-4989-8e11-b1825da90233.gif)

When logging the estimated height and the estimated scroll pos y it appears that the estimated height stays the same (which is good because that comes from the SizeTracker, if I understand it correctly and that was just fixed with the PR), while estScrollY has rapid changes similar to those which were fixed. 

Example log data:
```
Old scroll pos y: 5062.4, new: 4477.2
Old scroll pos y: 4477.2, new: 5062.4
Old scroll pos y: 5062.4, new: 4477.2
Old scroll pos y: 4477.2, new: 5062.4
``` 

Unfortunately I hadn't much time to look into it further. If you think that this problem is out of the scope of this ticket, I will be happy to create a new one.

Thanks again for your work!

**Comment by Jugen** [comment]
I think the _ScaledVirtualized_ issue is just a rounding problem which results in the values being slightly out causing the flickering as the values converge. Have submitted a commit to the PR to address. Please give it try and let me know if it helps, thanks.

**Comment by Elmari** [comment]
I've only tested it briefly, but with the latest commit the problem with the ScaledVirtualized seems to be fixed as well. I think then the bug is actually completely fixed. Thank you again for your great work.
By the way: I found the following old bugticket, which seems to describe the same problem. This could then probably also be closed: https://github.com/FXMisc/RichTextFX/issues/260

**Comment by Jugen** [comment]
Thanks a stack, and have linked the 260 issue aswell.
Will do a final review tomorrow then and probably merge.
