### ISSUE TITLE
Build failures on macOS when using RichTextFX 0.11.0

### ISSUE THREAD

**Issue by swpalmer** [FXMisc/RichTextFX#1154]
## Expected Behavior

updating to 0.11.0 should work with no other changes (if I'm already using Java 11 or above).

## Actual Behavior

Gradle build using the 'application' plugin fails with the following error:

```
* What went wrong:
Execution failed for task ':startScripts'.
> Error while evaluating property 'relativeClasspath' of task ':startScripts'.
   > Could not resolve all files for configuration ':runtimeClasspath'.
      > Could not find javafx-fxml-19-win.jar (org.openjfx:javafx-fxml:19).
        Searched in the following locations:
            file:/Users/scott/.m2/repository/org/openjfx/javafx-fxml/19/javafx-fxml-19-win.jar
      > Could not find javafx-controls-19-win.jar (org.openjfx:javafx-controls:19).
        Searched in the following locations:
            file:/Users/scott/.m2/repository/org/openjfx/javafx-controls/19/javafx-controls-19-win.jar
      > Could not find javafx-graphics-19-win.jar (org.openjfx:javafx-graphics:19).
        Searched in the following locations:
            file:/Users/scott/.m2/repository/org/openjfx/javafx-graphics/19/javafx-graphics-19-win.jar
      > Could not find javafx-base-19-win.jar (org.openjfx:javafx-base:19).
        Searched in the following locations:
            file:/Users/scott/.m2/repository/org/openjfx/javafx-base/19/javafx-base-19-win.jar
```

I am building and running on macOS and have specified JavaFX 19 with the gradle plugin for javafx.  Note the reference to "-win"

Looking at 
~/.gradle/caches/modules-2/files-2.1/org.fxmisc.richtext/richtextfx/0.11.0/99a3f3d838ce91c8ecc1d34a664c83718439c621/richtextfx-0.11.0.module

I see several "thirdPartyCompatibility" references that specific a "win" classifier.  I'm not sure if this is the issue, but it seems wrong.
```
  84   │           "thirdPartyCompatibility": {
  85   │             "artifactSelector": {
  86   │               "name": "javafx-graphics",
  87   │               "type": "jar",
  88   │               "extension": "jar",
  89   │               "classifier": "win"
  90   │             }
  91   │           }
```

## Environment info:

- RichTextFX Version: 0.11.0
- Operating System: macOS 12.6.2
- Java version: 17.0.4

**Comment by Jugen** [comment]
Here's a javafx-gradle-plugin issue that I think is related: [Remove classifier from JavaFX artifacts when publishing to Maven Central](https://github.com/openjfx/javafx-gradle-plugin/issues/26)

**Comment by swpalmer** [comment]
Well I fixed my issue of the artifacts not resolving... It's a Gradle issue where if it finds some version of an artifact at a particular repo, it won't look in other repos even if it doesn't find the actual version it is looking for in the first repo.  I had mavenLocal() listed before maventCentral() in my build.gradle file.  Because maven local had older versions of the artifact it prevented the missing artifact from being found at maven central.  There is still an issue, but it isn't stopping me anymore.

**Comment by Jugen** [comment]
Great, thanks for the feedback. When the next version of RichTextFX is released, I'll try and convince Gradle not to include the Javafx dependency stuff.
