### ISSUE TITLE
wrapTextProperty() is temporarily ignored when inserting characters on a long line

### ISSUE THREAD

**Issue by Col-E** [FXMisc/RichTextFX#1168]
## Expected Behavior

Given the following code:
```java
CodeArea area = new CodeArea();
area.setWrapText(false);
setCenter(area);
```
Inserting a long line such as `JsonReader json = new JsonReader(new InputStreamReader(Editor.class.getResourceAsStream("/syntax/java.json")));` should remain on a single line. Changing the window size, or inserting additional characters on the line should have the line still occupy one visual line.

## Actual Behavior

Upon inserting a character, the line wraps. Any further interaction resets to the expected wrapping behavior.
Deleting characters does not trigger the bug, only insertions.

https://user-images.githubusercontent.com/21371686/216116207-d84e5dca-4d33-48b8-9951-e68383902e0c.mp4

## Reproducible Demo

````java
public class Bug extends Application {

 public void start(Stage primaryStage) {
   CodeArea area = new CodeArea();
   area.setWrapText(false); // at runtime, just paste your long text in since its the interaction of insertion by the user that triggers this
   primaryStage.setScene(new Scene(new BorderPane(area)));

   primaryStage.show();
 }

}
````

## Environment info:

- RichTextFX Version: `0.11.0`
- Operating System: Windows 10
- Java version: 17

**Comment by Col-E** [comment]
Seems to happen for anything that pushes content to the right. My line graphic padding is a bit bugged atm and triggered the bug as well.

https://user-images.githubusercontent.com/21371686/216506194-b9d1ca69-d48e-4e5b-85f7-48d78b4ccd71.mp4

**Comment by Jugen** [comment]
Thanks for the great bug report and videos. Have submitted PR 1169 to fix.

**Comment by Col-E** [comment]
Confirmed the fix, thanks 👍
