### ISSUE TITLE
Question regarding nodeFactory - custom Node implementation instead of TextExt

### ISSUE THREAD

**Issue by cyfung1031** [FXMisc/RichTextFX#1178]
In `GenericStyledArea`, there is `nodeFactory` in its constructor.
For `StyledTextArea`, it creates `TextExt` which is extended from `Text`.

I tried many ways to make the fixed width for it, like `setWrappingWidth`, `maxWidth` + `minWidth` + `prefWidth`, still do not work.

I tried to modify the Text constructor's parameter to a padded text, the text width can be wider but looks like it breaks the layout of the text area. Some texts are visible but not selectable.

So I tried to make a container, like TextFlow, Pane, VBox, HBox, ... , the width can be fixed but the text are not selectable.

I just want to make a fixed width Text.
Might I ask how...? Thanks.

**Comment by Jugen** [comment]
Can you try and give a bit more detail as it's not clear if you want to have a fixed width font (i.e. Text), or if you want the text area to be fixed width (i.e. no wrapping), or do you mean that a paragraph may only be X characters wide and no more ?

**Comment by cyfung1031** [comment]
My texts are like
```
te8e77\tMy Word - Apple
x351\tMy Word - Orange
y991ww\tMy Word - Sun
```

As the text before `\t` is irrgular length, it will be ugly.
I want to make them all as the same width.

e.g.
```
te8e77              \tMy Word - Apple
x351                  \tMy Word - Orange
y991ww            \tMy Word - Sun
```

**Comment by cyfung1031** [comment]
It would be great if the TextFlow can be used as the Node produced by nodeFactory.

Right now there is no any way to support color emoji in RichTextFX.
Noto Fonts could not work with javafx.
Only OpenSansEmoji can works but just mono color and the emoji set is very old. OpenSansEmoji will not update anymore I guess.



Therefore, I would like to have the answers regarding two things:

1. If I am creating the custom node instead of the default TextExt, what should my Node required to provide?
 - The rendered text might not be the same length as the text provided. (e.g. I want to pad space or pad zero to the original text (the extracted text according setStyle & StyleSpan) )
 - How to make my text in the custom node being selectable? Say I am using TextFlow or VBox to contain the Text node.


See:
https://stackoverflow.com/questions/36854539/how-do-i-display-emoji-in-javafx-on-os-x

**Comment by Jugen** [comment]
Sorry for the delayed response.

I think a possibly better way of solving your problem may be to have a look at the [hyperlink demo](https://github.com/FXMisc/RichTextFX/tree/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/hyperlink).

I suggest modifying it so that instead of a hyperlink it returns a fix width Label that will then give the visual affect you are looking for, where you put the first part into the Label and the rest as normal text.

**Comment by cyfung1031** [comment]
Thanks for your response,  although i did not tried your demo.

I have switched to another way (use webview and javascript code mirror with css to solve the issue already)

Therefore this comment is closed now.
