### ISSUE TITLE
How to avoid setStyleSpans being an action for undo?

### ISSUE THREAD

**Issue by cyfung1031** [FXMisc/RichTextFX#1179]
I am using `area.multiPlainChanges().subscribe(change -> {... })`

I found out that setStyleSpans will make a new state for undo.

after i typed something or pasted something
the ctrl-z will make it undo the style first (remove the style) then undo the typing (delete the char)

how to avoid this bug?

**Comment by Jugen** [comment]
There are three ways to do this:
1. Only have plain text undo, so styling undo gets ignored:
```java
area.setUndoManager( UndoManager.plainTextUndoManager() );
```
2. Suspend the undo manager for certain styling:
```java
SuspendableYes suspendUndo = new SuspendableYes();
area.setUndoManager( UndoUtils.richTextSuspendableUndoManager( area, suspendUndo ) );
suspendUndo.suspendWhile( () -> area.setStyle( 5, 9, "-fx-font-weight: bold;" ) );
```
3. Combine changes and styling into one event:
```java
area.createMultiChange(2)
   .... // change text
   .... // change style
   .commit();
```

**Comment by cyfung1031** [comment]
Thanks for your response. The topic can be closed now. 
I hope that these methods shall be documented for future readers to read in manual or example demo.

**Comment by avavrin** [comment]
Hi @Jugen Thank you for your answer. 
About your point 3. Is there an implementation of `MultiChangeBuilder` that deals with style changes ?
Thank you

> 3. Combine changes and styling into one event:
> 
> ```java
> area.createMultiChange(2)
>    .... // change text
>    .... // change style
>    .commit();
> ```

**Comment by Jugen** [comment]
> About your point 3. Is there an implementation of MultiChangeBuilder that deals with style changes ?

Unfortunately not. You'll have to do it via replacement with a **StyledDocument** using the  _MultiChangeBuilder_ 
`replace( int start, int end, StyledDocument replacement )` method.

**Comment by avavrin** [comment]
Thank you !

I have a specific case, where I need to add Markdown delimiters in the text and then use a Markdown parser to style some parts of this text, in the same `MultiChangeBuilder.commit`  to be able to undo both text and style as you suggest.

Maybe these methods below can help other users, but this in not perfect since you need to make text modifications first, and then use `getCurrentDocument` to compute the current text (without commit) to apply styles absolutely.

```java
    private StyledDocument<PS, SEG, S> getCurrentDocument() {
        final GenericEditableStyledDocument<PS, SEG, S> document = new GenericEditableStyledDocument<>(ReadOnlyStyledDocument.from(area.getDocument()));
        document.replaceMulti(Collections.unmodifiableList(list));
        return document;
    }

    public void updateStyle(int start, int end,
                            UnaryOperator<S> mapper) {
        final StyledDocument<PS, SEG, S> currentDocument = getCurrentDocument();
        final ReadOnlyStyledDocumentBuilder<PS, SEG, S> builder = new ReadOnlyStyledDocumentBuilder<>(area.getSegOps(), area.getInitialParagraphStyle());
        currentDocument.subSequence(start, end).getParagraphs().forEach(par -> {
            final List<StyledSegment<SEG, S>> segments = new ArrayList<>();
            par.getStyledSegments().forEach(seg -> {
                final S style = seg.getStyle();
                final S newStyle = mapper.apply(style);
                segments.add(new StyledSegment<>(seg.getSegment(), newStyle));
            });
            builder.addParagraph(segments, par.getParagraphStyle());
        });
        replaceAbsolutely(start, end, builder.build());
    }
```
