### ISSUE TITLE
\r and \r\n

### ISSUE THREAD

**Issue by Xiaobaishushu25** [FXMisc/RichTextFX#1181]
Hello, thank you for your project. What I'm wondering is why  \r  breaks line occur in codeArea. Shouldn't it be returning to the beginning of the line?

**Comment by Jugen** [comment]
I think it's because of this:
> It used to be that, on Macintosh computers, the “\r” was used to indicate “end of line” in files. This is in contrast to Unix (of which Linux is one variant) computers which use just “\n” and Microsoft Windows which uses both, “\r\n”.
