### ISSUE TITLE
Question: how can I precisely detect the index of the character being clicked? 

### ISSUE THREAD

**Issue by jpmonettas** [FXMisc/RichTextFX#1191]
Hi! I need to detect clicks on specific characters on a CodeArea text.

What I'm currently trying is attaching a onMouseClicked event on the CodeArea and then grabbing the caret position with codeArea.getCaretPosition(). The problem with this approach is that is not precise for detecting which character you are trying to click since the caret is between characters.

Any ideas on how to accomplish this?

Thanks!

**Comment by Jugen** [comment]
Have a look at [Custom tooltips](https://github.com/FXMisc/RichTextFX/tree/master/richtextfx-demos#custom-tooltips) and see if that helps.

**Comment by jpmonettas** [comment]
Tried it by setting a small mouseOverTextDelay, like 50 ms, and then keeping a var with the current character with mouse enter/exit event but couldn't make it work reliable since clicking on the CodeArea generates a MouseOverTextEvent.MOUSE_OVER_TEXT_END event for some reason, even when you are still over the character.

**Comment by Jugen** [comment]
Ok, let's try the following and see if does what you want:
```java
area.addEventFilter( MouseEvent.MOUSE_CLICKED, ME ->
{
    var charHit = ((CodeArea) ME.getSource()).hit( ME.getX(), ME.getY() );
    charHit.getCharacterIndex().ifPresent( i -> System.out.println( area.getText( i, i+1 ) ) );
});
```

**Comment by jpmonettas** [comment]
Great! this does what I need! Thanks a lot @Jugen !
