### ISSUE TITLE
SetPlaceholder is invalid and does not display placeholders

### ISSUE THREAD

**Issue by ljy1058318852** [FXMisc/RichTextFX#1192]
`
<CodeArea fx:id="result3" prefWidth="300" preHeight="300"/>
`

```
@FXML
private CodeArea result3;

@FXML
void initialize() throws IOException {
    TextFlow placeholder = new TextFlow (new Text ("myText"));
    result3.setPlaceholder(placeholder, Pos.CENTER);
}
```

Do not display placeholder characters，Why is this? Did I make a spelling mistake？

**Comment by Jugen** [comment]
It may be that the CodeArea has focus, you will see the cursor flash, then the placeholder will not show.
The placeholder only shows if there is no text and it does not have focus.

**Comment by ljy1058318852** [comment]
> It may be that the CodeArea has focus, you will see the cursor flash, then the placeholder will not show. The placeholder only shows if there is no text and it does not have focus.

Thank you very much for your reply, but in fact, I have created multiple CodeAreas, and I have confirmed that none of them have obtained focus or entered a cursor.

**Comment by Jugen** [comment]
Could you then provide a small test program that demonstrates the problem, as it works for me ?

**Comment by ljy1058318852** [comment]
This is fxml:
`<?xml version="1.0" encoding="UTF-8"?>

<?import javafx.scene.layout.StackPane?>
<?import org.fxmisc.richtext.CodeArea?>

<?import javafx.scene.layout.HBox?>
<StackPane fx:id="sPane" maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" xmlns="http://javafx.com/javafx/20.0.1" xmlns:fx="http://javafx.com/fxml/1" fx:controller="com.potato.potatotool.controller.PaneWebshellDecode">
   <HBox spacing="10">
      <CodeArea fx:id="result1" prefWidth="300" prefHeight="300" style="-fx-background-color: red"/>
      <CodeArea fx:id="result2" prefWidth="300" prefHeight="300"/>
      <CodeArea fx:id="result3" prefWidth="300" prefHeight="300" style="-fx-background-color: blue"/>
   </HBox>
</StackPane>
`
This is Controller:
`package com.potato.potatotool.controller;

import javafx.fxml.FXML;
import javafx.geometry.Pos;
import javafx.scene.layout.StackPane;
import javafx.scene.text.Text;
import javafx.scene.text.TextFlow;
import org.fxmisc.richtext.CodeArea;

import java.io.IOException;

public class PaneWebshellDecode {
    @FXML
    private CodeArea result1;
    @FXML
    private CodeArea result2;
    @FXML
    private CodeArea result3;

    @FXML
    void initialize() throws IOException {
        TextFlow placeholder = new TextFlow (new Text("myText"));
        result1.setPlaceholder(placeholder, Pos.CENTER);
        result2.setPlaceholder(placeholder, Pos.CENTER);
        result3.setPlaceholder(placeholder, Pos.CENTER);
    }

}
`
richtextfx v0.10.8   java11.0.12

I'm very sorry, it may be due to network reasons that we are unable to upload the rendering. In fact, three CodeAreas did not appear as placeholder strings.

**Comment by Jugen** [comment]
Ok, have found a bug and will submit a fix .....

By the way:
1. The same placeholder cannot be used on multiple areas at the same time, as a Node may only occur once in the scene graph.
2. And `Text` does not have to be wrapped in a `TextFlow`, just do: `area.setPlaceholder( new Text("myText") );`

**Comment by ljy1058318852** [comment]
Thank you for the quick fix!  Appreciate it.  👍
