### ISSUE TITLE
Is there a built-in and universal code keyword highlighted?

### ISSUE THREAD

**Issue by ljy1058318852** [FXMisc/RichTextFX#1196]
Is there a built-in code keyword highlighting? Of course, I'm not sure what programming language the user is using for input, it could be Java Python PHP ASP aspx, etc

Of course, this would be perfect if possible:
`CodeArea. setLanguage ("Java");
codeArea. setLanguage ("ALL");`

**Comment by Jugen** [comment]
No, but you can have a look at the [keyword highlighting demo](https://github.com/FXMisc/RichTextFX/tree/master/richtextfx-demos#automatic-highlighting-of-java-keywords) to maybe get you started.
