### ISSUE TITLE
How to refresh/redraw the area?

### ISSUE THREAD

**Issue by bruno-kus** [FXMisc/RichTextFX#1202]
I hope there is a simple method I'm just missing.
Here's how I do it now:
`public void refresh() {
        insertText(getLength(), " ");
        replaceText(getLength() - 1, getLength(), "");
    }`

**Comment by Jugen** [comment]
Under what conditions are you having to force a refresh like this ?
Or putting it another way what change are you making that isn't being updated/refreshed automatically, so that you have to do this ?

**Comment by bruno-kus** [comment]
Each segment has a tag and I wanted to highlight all those belonging to the tag currently selected. I was manipulating style through TextStyle and didn't realize I can bind TextExt directly — which now seems obvious.
```
t.setBorderStrokeColor(Color.BLACK);
t.borderStrokeWidthProperty().bind(Bindings.createIntegerBinding(() -> area.selectedTag().equals(seg.getRight().tag) ? 2 : 0));
```
 Issue fixed.
