### ISSUE TITLE
Question: How to keep the selection when append text?

### ISSUE THREAD

**Issue by zkycaesar** [FXMisc/RichTextFX#1204]
I noticed that when I call `appendText`, the selection will be cleard. How do I keep the selection?

**Comment by Jugen** [comment]
So the problem is that `appendText` and related API all cause the caret to move which then clears the selection.
The simplest way around this is to not use the convenience API and rather do something like:
```java
var len = area.getLength();
var addDoc = ReadOnlyStyledDocument.fromString
(
    theTextToAppend,
    area.getParagraphStyleForInsertionAt( len ),
    area.getTextStyleForInsertionAt( len ),
    area.getSegOps()
);

area.getContent().replace( len, len, addDoc );
```

**Comment by zkycaesar** [comment]
Cool! Thanks.
