### ISSUE TITLE
How to set the size of tab in CodeArea?

### ISSUE THREAD

**Issue by PavelTurk** [FXMisc/RichTextFX#1209]
According to https://bugs.openjdk.org/browse/JDK-8233810 JavaFX 14 supports `-fx-tab-size` property. I use javafx-19-ea+3. As I understand from https://github.com/FXMisc/RichTextFX/issues/86#issuecomment-58573872  `CodeArea` internally uses `TextFlow`. So,  `-fx-tab-size` must be supported. This is my code:

       Java
        this.textArea = new CodeArea();
        this.textArea.getStyleClass().add("xml-text-area");
        final var highlighter = new XmlHighlighter();
        textArea.textProperty().addListener((obs, oldText, newText) -> {
            textArea.setStyleSpans(0, highlighter.computeHighlighting(newText));
        });
        textArea.setEditable(true);
        textArea.setParagraphGraphicFactory(LineNumberFactory.get(textArea));
        textArea.setPadding(new Insets(0, 0, 0, 0));
        textArea.getUndoManager().atMarkedPositionProperty().addListener((ov, t, t1) -> {
            viewModel.doOnTextAreaModified(!t1);
        });

      CSS
      .xml-text-area {
            -fx-tab-size: 10;
      }

However, when I load files with tabs I don't see that my code works. Could anyone say how to fix it?

PS What I want is to set tab size in view, so I could to control the tab size when I render files with tabs.

**Comment by Jugen** [comment]
Try the following CSS instead:
```css
.xml-text-area .paragraph-text {
    -fx-tab-size: 10;
}
```
