### ISSUE TITLE
Question: is it possible to disable scrolling to bottom on appending text?

### ISSUE THREAD

**Issue by PavelTurk** [FXMisc/RichTextFX#1221]
When I open file with with my text area I use the following code:
    
            CodeArea textArea = ...
            textArea.clear();
            textArea.appendText(t);
            textArea.getUndoManager().forgetHistory();
            textArea.getUndoManager().mark();

However, after that text area is scrolled to bottom. If I add to my code:

        textArea.moveTo(0);
        textArea.requestFollowCaret();

Then textarea is scrolled to top, but there is a flickering of vertical bar and it is not good. Could anyone say how to disable scrolling to bottom on text appending? Or maybe there are other solutions?

**Comment by Jugen** [comment]
You can try the following:
```java
    textArea.clear();
    textArea.appendText( "\n" );
    textArea.selectRange( 0, 0 );

    var changes = textArea.createMultiChange(2);
    changes.insertTextAbsolutely( 0, 1, sampleCode );
    changes.deleteTextAbsolutely( 0, 1 );
    changes.commit();
```
