### ISSUE TITLE
Question: How to make wave underline?

### ISSUE THREAD

**Issue by PavelTurk** [FXMisc/RichTextFX#1225]
Could anyone say how to make wave underline? I mean something like this 

![Screenshot from 2024-05-14 18-05-05](https://github.com/FXMisc/RichTextFX/assets/10261361/b5f6b6fc-88b5-437a-93ec-ec57ad106bf8)

**Comment by Jugen** [comment]
See the following CSS in the [Wiki](https://github.com/FXMisc/RichTextFX/wiki/RichTextFX-CSS-Reference-Guide#the-additional-css-properties-for-textext)
```css
-rtfx-underline-color: red;
-rtfx-underline-wave-radius: 2;
-rtfx-underline-width: 1;
```
