### ISSUE TITLE
Question: What is the strategy to implement Highlight All for found matches for modifiable text?

### ISSUE THREAD

**Issue by PavelTurk** [FXMisc/RichTextFX#1227]
I have a `CodeArea` with text that can be modified by user. Now, I want to implement `Highlight All` for all found matches (for search). 

As I understand for all found matches I do `codeArea. setStyle​(from, to, style)`. But, if the user updates some match so that it shouldn't be highlighted anymore then how should I control what text was modified to remove highlighting? What if user pastes some text inside found match or deletes large block of text? Could anyone say how such things are done with RichTextFX?

**Comment by Jugen** [comment]
Yes that sounds about right .....

**Comment by Jugen** [comment]
You can use either `plainTextChanges` or `richChanges` which includes style changes.
