### ISSUE TITLE
Question: when to use StyleSpans?

### ISSUE THREAD

**Issue by PavelTurk** [FXMisc/RichTextFX#1229]
I have a `CodeArea`. For piece of a text I can set style using `StyleSpans`or without them:

```
textArea.setStyleSpans(int from,  StyleSpans<? extends S> styleSpans)//with
textArea.setStyleClass(int from, int to, String styleClass)//without
```

Could anyone explain when I should use `StyleSpans`?

**Comment by Jugen** [comment]
There are two cases for when to use StyleSpans:
1. `setStyleClass` will erase & replace the current styling of the specified range, while `setStyleSpans` will add the provided styling to any existing styling.
2. Every `setStyleClass` and `setStyleSpans` invocation is a single change event to the text which triggers a redraw for each change. If however you want to bundle multiple style changes into one undo event or optimize the amount of redrawing then you can bundle a group of StyleSpans together using `StyleSpansBuilder` and submit them in one go with `setStyleSpans`. **Note** that a series of StyleSpans are consecutive, that is the next StyleSpan position starts where the last one ended. So if you need to change separate sections of text in one go, you can insert an empty StyleSpan with the appropriate length to "move the change cursor" to the next change position.

**Comment by Jugen** [comment]
So you would have to get the style spans for the section of text that you are interested in, make changes to the style spans as appropriate, and then apply the changed style spans back. Something like:
```java
    private void changeStyle( IndexRange range )
    {
        if ( range.getLength() > 0 )
        {
            var newStyles = new StyleSpansBuilder<String>();

            for ( var span : area.getStyleSpans( range ) )
            {
                var style = span.getStyle();

                // Add or Remove styles as appropriate 

                newStyles.add( style, span.getLength() );
            }

            area.setStyleSpans( range.getStart(), newStyles.create() );
        }
    }
```
You can also try going from style span to style, something like:
```java
private void changeParagraphStyle( int p )
{
    var para = area.getParagraphs.get(p);
    var spanStart = 0;
    
    for ( var span : para.getStyleSpans() )
    {
        var style = span.getStyle();

	// Add or Remove styles as appropriate

        area.setStyle( p, spanStart, spanStart+span.getLength(), style  );

        spanStart += span.getLength();
    }
}
```

**Comment by Jugen** [comment]
Could something in `StyleSpans` ([ApiDoc](http://fxmisc.github.io/richtext/javadoc/0.11.1/org/fxmisc/richtext/model/StyleSpans.html)) ([Code](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/model/StyleSpans.java)) maybe help you ?

**Comment by Jugen** [comment]
Maybe you should use a custom style class instead, where you can put the extra information etc. Try the the following framework to get started:
```java
    public class CustomStyleArea extends StyledTextArea<String,MyStyle>
    {
        public CustomStyleArea()
        {
            super( "", CustomStyleArea::styleParagraph, MyStyle.NONE, CustomStyleArea::styleText );
            // Style codecs are used for (de)serialization during copy, paste, save, and load
            setStyleCodecs( Codec.STRING_CODEC, Codec.styledTextCodec(new MyStyleCodec()) );
        }

        private static void styleParagraph( TextFlow paragraph, String style )
        {
            // paragraph.getStyleClass().addAll( styles );
            paragraph.setStyle( style );
        }

        private static void styleText( TextExt text, MyStyle style )
        {
            // text.getStyleClass().addAll( style.getCssClasses() );
            // or
            // text.setStyle( style.getCss() );
        }
    }


    class MyStyle
    {
        public static final MyStyle NONE = new MyStyle();

        // TODO Styling info plus any extra data, flags, and methods eg:
        // public List<String> getCssClasses()
        // public String getCss()
    }


    /**
     * Codec methods are used for (de)serialization during copy, paste, saving, and load.
     * Note: you can leave this till last, once you've finished MyStyle.
     */
    class MyStyleCodec implements Codec<MyStyle>
    {
        @Override public String getName()
        {
            return "richtextfx/mystyle";
        }

        @Override public void encode( DataOutputStream os, MyStyle t ) throws IOException
        {
            // TODO
        }

        @Override public MyStyle decode( DataInputStream is ) throws IOException
        {
            // TODO
            return null;
        }
    }
```
