### ISSUE TITLE
Question: how to get real size of one span at position X?

### ISSUE THREAD

**Issue by PavelTurk** [FXMisc/RichTextFX#1231]
When I do 

```
for (var span : codeArea.getStyleSpans(0, codeArea.getText().length())){
    System.out.println(span);
}         
```
I get:

```
StyleSpan[length=6, style=[]]
StyleSpan[length=5, style=[MyStyle{...}]]
StyleSpan[length=434, style=[]]
```
So, I there are three spans. The length of the first is 6. Now I want to get the length of the span at position X. But when I do:

```
var spans = codeArea.getStyleSpans(3, 4);
System.out.println("L:" + spans.iterator().next().getLength());
```
I get:
```
L:1
```
Can I get ONE span at position X and its full length?

**Comment by Jugen** [comment]
Would `codeArea.getStyleRangeAtPosition( pos );` maybe help ?

**Comment by Jugen** [comment]
Yeah, I'm surprised by that as well !?  Looking at the code reveals that the returned IndexRange is relative to the paragraph as you guessed.
I'd say this is a bug but I'm not going to change it since it's been like that for how long and may break somebody's code ?  I will however add a note to the JavaDoc for those methods.

I'd suggest using `getStyleRangeAtPosition( par, col )` instead where it makes more sense that the returned IndexRange is relative to the paragraph.

For style spans over multiple paragraphs you could try the following based on what is done in _Paragraph_:
```java
// Must use this method of getStyleSpans or the one with parameter IndexRange and not any other !
var spans = codeArea.getStyleSpans( 0, codeArea.getLength() );
var offset = spans.offsetToPosition( targetPos, Bias.Backward );
var styleStart = offset.getMinor();
var styleEnd = styleStart + spans.getStyleSpan( offset.getMajor() ).getLength();
```

**Comment by Jugen** [comment]
Try updating `getRealStyleRangeAt` to the following:
```java
    public IndexRange getRealStyleRangeAt( int position )
    {
        var length = 0;
        for ( var ss : codeArea.getStyleSpans( 0, codeArea.getLength() ) )
        {
            if ( (length += ss.getLength()) >= position )
            {
                var start = length - ss.getLength();
                return new IndexRange( start, length );
            }
        }

        return new IndexRange( 0,0 );
    }
```

**Comment by Jugen** [comment]
Yeah, I don't like the iteration either but I don't know of another way as I haven't been able to find it in the model.
The `StyleSpans` interface extends `TwoDimensional` which only seems to be able to give us relative ranges and not absolute ones.
The API allows us to get a `StyleSpan` at a particular position and to tell us where in that `StyleSpan` the position is but it has no knowledge of it's own position and `StyleSpans` doesn't seem to know the absolute position either.

I can try and add a start field to `StyleSpan` which `StyleSpansBuilder` can update when creating `StyleSpans`. Then integrate `getRealStyleRangeAt` into `StyleSpans` which can then be reduced down to the following I think:
```java
var offset = spans.offsetToPosition( position, Bias.Backward );
var span = spans.getStyleSpan( offset.getMajor() );
var spanStart = span.getStart();
return new IndexRange( spanStart, span.getLength() );
```

**Comment by Jugen** [comment]
Do the following three steps ....
1. Declare private field:
```java
private SuspendableYes suspendUndo = new SuspendableYes();
```
2. Set undo manager when creating area:
```java
textArea.setUndoManager( UndoUtils.richTextSuspendableUndoManager( textArea, suspendUndo ) );
```
3. Use suspendUndo when required:
```java
suspendUndo.suspendWhile( () -> textArea.setStyleSpans( position, ssb.create() ) );
```
