### ISSUE TITLE
How to remove all styles from undo text?

### ISSUE THREAD

**Issue by PavelTurk** [FXMisc/RichTextFX#1234]
Situation. I have a text with styles. When user modifies some pieces of text I remove styles from that pieces. The problem is that when user does undo (`textArea.getUndoManager().undo();`) then old text is returned with old styles. For example `junit` is highlighted:

![Peek 2024-05-30 10-59](https://github.com/FXMisc/RichTextFX/assets/10261361/905420a7-12cf-42b7-8237-f551180fe05f)

**Comment by Jugen** [comment]
Are you sure it is undo that is restoring the styles ?
If so then was the undo manager suspended when the styles were applied ?

If you don't want any styling changes to be included in the undo / redo operations at all and are only interested in plain text changes then the easiest is to apply a plain text undo manager.
```java
textArea.setUndoManager( UndoUtils.plainTextUndoManager( textArea ) );
```
Alternatively if you're using the CustomeStyleArea template/framework I provided then change the following line in the constructor:
```java
super( "", CustomStyleArea::styleParagraph, MyStyle.NONE, CustomStyleArea::styleText, false );  // added false for plaintext undo
```

**Comment by Jugen** [comment]
Hmmm, I don't think I was clear enough with the change to the super constructor invocation. When changing it you MUST also remove `setUndoManager` from your code as well as the suspendable code as they are not needed anymore. Then the undo manager will only keep track of plain text changes and NO styling changes.
