### ISSUE TITLE
Question: is textArea.getLength() equal to the number of Unicode code points

### ISSUE THREAD

**Issue by PavelTurk** [FXMisc/RichTextFX#1236]
Could anyone say  if `textArea.getLength()` is always equal to `textArea.getText().codePoints().count()`?

**Comment by Jugen** [comment]
No they are not always equal.

**Comment by Jugen** [comment]
No, it's about those characters where more than one Unicode code unit is required to represent the character.  String.length() returns the number of Unicode code units while codePoints() combines these code units into a single integer value and returns that. So String.length can be larger than the count of integers returned by codePoints.

**Comment by Jugen** [comment]
I agree, I've updated the JavaDoc for getLength()
Thanks.
