### ISSUE TITLE
Behavior of setParagraphStyle  bas been changed in 0.11 in comparison with 0.10.9 version 

### ISSUE THREAD

**Issue by iazarny** [FXMisc/RichTextFX#1241]
## Expected behavior or in 0.10.X version 

The paragraph style applies to the entire width of the code area. In this way, you can highlight the entire line

## Actual behavior or in 0.11.X version 

Paragraph style applied till end of the line, the length of which may be less code area width

## Css example
.diff-modified {
    -fx-background-color: #d7f8f6;
    -fx-stroke-width: 0.5;
    -fx-stroke: #e5e5fa;
    -fx-fill: #d7f8f6;
}

## Environment info:

- RichTextFX Version: 0.10.X, 0.11.X
- Operating System: Win, Mac, Lin
- Java version: 17 - 21
<img width="1291" alt="actual" src="https://github.com/user-attachments/assets/855f3fcd-1c09-43b0-95f0-9c2946cf550c">
<img width="1288" alt="expected" src="https://github.com/user-attachments/assets/6fda6592-d8e9-4a2c-9d83-a240dd0d0288">

**Comment by Jugen** [comment]
Is this already broken in 0.11.0 ? And please provide a short program that demonstrates this bug. Thanks.
