### ISSUE TITLE
Question: How to show whole text when text area is added to scene

### ISSUE THREAD

**Issue by PavelTurk** [FXMisc/RichTextFX#1243]
Let's assume there is an unknown text with some styles. 

Now, I need 

1. to create text area (InlineCssTextArea) with fixed width (for example, 500 pixels)
2. to add text to it with styles
3. to find whole document height
4. to make text area height equal to document height
5. to add text area to scene to show whole document without scrollbars.

As it is seen the problem is that I need whole document height when I only add text area to scene. I tried this code:

```
var messageArea = new InlineCssTextArea();
var scrollPane = new VirtualizedScrollPane(messageArea);
messageArea.totalHeightEstimateProperty().addListener((ov, oldV, newV) -> scrollPane.setMinHeight((double) newV));

```
This code works, but the problem is that when messageArea becomes visible it has one height and later its height is changed and user sees `flickering`. I tried to add
```
messageArea.setAutoHeight(true);
messageArea.applyCss();
messageArea.requestLayout();
```
But it didn't help. Could anyone say how to do it if it is possible?

**Comment by Jugen** [comment]
Not sure if this will work but let's start with just this:
```
var messageArea = new InlineCssTextArea();
messageArea.setPrefWidth(500);
messageArea.setMinWidth(500);
messageArea.setMaxWidth(500);
messageArea.setAutoHeight(true);
// add text to it with styles
```
So no scrollpane and no height property listener.
If this doesn't work as you would like then we'll build on it.

**Comment by Jugen** [comment]
With your first code provided above I see what you mean in video but can't replicate on my system ?
With the 2nd code I get the same "result" as you. It seems that the TextArea height requires another pulse to calculate correctly.
If you change `pulsePassed` to an int and increment it, printing to console when it reaches 1 or 2 then it'll be correct.
This maybe explains the flicker ?

**Comment by Jugen** [comment]
It seems that the delay only happens the first time the TextArea is rendered. 
This is because for the height to be calculated the width needs to known, so if the width is zero then a layout request is issued first to determine the width and this then results in the height only being calculated on the 2nd pass.

**Comment by Jugen** [comment]
Hmm, the TextArea requires its actual width. Those methods just specify the width limits and preference, not it's final rendered width which will depend on other things as well like the parent containers it is in.

You can try the following hack to prepare the messageArea for dialogs and popups:
```java
// Dummy scene to trigger initial layout to set width to 500
new Scene( messageArea, 500, 50 ).snapshot( null ); 
messageArea.appendText( text ); // Must be after
// Add messageArea to the Dialog/Popup container
```

**Comment by Jugen** [comment]
Have submitted a PR that calculates the height using the preferred width when appropriate as suggested.
Also updated latest maven snapshot including this PR.
Please assess and provide feedback, thanks.
