### ISSUE TITLE
Is it possible to set style in InlineCssTextArea from some point and until it is overridden?

### ISSUE THREAD

**Issue by PavelTurk** [FXMisc/RichTextFX#1247]
This is my test code:

```
public class RichTextFxTest extends Application {

    private final InlineCssTextArea textArea = new InlineCssTextArea();

    @Override
    public void start(Stage stage) throws Exception {
        var root = new VBox(textArea);
        textArea.append("My first text. ", "-fx-fill: green;-fx-font-weight:bold");
        textArea.append("My second text. ", "-fx-fill: red;");
        var scene = new Scene(root, 300, 200);
        stage.setScene(scene);
        stage.show();
    }
}
```
And this is the result:

![Screenshot from 2024-10-31 15-48-42](https://github.com/user-attachments/assets/1a289746-14f4-4232-8667-12c9df7459ba)

I append the first text with bold font weight and I want this style was set to all texts until I set `-fx-font-weight: normal`. However, as you see in the picture the second text is not bold (although I didn't do `-fx-font-weight: normal`).

Could anyone say how to do it, if it is possible?

**Comment by Jugen** [comment]
I don't think it can be done without coding it.
