### ISSUE TITLE
Double underline

### ISSUE THREAD

**Issue by PavelTurk** [FXMisc/RichTextFX#1248]
It is possible to create a single underline using the following style: `-rtfx-underline-color: black; -rtfx-underline-width: 1px;`. But I need a double underline, what in web can be done using `text-decoration-line: underline; text-decoration-style: double;`. Could anyone say how to do it?

**Comment by Jugen** [comment]
It's not currently possible.

**Comment by Jugen** [comment]
I've had a quick look and I can try and get it done next week.
We'll postpone the next release for this then.

**Comment by Jugen** [comment]
Specifying _-rtfx-underline-double-gap_: **0**; results in a double underline with zero gap.
Depending on how you see it this is probably a bug. I'll submit a fix for the next release.

**Comment by Jugen** [comment]
Just to be clear, if you don't specify _-rtfx-underline-double-gap_ at all it renders the underline as expected.

**Comment by Jugen** [comment]
Yes, I think so.
