### ISSUE TITLE
Copy keybind (Control + C) does not update clipboard on alternative keyboard layouts

### ISSUE THREAD

**Issue by Col-E** [FXMisc/RichTextFX#1253]
On a `ENG` keyboard layout `Control C` copies text in a `CodeArea` as one would expect.

On other keyboard layouts such as `RUS` the clipboard contents are never updated.

https://github.com/user-attachments/assets/76ef4ae5-043e-4bd1-9ade-293094d77836

**Comment by Col-E** [comment]
It seems that [GenericStyledAreaBehavior's copy key mapping](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledAreaBehavior.java#L172) is never invoked because the keycode you type when using an alternative keyboard layout is not `C`.

**Comment by xxDark** [comment]
I investigated this further, and the comment [here](https://github.com/FXMisc/RichTextFX/blob/d4dc5fef7fa26795aedaa074ab96697d9f44d822/richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledAreaBehavior.java#L57) either is not correct, or this does not apply to Russian keyboard layout.
`KeyCharacterCombination` invokes `getKeyCodeForChar` from JavaFX Toolkit which returns 0 for any Russian character.
I locally swapped out `KeyCharacterCombination` to `KeyCodeCombination` and everything seem to work again.
```java
        KeyCombination SHORTCUT_A = new KeyCodeCombination( A, SHORTCUT_DOWN );
        KeyCombination SHORTCUT_C = new KeyCodeCombination( C, SHORTCUT_DOWN );
        KeyCombination SHORTCUT_V = new KeyCodeCombination( V, SHORTCUT_DOWN );
        KeyCombination SHORTCUT_X = new KeyCodeCombination( X, SHORTCUT_DOWN );
        KeyCombination SHORTCUT_Y = new KeyCodeCombination( Y, SHORTCUT_DOWN );
        KeyCombination SHORTCUT_Z = new KeyCodeCombination( Z, SHORTCUT_DOWN );
        KeyCombination SHORTCUT_SHIFT_Z = new KeyCodeCombination( Z, SHORTCUT_DOWN, SHIFT_DOWN );
```

**Comment by xxDark** [comment]
This seems like a leftover fix back from 2018 which was supposed to fix [this](https://bugs.openjdk.org/browse/JDK-8123632) bug (?), but now it causes a bug instead

**Comment by Jugen** [comment]
Thanks @Col-E for reporting, and @xxDark for investigating.

I see that the reason for using `KeyCharacterCombination` was in order to support Dvorak keyboards.

Do either of you know (or can test) if changing to using `KeyCodeCombination` will break Dvorak support or not ?

**Comment by Jugen** [comment]
I've updated the RichTextFX maven 1.0.0-SNAPSHOT for testing.

**Comment by Jugen** [comment]
I've subsequently had a look at the JavaDoc for `KeyCodeCombination` versus `KeyCharacterCombination` and am of the opinion that it'll not break it.

Will wait a few days for any feedback and then submit a PR for the next release in about two weeks or so.
