### ISSUE TITLE
Is it possible to make text unmodifiable in a specific range?

### ISSUE THREAD

**Issue by PavelTurk** [FXMisc/RichTextFX#1260]
I have TextArea with text which length is, for example, 120 characters. And I need to lock text from the beginning to position 100. I mean that the user should not be able to do anything with the text in the range 0-100. 

In my situation it is very difficult to work with textArea.addEventFilter(KeyEvent.KEY_PRESSED,...) because there are menu item accelerators that can be configured via settings. So, I thought, maybe it is possible on text area low level API somehow to catch text change events and block them.

Could anyone help me?

**Comment by Jugen** [comment]
Try overriding the `replaceText( start, end, text )` method and then check that `start > 100` before calling `super.replaceText( start, end, text )`.

**Comment by Jugen** [comment]
Okay, then override `replace( start, end, doc )` instead, with the same logic as before.
