### ISSUE TITLE
Can tables be displayed alongside of text in the area?

### ISSUE THREAD

**Issue by reitffunk** [FXMisc/RichTextFX#193]
Hi,

is it technically possible to create Tables within a InlineStyleTextArea or is it not possible at all?

**Comment by TomasMikula** [comment]
Hi,

tables, or other kinds of nodes, are unfortunately not supported.

**Comment by reitffunk** [comment]
Ok, thanks for the fast answer and keep up the good work! :)

2015-10-21 20:01 GMT+02:00 Tomas Mikula <notifications@github.com>:

> Hi,
>
> tables, or other kinds of nodes, are unfortunately not supported.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TomasMikula/RichTextFX/issues/193#issuecomment-149978760>
> .
>



-- 
malte müller | tel. +49 176 20157655

**Comment by JordanMartinez** [comment]
@reitffunk Tables can now be displayed in an area alongside of text. However, getting the two to work together (e.g. when the user clicks inside the table, the area's caret should no longer appear and a caret should appear in the table) may be a bit harder.

**Comment by JordanMartinez** [comment]
Since this question was already answered, I'm closing this. Adding it as an enhancement should be discussed in #628
