### ISSUE TITLE
Add an inline style to a text segment

### ISSUE THREAD

**Issue by jeffreyguenther** [FXMisc/RichTextFX#2]
Is possible to add an inline style to substring? Right now, setStyle(String style) styles the whole control.

Can we get a method like?

``` java
setStyle(int from, int to, String style)
```

**Comment by corie-lc** [comment]
is it possible to have two different styles on one text segment?

**Comment by Jugen** [comment]
Yes it is, but it depends what you mean. If I'm not mistaken styles can't be overlaid separately, as in apply one style and then later on apply another style over the previous one. However you can combine styles and apply them on a segment, so you can get the previous style on a segment and add/update it and then reapply it to the segment.

**Comment by corie-lc** [comment]
@Jugen how are we to change text with lists? I can do 

InlineTextArea.setStyle(selection.start, selection.end, "-fx-fill: green");

how could i add multiple styles to selected text?

**Comment by Jugen** [comment]
@corie-lc can you give a more comprehensive example of what you want to do please ....

**Comment by Sylordis** [comment]
> @corie-lc can you give a more comprehensive example of what you want to do please ....

To take over what @corie-lc asked for, is there a method that can allow to set direct CSS styling to a text. For example, my users can define text styles how they see fit and change them, so I cannot create CSS files with the required classes.
For example, they will define a text style "note" that is italic with a certain colour, and can assign this style to a portion of text whenever they want.
But it seems that `setStyle` only takes CSS classes as arguments for the collection, not raw CSS styling, so calling `setStyle(<start>, <end>, "-fx-fill: #b20000; -fx-font-style: italic")` or `setStyle(<start>, <end>, List.of("-fx-fill: #b20000", "-fx-font-style: italic"))` (tried a bunch of stuff) does not do anything.

**Comment by Jugen** [comment]
You should use an `InlineCssTextArea` then.
