### ISSUE TITLE
Add support for a prompt / placeholder text when area is empty

### ISSUE THREAD

**Issue by kuc** [FXMisc/RichTextFX#256]
This would be a nice feature. Standard `TextArea` allows to set it.

**Comment by TomasMikula** [comment]
Also, standard JavaFX controls' approach to versatility is blending in more and more features in hope they will cover most use cases. But they can never cover all use cases. Moreover, this approach poses unnecessary overhead for users that don't need this or that feature. (And I'm less concerned about memory or CPU overhead, than I am about the cognitive overhead needed to be able to use the control correctly.)

My approach to versatility is breaking things apart, so that they can be recombined in different ways. I don't always do a great job of it on the first try, so please let me know if I can break something apart for you so that you can implement this feature on top of `StyledTextArea` yourself. It seems to me that you already can. You can register mouse listeners, text length listeners, and clear the undo-manager's history. That should be all that you need.

**Comment by kuc** [comment]
I personally don't think that very common feature of displaying placeholder is "unnecessary overhead". Implementing it by manipulating of `setText()` is possible, but you must account for many corner cases of accidental use of placeholder text as legitimate user input.

Another workaround could be using dynamically-created transparent background image with text on it. Or maybe using `StackPane` somehow.

**Comment by JordanMartinez** [comment]
> Another workaround could be using dynamically-created transparent background image with text on it. Or maybe using StackPane somehow.

Something like this?
````java
StackPane pane = new StackPane();
StyledTextArea area = // creation code;
pane.getChildren().add(area);

Text promptText = new Text(/* prompt string */);
// or perhaps setMargin would be better...
StackPane.setAlignment(promptText, Pos.TOP_LEFT);

area.lengthProperty().addListener((obs, ov, nv) -> {
    if (nv == 0) {
        pane.getChildren().add(promptText)
    } else {
        pane.getChildren().remove(promptText)
});
````

**Comment by kuc** [comment]
>Something like this?

Hmm, I think it's actually very close :smiley: 
But `Text` must be _behind_ `StyledTextArea`, because with this implementation you could set focus on it. I will try to post here some more complete example in the future.

**Comment by JordanMartinez** [comment]
> with this implementation you could set focus on it

Good point.
However, if it is behind the `StyledTextArea`, will it even appear in a `StackPane`? `StyledTextArea`'s background is white, so wouldn't that whiteness be displayed over the `Text`? If one reconfigured the `pickNode` code, it might get around that issue.

Now, if you use something other than `StackPane`, I guess you wouldn't have the above issue.

**Comment by melkhaldi** [comment]
Why not have it as a popup, placed at index 0? Richtext supports popup.

**Comment by JordanMartinez** [comment]
Hmm.... that's not a bad idea.

**Comment by melkhaldi** [comment]
Something like:
Iisten to text change property, if length is 0, set popup window and
show-will be at zero index. Else, remove.

**Comment by kuc** [comment]
That's terrible idea IMO, this has even worse problems with focus.

>However, if it is behind the StyledTextArea, will it even appear in a StackPane? StyledTextArea's background is white, so wouldn't that whiteness be displayed over the Text?

Why not set it to transparent color then? I read that's a common use case for StackPane, to layering multiple controls into one.

**Comment by melkhaldi** [comment]
Oops. Sorry for proposing a "terrible" idea!

**Comment by JordanMartinez** [comment]
> Oops. Sorry for proposing a "terrible" idea!

Why? It's a valid idea worth bringing up for discussion. If it happens not to work in this situation, so what?

> Why not set it to transparent color then? I read that's a common use case for StackPane, to layering multiple controls into one.

Oh. Ok! I haven't needed to do stuff like that yet, so I didn't know that :smile:

**Comment by kuc** [comment]
Huh? Don't be sorry, it's just my opinion that trying to solve this in that way would be unreliable. :wink:

**Comment by JordanMartinez** [comment]
@TomasMikula 
> It seems to me that you already can. You can register mouse listeners, text length listeners, and clear the undo-manager's history. That should be all that you need.

Except that using the above approach would also clear out the undo history. If a user typed something, cleared it (prompt text appears), and then redid the undo, there's nothing to undo. This only becomes an issue if one types a large amount of text into the area (and has a large undo history), deletes everything, and then tries to undo (via redo) their deletion.

**Comment by TomasMikula** [comment]
I only imagined to display the prompt before the user types anything, not whenever the area becomes empty. But I agree that displaying a node with the prompt above or below the area is probably a better idea.

**Comment by kuc** [comment]
Resolved using https://gist.github.com/kuc/d827edf158bb3cc31ef0 :blush:

**Comment by kuc** [comment]
https://github.com/TomasMikula/RichTextFX/wiki/Dropped-but-Now-Desired-Features

>Dropped but Now Desired Features (...) pull requests that implement them are desired:
>- Prompt.

@TomasMikula So, I if would integrate above code in RichTextFX, you will be happy to merge it?

**Comment by JordanMartinez** [comment]
@kuc I rewrote that page because at least three of those features had been requested and it seemed that Tomas would be pleased if someone implemented them. So, I assumed that the prompt feature would be included as well.

**Comment by kuc** [comment]
@JordanMartinez OK, so I could think about good implementation of prompt/placeholder in a free time 🙂
Code posted above works, but has some limitations (e.g. no wordwrapping of placeholder)

**Comment by JordanMartinez** [comment]
@kuc Probably, but I'm also not Tomas :smile:

**Comment by kuc** [comment]
@JordanMartinez I know 😉

**Comment by JordanMartinez** [comment]
Since the other features in the "Dropped, but Now Desired Features" page already have their issues open elsewhere, I'm reopening this one so we can delete that wiki page.
