### ISSUE TITLE
With wrap text enabled, typing characters into paragraph that is not fully visible on screen, causes visual flickering

### ISSUE THREAD

**Issue by alt-grr** [FXMisc/RichTextFX#260]
Steps to reproduce:
1. Create text area, enable wrap text property
2. Type or paste single line that is long enough, so start of paragraph is off-screen
3. Typing or deleting more characters in that line causes very visible blinking and redraws

**Comment by JordanMartinez** [comment]
Something like this? I'm not sure if the Gif-making program recorded it well.

![flickering](https://cloud.githubusercontent.com/assets/8413037/13226380/04a4438a-d946-11e5-952c-60a7f3c4b750.gif)

**Comment by kuc** [comment]
It's more clearly visible when text is inserted at the end of paragraph:

![flickering](https://cloud.githubusercontent.com/assets/1827393/13232771/e0e95ac8-d9b0-11e5-8e05-ee3884f22b73.gif)

**Comment by JordanMartinez** [comment]
I'm not sure whether to label this as a bug or enhancement. :smile:

**Comment by kuc** [comment]
@JordanMartinez IMO "enhancement" is for new features/performance improvements, and this is clearly a rendering bug.

**Comment by JordanMartinez** [comment]
You're right. Not sure why I thought otherwise *shrug*.

**Comment by JordanMartinez** [comment]
@kuc In my GIF, the rendering isn't as bad as the one you posted. So, can you provide a reproducible demo of this rendering bug?

**Comment by kuc** [comment]
@JordanMartinez Try typing on the end of the text.

**Comment by JordanMartinez** [comment]
@kuc That probably makes the difference. When I sit down to fix this bug, I'll try that.
