### ISSUE TITLE
Changing the text area height depending on fixed text size

### ISSUE THREAD

**Issue by sherzfel** [FXMisc/RichTextFX#405]
Hello,

I need to have an styletextarea that has an high that depends on the text, that is written in once by initialization. The text is not editable and is written once by initialization. The width is fixed und the wrapping property is set to true. How can i calculate the desired high of the styledtextarea? 

Please I need urgent help, because my boss  is sitting on my table.

**Comment by JordanMartinez** [comment]
I don't think anyone responded to this after you posted because they probably did not understand what your question was.

What do you mean by "a styled text area that has a **high** that depends on the text?" What do you mean by "high?" That's the part of your question that I do not understand.

**Comment by sherzfel** [comment]
I mean the height. I mean the number of the lines multiplicated with the style.

**Comment by JordanMartinez** [comment]
You seem to be asking, "How do I set the `StyledTextArea`'s height to change based on the font size of the area, so that (as I think this is the goal you are trying to reach) any given font size always adjusts the area's height so that at least a full `x` number lines are always displayed where `x` is the number of lines desired)?"

**Comment by sherzfel** [comment]
Yes, that I want to know. The StyledTextArea is not editable.

**Comment by JordanMartinez** [comment]
What are you using for the text style class? In other words, what is the second parameter in your area?
````java
StyledTextArea<ParagraphStyle, TextStyle> area = //
````
What is `TextStyle` in this case?

**Comment by sherzfel** [comment]
I call the following constructor:

new StyleClassedTextArea(). 

That constructor call:

 public StyleClassedTextArea(boolean preserveStyle) {
        this(
                new SimpleEditableStyledDocument<>(
                    Collections.<String>emptyList(), Collections.<String>emptyList()
                ), preserveStyle);
    }

**Comment by JordanMartinez** [comment]
Ok, so you're using `Collection<String>` as your style object and CSS to style the area. Ideally, you'd want to create an `EventStream` that handles this reactively:
````java
EventStream<Double> fontSize = // parses CSS for font size
EventStream<Double> lineSpacing = // parses CSS for line spacing
EventStream<Integer> nLines = // constructed from a Var or something else
EventStream<Tuple3<Double, Double, Integer>> lineHeight = EventStreams.combine(fontSize, lineSpacing, nLines);

lineHeight.map(tuple3 -> {
    double size = tuple3._1;
    double spacing = tuple3._2;
    int numLines = tuple3._3;

    return (size + spacing) * numLines;
}).feedTo(area.minHeightProperty());
````
I'm not sure how to parse the CSS manually to get the required values, but does this give you a better idea for what you need to do next?

**Comment by sherzfel** [comment]
I am using the branch with the getParagraphLinesCount method. But it doesn't work. Either the getParagraphLineCount returns the number of signs if wraptext is true or it returns 1 if wrapText is false.

**Comment by iazarny** [comment]
@sherzfel Try to 
```
Field field = FieldUtils.getField(codeArea.getClass(), "virtualFlow", true);
VirtualFlow oldVirtualFlow = (VirtualFlow) field.get(codeArea);
flow.visibleCells().size(); // guess, this is something, that you need 
```

**Comment by JordanMartinez** [comment]
#501 may help with this as you don't need to use reflection to get the size of visible cells.

**Comment by Jugen** [comment]
Closed via PR 944
