### ISSUE TITLE
Paragraph Questions.

### ISSUE THREAD

**Issue by ghost** [FXMisc/RichTextFX#41]
Hi Tomas,

To confirm, a paragraph is collection of styled texts that is separated from others by a new line before it and after it. right?

Would it be possible to provide a method to get Paragraph at caret?

Probably outside your scope, not sure. but do you plan to provide paragraph alignment options?

Thanks,
Maher

**Comment by TomasMikula** [comment]
Per-paragraph alignment is now supported with the latest SNAPSHOT.
