### ISSUE TITLE
AZERTY keyboard on Windows OS: SHORTCUT+SLASH key event does not run its consumer

### ISSUE THREAD

**Issue by ouaibsky** [FXMisc/RichTextFX#479]
Hi

I try to set a key shorcut on a CodeArea like this:
```java
        Nodes.addInputMap(codeAreaInstance
                          consume(keyPressed(SLASH, CONTROL_DOWN), this::commentRegion));
``` 

But nothing is happening, neither with "/" on numpad or "/" on regular place.
Replacing SLASH by other letter is working fine

Any ideas ?

PS: I'm running on windows 7, jre 8 upd 121 with azerty keyboard

**Comment by JordanMartinez** [comment]
I'm not sure why that's happening.... Perhaps, the JDK is mis-handling the keyboard input because of the azerty keyboard? 

If you add a catch-all `KeyEvent` listener, what gets outputted when you type `CTRL+SLASH`?

**Comment by JordanMartinez** [comment]
@ouaibsky any updates on this?

**Comment by ouaibsky** [comment]
Hi

A short update: While SLASH is working fine on my macbook pro, it fails on common windos keyboard (French)
I didn't investigate further more since I discover that **DIVIDE** is working fine.

Hope it helps
Chris.

**Comment by JordanMartinez** [comment]
So.... there's a workaround for this and it works for you? If so, I can close this, correct?

**Comment by JordanMartinez** [comment]
Since this doesn't seem entirely dependent upon RichTextFX and since you've posted your workaround, I'm closing this. Please reopen if it seems appropriate.
