### ISSUE TITLE
Question: How to translate the index of a visible paragraph into the index system of all paragraphs?

### ISSUE THREAD

**Issue by jmanc3** [FXMisc/RichTextFX#568]
How do you get the index of the first visible paragraph amongst all the paragraphs.
![image](https://user-images.githubusercontent.com/25911177/29245054-d9ce1480-7f91-11e7-999e-a12e53ae422b.jpg)

**Comment by JordanMartinez** [comment]
Sorry for not responding earlier.

This is a duplicate of #522, but I like your visual better than my explanation (below), so I'm closing the other one, not this one:

> `currentParagraph` is used to get the caret's paragraph index in terms of the total paragraphs, but now that #501 has been merged, there's not a counterpart for determining the caret's paragraph index in terms of the visible paragraphs. It should be `Optional<Integer> currentVisibleParagraph` 

Which version are you using?

**Comment by JordanMartinez** [comment]
Oh... actually it's not a duplicate :sweat_smile:

**Comment by JordanMartinez** [comment]
@jmanc3 Is this still a question you need answered? I was waiting for you to say which version you were using

**Comment by JordanMartinez** [comment]
This was added in #600
