### ISSUE TITLE
Trouble building project using NetBeans IDE due to ReactFX dependency

### ISSUE THREAD

**Issue by JordanMartinez** [FXMisc/RichTextFX#583]
**Edit: The original issue here got off-topic quickly and has been moved to #768. This issue's title has been updated to reflect that**

<hr>

I've been talking to Tomas about this for a while. See [the original thread here](http://mail.openjdk.java.net/pipermail/openjfx-dev/2017-September/020804.html)

> Hi everyone,
> 
> since I don't work with JavaFX (or GUI applications, or that matter)
anymore, it is hard for me to keep up with the maintenance of my JavaFX
projects. I am therefore looking for new maintainers (and possibly new
home) of my most active JavaFX project, RichTextFX (
https://github.com/TomasMikula/RichTextFX/), and its essential dependency,
Flowless (https://github.com/TomasMikula/Flowless/).
> 
> I want to thank Jordan Martinez, who has been doing the bulk of
fixing bugs and reviewing pull requests for the past two years.
> 
> I am hoping that either some bigger user of RichTextFX, or a UI framework
for which RichTextFX would be an attractive addition to the portfolio,
would step forward and take it up. Jordan and I are happy to help with the
transfer.
> 
> Best regards,
> Tomas

**Comment by Ansury** [comment]
I'm not claiming to be a big help here, but I might be able to help out some if I can get past some build environment issues. Building with Gradle works and the tests pass, but the Gradle NetBeans plugin keeps complaining about missing reactfx packages. Does anyone use NB+Gradle? (I'm using NB 8.2.) 

Build result is ok (ran from within NB): 
```
-----------------------------------------------------------------------
|  Results: SUCCESS (106 tests, 98 successes, 0 failures, 8 skipped)  |
-----------------------------------------------------------------------
:richtextfx:check
:richtextfx:build

BUILD SUCCESSFUL in 52s
14 actionable tasks: 14 executed
```

Below you can see the flagged package import, and ReactFX is present under Dependencies. The "Either" class is visible inside the util package, so all looks good to me. I've tried reloading the project, closing/opening, restarting NB... no change. Out of ideas to try at the moment. 
![gradle](https://user-images.githubusercontent.com/11338660/31421637-6cca5eb2-ae16-11e7-98e0-0867eac6df5e.jpg)

The demos project isn't building at all (this was a regular command line "gradle build"): 
```
gradle build
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :richtextfx:compileJava
/home/lou/git/RichTextFX/richtextfx/src/main/java/org/fxmisc/richtext/StyledTextArea.java:136: warning: [deprecation] impl_selectionFillProperty() in Text has been deprecated
        t.impl_selectionFillProperty().bind(t.fillProperty());
         ^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning

> Task :richtextfx-demos:compileJava
/home/lou/git/RichTextFX/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/hyperlink/HyperlinkDemo.java:3: error: package com.sun.deploy.uitoolkit.impl.fx does not exist
import com.sun.deploy.uitoolkit.impl.fx.HostServicesFactory;
                                       ^
/home/lou/git/RichTextFX/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/hyperlink/TextHyperlinkArea.java:68: warning: [deprecation] impl_selectionFillProperty() in Text has been deprecated
        t.impl_selectionFillProperty().bind(t.fillProperty());
         ^
/home/lou/git/RichTextFX/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/hyperlink/HyperlinkDemo.java:24: error: cannot find symbol
        Consumer<String> showLink = HostServicesFactory.getInstance(this)::showDocument;
                                    ^
  symbol:   variable HostServicesFactory
  location: class HyperlinkDemo
2 errors
1 warning


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':richtextfx-demos:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
5 actionable tasks: 5 executed
```

Ack... a com.sun import... 
Will try looking at this some more tomorrow. Should be building with OpenJDK 1.8.0_131. That's what I pointed NetBeans/Gradle to and that's what "java -version" reports.

**Comment by JordanMartinez** [comment]
> I'm not claiming to be a big help here, but I might be able to help out some if I can get past some build environment issues. 

That's always encouraging to hear!

Any particular reason why you are using NetBeans as your IDE instead of the other two common ones (Eclipse, IntelliJ)? Any particular reason why you're using OpenJDK instead of Oracle's one?

I'm not familiar with NetBeans, so I don't know what help I can offer you. Have you tried StackOverflow?

**Comment by afester** [comment]
Please try with Oracle's JDK 8 first. There are some issues with OpenJDK, like that JavaFX is not contained out of the box. Did you add JavaFX to your OpenJDK installation?

**Comment by Ansury** [comment]
I installed OpenJFX, so I don't think that's the issue. I could see another JDK helping particularly with that sun package error, so I'll try Oracle's. Actually, that totally makes sense. Main reason I'm working with OpenJDK is just convenience (on Linux Mint, already had it). 

And since you started it (hah)... I switched to NB from Eclipse (after about a decade!) after considering how glitchy and picky Eclipse can be. In light of this possible bug this is ironic, but I still feel that's generally true relative to NB. Eclipse Gradle support had some annoying glitches too a year+ ago. As popular as Gradle is, the IDE tooling sure does seem to be glitchy from what I've seen. 

IntelliJ... I forgot they have an open source edition. I guess I just prefer NB, but I could try IJ again if another JDK doesn't help. And in NB defense, I think it's a little more popular than you're hinting at, there. :)

**Comment by JordanMartinez** [comment]
> IntelliJ... I forgot they have an open source edition. I guess I just prefer NB, but I could try IJ again if another JDK doesn't help. And in NB defense, I think it's a little more popular than you're hinting at, there. :)

:smile: When I first learned about IDEs and tried out NetBeans and Eclipse, I was overwhelmed and confused. Then I tried out IntelliJ and it seemed more straight forward... However, I was trying to use them for Groovy projects, not Java, so that probably explains why :man_shrugging: To each, his own, right?

**Comment by Ansury** [comment]
Trivial maybe, but I'm a little turned off by the single-project-only model in IntelliJ, and that "flat" UI style.  

You guys don't have a collaboration area I assume (ex. Slack workspace)? For non-issue related stuff, I mean. 

Is anyone using Eclipse to build RichTextFX successfully? That'd be an easier learning curve (well, none) for me, assuming Gradle support behaves--so a better chance that I'd be useful. Looking for the path of least resistance here.

**Comment by JordanMartinez** [comment]
> Is anyone using Eclipse to build RichTextFX successfully? That'd be an easier learning curve (well, none) for me, assuming Gradle support behaves--so a better chance that I'd be useful. Looking for the path of least resistance here.

Tomas uses Eclipse, and he's the one that initially created this project. So, I think you'd be good going there.

> You guys don't have a collaboration area I assume (ex. Slack workspace)? For non-issue related stuff, I mean.

None that I know of. I think Tomas would respond to SO questions. I know TestFX uses Gitter, but sometimes conversations I have in there turn into ones that should be in issues. Personally, I find using issues to be easier because it keeps everything public and within a specific scope.

**Comment by Ansury** [comment]
A little reluctant to post questions of this nature on SO. I could see people closing it for being "too localized" or something, which completely defeats the purpose of the site IMO. IntelliJ seems to be working, other than the learning curve and inability to figure out how to get all tests to run at once. I'll give Eclipse + Buildship a shot too. 

Gitter looks pretty good, but without some kind of conversation-to-issue-importer I can see your point. I was just thinking I shouldn't make a habit of cluttering the issues area here (same problem, opposite direction). Hopefully the number of issues that need to move to Github from Gitter would be infrequent in comparison to the clutter being added here without a workspace. I'd be willing to try Gitter out if anyone wants to collaborate a little. I think I'm going to look into ways to improve performance with large text blocks--we'll see where that leads I guess.

**Comment by JordanMartinez** [comment]
I don't use IntelliJ to run tests. I use Gradle via ALT + F12 to bring up the terminal within the IDE and running it from there. There have been too many times where IntelliJ said a test passed when it failed when Gradle ran it. However, I have also set up an option within that IDE to delegate tasks to the Gradle runner.

On another note, you can put your caret in any single test class (as long as its on the outer class in integration test classes annotated with "@RunWith(NestedRunner.class)") and then press SHIFT + F10

**Comment by Ansury** [comment]
Turns out, the performance issue I'm seeing may not be as blatant as I thought. I wasn't able to reproduce it with a minimal test case. So once I figure out what I'm doing different in the other case, I'll post an issue assuming it isn't some mistake on my part.

**Comment by mataide** [comment]
Neatbeans works fine, you must use Oracle's JDK 8.

**Comment by JordanMartinez** [comment]
I've renamed this issue's subject line and am closing it since there haven't been any updates on it for quite some time.
