### ISSUE TITLE
Test Automation: Some tests do not work on Windows when using AWT Robot Adapter

### ISSUE THREAD

**Issue by afester** [FXMisc/RichTextFX#588]
By default, TestFX uses the "awt" robot adapter. At least on Windows, this results in the SHIFT key not properly handled when selecting text. RichTextFX test cases such as those in the ShiftDown test suite are then failing.
When setting the property `testfx.robot` to `glass`, text selection with the pressed shift key works and those test cases succeed.

The solution for the gradle build is to add `integrationTest.systemProperty "testfx.robot", "glass"` to the build file. (Will submitt a pull request after checking the same on Linux).

See also https://github.com/TomasMikula/RichTextFX/wiki/Test-Automation

**Comment by JordanMartinez** [comment]
Good to know. I'll wait for your PR

**Comment by afester** [comment]
I verified that the tests are running fine on X11 / Linux with the glass robot - would you be fine with setting the `testfx.robot` property to `glass` independant of the OS? Someone should test on Mac, though ;-)

BTW: Those integration tests are really cool. Can we establish a policy so that we accept pull requests only if a corresponding test is provided? :-)

**Comment by JordanMartinez** [comment]
> Someone should test on Mac, though

I think the headless Travis build uses the glass robot anyways, so I don't know if we need to test it on a mac. Mind submitting a PR?

> Can we establish a policy so that we accept pull requests only if a corresponding test is provided?

It would be ideal, but we should clean up the tests that we have right now. When I first wrote them, I wasn't going for accuracy as much as I was just trying to prove that the code works. So, some tests should have a few additional checks that aren't currently there right now.

**Comment by JordanMartinez** [comment]
Closed by #589

**Comment by JordanMartinez** [comment]
@afester Can you list which tests failed on Windows when the `awt` robot adapter was used? I'd like to have this build on both adapters on Windows in the CI build if possible. I'm not sure if the tests are flaky or not.

**Comment by afester** [comment]
I quickly run the tests from within Eclipse, using the awt robot. The failures are usually compare assertions (selection does not match the expected text) while the errors are usually something like `java.lang.IllegalArgumentException: Invalid key code`. I also aded my "counter" workaround for `waitForMultiLineRegistration` so that `pressing_up_moves_caret_to_previous_line` does not block the test execution (and that test than fails with a timeout):

![image](https://user-images.githubusercontent.com/2681864/31075991-806248d0-a778-11e7-9cbc-44dc07272203.png)

**Comment by afester** [comment]
BTW: I think this is more a TestFX issue. I have written this simple pure JavaFX test case: https://github.com/afester/FranzXaver/blob/testfx/Examples/src/main/java/afester/javafx/examples/testfx/SelectionTestFXExample.java and it also failes with the awt robot. I see the cursor moving in the input text field, but the text does not get selected. With the glass robot, this worked immediately.

**Comment by JordanMartinez** [comment]
The tests in question are currently skipped when using the AWT robot adapter (see #596), so that one can still build the project without needing to specify this directly. Still, it'll be better to learn more about the issue in the mentioned TestFX issue.
