### ISSUE TITLE
Feature: Provide mapping between all-paragraph and visible-paragraph index systems

### ISSUE THREAD

**Issue by JordanMartinez** [FXMisc/RichTextFX#599]
Given an index in `area.getParagraphs()`, one should be able to map it to its respective `area.getVisibleParagraphs()` index. Likewise, the index of the latter should be mappable to the index of the former. Thus, we should add an API like
````java
public final Optional<Integer> allParToVisibleParIndex(int allParIndex);
public final int visibleParToAllParIndex(int visiblePar);
````

**Comment by grenche** [comment]
@JordanMartinez Great! Thank you. How can I use it?

**Comment by JordanMartinez** [comment]
@grenche see the Readme's instructions on the snapshot release.
