### ISSUE TITLE
How to find the text offset of the last character currently displayed in the view?

### ISSUE THREAD

**Issue by garybentley** [FXMisc/RichTextFX#613]
I have a use case where I want to mark "how much of the text has been edited", that is if you have edited the text up to character 2000 I want to display a visual marker indicating this point in a margin to the left of the text area.  The marker would be a solid bar showing that the currently visible text has been marked as edited, thus 

To do this though I need to know what text offsets are currently visible in the view.  What is the best way to find out those offsets?  Specially I need the text offset of the last character visible but the first would also be useful.

I have tried using the text area's layout bounds but that, of course, leads to a position that is after the last line currently displayed in the view.

**Comment by JordanMartinez** [comment]
There are two "coordinate systems" to keep in mind here. The first is called "position" and refers to the positions between the letters of a text (e.g. `|` in `|t|e|x|t|`) and the second is called a character index and refers to the letters themselves

So... given an area with 50 lines of text, where the viewport is currently showing lines 30-33:
````
30 | some text
31 | some text
32 | some text
33 | some tex*t*
````
you want to figure out what the character index of the last "t" surrounded by asterisks is, correct? 

It seems like you'll need to use something like this:
````java
int lastVisibleParIdx = area.getVisibleParagraphs().size() - 1;
int paragraphOfChar = area.visibleParToAllParIndex(lastVisibleParIdx)
// calculation to determine where the character index is on that line
// this changes if you don't want to use that last character on the line
int indexOfChar = area.getParagraphLength(paragraphOfChar); 
int textCharIndex = area.position(paragraphOfChar, indexOfChar).toOffset();
````

**Comment by garybentley** [comment]
But wouldn't this just give the index of the last character in the paragraph?  For my use case I have a single paragraph that spans multiple lines in the view..  I need to find which line of the paragraph is currently visible at the bottom.  The paragraph may be only partially visible with more lines out of view below.

So from your example:

```
30 | some text ... more text that wraps in the view
30 | some text ...
30 | some text ...
30 | some tex*t*
30 | some text  <- this is not visible but still part of paragraph 30
```

**Comment by JordanMartinez** [comment]
ah... ok

You might try something like...
````java
Bounds local = area.getBoundsInLocal();
Bound screen = area.localtoScreen(local);
HitInfo hit = area.hit(screen.getMaxX() - 1, screen.getMaxY() - 1);
int charIdx = hit.getCharacterIndex();
````
