### ISSUE TITLE
What would be the preferred way for printing and/or save as pdf?

### ISSUE THREAD

**Issue by skinkie** [FXMisc/RichTextFX#619]
I am trying to print a RichTextFX Node, using the standard examples I might be able to print the Area node. But is there something more advanced for generating a PDF without going through the printing system?

**Comment by JordanMartinez** [comment]
I'm not familiar with the inside structure of a PDF file (it's XML right? :sweat_smile:), but you could try `area.getDocument()` to get the underlying model and then iterate through the document's `Paragraph`s and either its `styledSegments` or its segments and its style spans to get the finer parts of that.

**Comment by skinkie** [comment]
Would it be possible to get a HTML document out of RichTextFX? Then openhtml2pdf (via pdfbox) would work.

**Comment by JordanMartinez** [comment]
Short answer: yes

Long answer: If you follow the approach I shared above and write code that can convert the model information into a String that is HTML, I don't see why that wouldn't work.

However, if your goal is HTML, why not just use HTMLEditor?

**Comment by skinkie** [comment]
My goal is to have a lean way to edit, export pdf and print templates from JavaFX. I did not expect there was so few integration between individual pieces from an open source perspective. PDFBox for example only has AWT support to print, JavaFX itself only does normal printing, which for some reason or the other isn't very stable on my Linux distro (I reguarly get there are zero printers available). Your suggestion to use HTMLEditor is fine, I wasn't even aware of it. Which probably allows me to take the HTML and feed it to openhtml2pdf, and from pdfbox to awt printing.

**Comment by JordanMartinez** [comment]
Reopen this if you still need more help or have related questions.
