### ISSUE TITLE
Drop "Milestone" from release version and continue with 0.8, 0.9, 0.10, ...

### ISSUE THREAD

**Issue by JFormDesigner** [FXMisc/RichTextFX#622]
I'd like propose to drop the `0.7-M?` versioning scheme and continue with 0.8, 0.9, 0.10, etc versions.

We use `0.7-M?` versioning since one and a half year with 440 commits to master since `0.7-M1`.
Thanks to @JordanMartinez's fantastic work, there are so many improvements in RichTextFX that it is IMHO worth to leave the "Milestone" versioning.

The version still starts with `0.` so there actually is no need for milestones.

And some day we should consider to go to `1.0` 😃 

Opinions?

**Comment by JordanMartinez** [comment]
> I'd like propose to drop the 0.7-M? versioning scheme and continue with 0.8, 0.9, 0.10, etc versions.

Yeah... I've been wondering about that, too. We could return back to the semantic version scheme in this next release. However, I wasn't sure that, if we chose to do that, whether it should be `0.7` or `0.8`

**Comment by JordanMartinez** [comment]
I think we'll continue the version scheme at `0.8` because it provides a clean break from the `0.7` milestone release versions.

**Comment by JFormDesigner** [comment]
👍

**Comment by JordanMartinez** [comment]
The `0.8.0` release should show up on Maven soon.
