### ISSUE TITLE
Feature: support tables

### ISSUE THREAD

**Issue by mummyildiz** [FXMisc/RichTextFX#628]
Would it be nice if it was possible to add a table?

**Comment by JordanMartinez** [comment]
This would require a custom segment that could be added into the area. However, it would require modifying how the caret/selection works.

**Comment by mummyildiz** [comment]
tablo oluşturma özelliği olursa iyi olur.

**Comment by JordanMartinez** [comment]
> tablo oluşturma özelliği olursa iyi olur.

Google translates this as: "it would be better if the table creation feature."
