### ISSUE TITLE
TextField-like input in one line

### ISSUE THREAD

**Issue by piegamesde** [FXMisc/RichTextFX#635]
I am currently using a `CodeArea` as my input field. But I want to restrict the amount of lines a user can input to one and the component to be only one line high (like in a `TextField`). Also I need scrolling to be disabled since the component itself is embedded in another `ScrollPane`.

How can I do this in RichTextFX?

**Comment by JordanMartinez** [comment]
You're asking two questions:
- how do I restrict the area to only display one line?
  - answer: you don't. This is a feature that needs to implemented in Flowless, a dependency of RichTextFX. See #
- how do I remove scrolling behavior on the area
  - answer: you override the default behavior. If you look at `GenericStyledAreaBehavior` to see what the `InputMapTemplates` that get installed on the area are and see the `OverrideBehaviorDemo` to see how to override/remove behavior, you should be able to figure out what specifically you need to override to get the desired behavior.

On a separate note, we could always create a `RichTextField`. I've thought about implementing that for a while, too.

**Comment by JordanMartinez** [comment]
Also, please ask your questions in two separate issues rather than in one.

**Comment by JordanMartinez** [comment]
Closing since this is a duplicate
