### ISSUE TITLE
Read only pseudo class is misspelled in GenericStyledArea

### ISSUE THREAD

**Issue by Jugen** [FXMisc/RichTextFX#650]
The read only pseudo class parameter in [GenericStyledArea](https://github.com/FXMisc/RichTextFX/blob/ed58d3181898a54682da3151b07eb451578d52aa/richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java#L297) is currently `read-only` but to be consistent with CSS convention should be `readonly` (i.e. without the hyphen).

The misspelling causes the RichTextFX area to not respond to the CSS `:readonly` pseudo‑class.

**Comment by JordanMartinez** [comment]
That's my fault. It originally did not have the hyphen, but I added it because I thought it was breaking convention. Mind submitting a PR for that?
