### ISSUE TITLE
Regression of properties that could be set in FXML, fail in 0.8.1

### ISSUE THREAD

**Issue by Jugen** [FXMisc/RichTextFX#653]
Before RichTextFX 0.8.1 properties like wrapText and editable could be set in FXML, but they now fail :-(

The cause of this is that these properties were made **default** methods in [ViewActions.java](https://github.com/FXMisc/RichTextFX/blob/8619544311d39ea108fcfc6a5e1b07a6ba9027e3/richtextfx/src/main/java/org/fxmisc/richtext/ViewActions.java#L42), whereas previously they were implemented in [GenericStyledArea.java](https://github.com/FXMisc/RichTextFX/blob/v0.8.0/richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java#L308)

**Comment by JordanMartinez** [comment]
Dang... I did that so the `GenericStyledArea` file was cleaner and wasn't as long. I didn't know it would produce that affect. sigh...

Are there other properties besides these two that should also be moved back into GSA?

**Comment by Jugen** [comment]
Here is the full list of properties affected:

> editable
> wrapText
> autoScrollOnDragDesired
> 
> contextMenuObject
> contextMenuXOffset
> contextMenuYOffset

BTW if the following methods had `EventHandler<MouseEvent>` as a parameter instead of `Consumer<MouseEvent>` then they would also be accessible from FXML.

> onOutsideSelectionMousePress
> onInsideSelectionMousePress
> onNewSelectionDragEnd
> onSelectionDrop

**Comment by JordanMartinez** [comment]
Mind submitting a PR for that? And let's include the change from `Consumer` to `EventHandler`

**Comment by JordanMartinez** [comment]
Closed by #654. I've also opened #655 to address the second part of this issue.
