### ISSUE TITLE
Make mouse behavior override properties FXML-friendly

### ISSUE THREAD

**Issue by JordanMartinez** [FXMisc/RichTextFX#655]
Coming from #653, change the `Consumer` type of `setOnMouseDrop` and other related methods for overriding the default mouse behavior to `EventHandler`, so as to be FXML-friendly.

**Comment by Jugen** [comment]
I'm almost done, just one small thing I need help with. 
I can't find a reference to onNewSelectionDragEnd anywhere (neither getOnNewSelectionDragEnd() nor onNewSelectionDragEndProperty()) ?  I tried figuring out where it should be in [GenericStyledAreaBehavior](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledAreaBehavior.java), but there's no obvious spot.  Any suggestions .... ?

**Comment by JordanMartinez** [comment]
I'll have to respond to this tomorrow. Sorry.

**Comment by Jugen** [comment]
After reviewing the code it appears (if I'm not mistaken :-) that the `onNewSelectionDragEnd` functionality hasn't been implemented, so I've taken the liberty of adding it as part of this issue - see PR.

**Comment by JordanMartinez** [comment]
Closed by #656.
