### ISSUE TITLE
Enabling foreign language input

### ISSUE THREAD

**Issue by kavinkumarks** [FXMisc/RichTextFX#658]
We are using 0.6.10 version and using CodeArea to type in the user input.We need to enable the option to input languages like Japanese,French,German etc. using keyboard and the shortcuts in them.How do I achieve it?

**Comment by JordanMartinez** [comment]
This feature isn't yet implemented and doing so will be difficult since `GenericStyledArea` does not extend `TextInputControl`. See #146 for more info and please continue the discussion there. I am dealing with finals right now, so I won't be able to respond for a few more days, if not a week.

**Comment by kavinkumarks** [comment]
Thanks for the update!
