### ISSUE TITLE
Empty CodeArea

### ISSUE THREAD

**Issue by senges** [FXMisc/RichTextFX#660]
Hi !
As soon as my CodeArea gets empty, the application throws : 

> Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: Cannot get the type of a change that neither inserts nor deletes anything.

Any alternaive to that has been released ?
`text.richChanges()
                .filter(ch -> !ch.getInserted().equals(ch.getRemoved())) // XXX
                .subscribe(change -> {
                    text.setStyleSpans(0, computeHighlighting(text.getText()));
                });`

I just need Syntaxe Higlighting.

**Comment by JordanMartinez** [comment]
Upgrade to `0.8.1`

**Comment by senges** [comment]
Indeed, works like a charm.
Thanks !

**Comment by senges** [comment]
EDIT : No more Exception Thrown but it still removes all my EventHandler

**Comment by JordanMartinez** [comment]
If you're referring to event handlers, I'm guessing you are trying to override the behavior, correct? If so, see the `OverrideBehaviorDemo` for how to do that properly.

**Comment by senges** [comment]
Ok I see.
Thanks for your work !
