### ISSUE TITLE
Selection is no longer highlighted of inlineCssTextArea

### ISSUE THREAD

**Issue by Zethson** [FXMisc/RichTextFX#670]
-

**Comment by JordanMartinez** [comment]
> I apologize in advance for violating guidelines, first time creating an issue here and in general.

Meaning, are you not sure how to post a clear issue so that we can troubleshoot it and would like an explanation on how to do that? Or something else?

Since this isn't a self-contained application that reproduces the bug, I'm going to wait to hear back from you on my previous question.
