### ISSUE TITLE
how can i disable vertical scrolling and always show the whole text?

### ISSUE THREAD

**Issue by trapchar** [FXMisc/RichTextFX#674]
i was using TextFlow as a cell in ListView, and make it always expand horizontally.
so texts are always as wide as the parent, and if they don't fit in one line, they wrap, take up multiple lines, take up whatever vertical space is needed, all texts are visible all the time

but TextFlow misses features, for example, i'm told the easiest way to make text selectable is to use RichTextFX

RichTextFX is powerful, but maybe too powerful, now when the text is too long, a built-in scroll mechanism kicks in.  i searched around, i guess i can make it ignore certain mouse events, but i don't think that'll make the text always shown in its entirety on screen, right?

could you give me some pointers, thanks!

**Comment by JordanMartinez** [comment]
> RichTextFX is powerful, but maybe too powerful, now when the text is too long, a built-in scroll mechanism kicks in.

Yes, because that's what is expected for regular text editors. 

It sounds like you want to wrap the text so that the horizontal scrollbar never appears, correct? If so, have you turned on the text wrapping (e.g. `area.setWrapText(true)`)?

I'm also assuming that you don't want the vertical scrollbar to stop appearing or vertical scrolling to stop working at all, correct?

**Comment by trapchar** [comment]
@JordanMartinez Yes, I have turned on the text wrapping and got rid of the horizontal scrollbar. Also I want to completely get rid of the vertical scrolling, because actually I just want a more powerful TextFlow instead of a text editor.
I want it to shrink or expand vertically depending on how much content is currently put inside it.
I know RichTextFX is primarily designed for editors, but it looks quite flexible, I guess it can be made to work in many situations.

Thanks for your quick reply!

**Comment by JordanMartinez** [comment]
>  Also I want to completely get rid of the vertical scrolling

Sorry. I misread the issue's title where you explicitly state that, haha. See [OverrideBehaviorDemo](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/OverrideBehaviorDemo.java) to know how to override the default scrolling behavior and then check out [GenericStyledAreaBehavior](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledAreaBehavior.java) to see what specifically you need to override to prevent the vertical scrolling from occurring. You might also need to override some of the mouse behavior hooks (e.g. `onSelectionDrop(Consumer<MouseEvent>)` in `GenericStyledArea`) as that may also scroll the viewport at times.


> I want it to shrink or expand vertically depending on how much content is currently put inside it.

I think you mean #77

**Comment by JordanMartinez** [comment]
Since the behavior overriding is a FAQ, I've added my slight variation of my response above to a page in the wiki.

**Comment by aimozg** [comment]
I have similar problem as @trapchar - I want an auto-sizeable, non-scrolling, editable rich text area inside a list cell.

For auto-sizing, I override the `computePrefHeight`: (Kotlin language)
```kotlin
override fun computePrefHeight(width: Double): Double {
	val ih = insets.top + insets.bottom
	val c = children.firstOrNull() as? VirtualFlow<*, *>
	if (c != null && paragraphs.size > 0) {
		return ih + (0 until paragraphs.size).sumByDouble { i ->
			c.getCell(i).node.prefHeight(width)
		}
	}
	val d = totalHeightEstimateProperty().value
	if (d != null) return ih + d
	runLater { requestLayout() }
}
```

Scroll events are consumed by VirtualFlow, not Behaviour: https://github.com/FXMisc/Flowless/blob/master/src/main/java/org/fxmisc/flowless/VirtualFlow.java#L185
so I re-fire the event to parent on capture stage
```kotlin
addEventFilter(ScrollEvent.SCROLL) {
	it.consume()
	parent?.fireEvent(it.copyFor(it.source, parent))
}
```

**Comment by xulihang** [comment]
My steps:

1. set WrapText to be true
2. call totalHeightEstimate to adjust height
3. filter scroll event for the textarea and pass it to its parent(e.g. listview).
