### ISSUE TITLE
How can foreign alphabet inputs like Google's Hiragana input be rendered on GenericStyledAreas?

### ISSUE THREAD

**Issue by OscarEReyes** [FXMisc/RichTextFX#675]
I am trying to make it possible for users to be able to input words in foreign alphabets such as Hiragana/Katakana for example. This behavior **works** on a _regular_ TextArea from javaFX, possession of a keyboard for that language is obviously assumed.

Trying this on say, a GenericStyledArea results in "normal" input. Just the regular roman alphabet.

Would I have to add said capability (rendering of alphabet) for each desired alphabet, similarly to the way the wiki mentions implementing emojis?

**Comment by JordanMartinez** [comment]
It doesn't work on a regular `GenericStyledArea` because that object doesn't extend `TextInputControl`. You can see #146 for help in adding support for stuff like that, and you should be aware of #280.

**Comment by OscarEReyes** [comment]
That was very helpful! I got it to work now. Thanks for pointing me in the right direction.
