### ISSUE TITLE
Question: syntax highlighting

### ISSUE THREAD

**Issue by iAmGio** [FXMisc/RichTextFX#677]
Hi,
since I need to create a CodeArea with syntax highlighting, I tried the JavaKeywords demo to get started (using my own patterns) but, apparently, nothing changes. Can you please explain this argument here or in the wiki since there is nothing about this?
Thanks, and sorry for my inexperience.

**Comment by JordanMartinez** [comment]
> I tried the JavaKeywords demo to get started (using my own patterns) but, apparently, nothing changes.

Can you post the code that you're currently using to try to accomplish what you want to do? I can't help unless I see how you're modifying the demo's code.

> Can you please explain this argument here or in the wiki since there is nothing about this?

To which argument are you referring?

**Comment by iAmGio** [comment]
> To which argument are you referring?

Syntax highlighting.

> Can you post the code that you're currently using to try to accomplish what you want to do? I can't help unless I see how you're modifying the demo's code.

Start method:
```java
codeArea.setParagraphGraphicFactory(LineNumberFactory.get(codeArea));
codeArea.richChanges()
    .filter(ch -> !ch.getInserted().equals(ch.getRemoved()))
    .subscribe(change -> {
       codeArea.setStyleSpans(0, computeHighlighting(codeArea.getText()));
});
codeArea.getStyleclass().add("area");

```

computeHighlighting method:
```java
Matcher matcher = PATTERN.matcher(text);
int lastKwEnd = 0;
StyleSpansBuilder<Collection<String>> spansBuilder
    = new StyleSpansBuilder<>();
while(matcher.find()) {
    String styleClass =
        matcher.group("PATTERN_1") != null ? "class-1" :
        matcher.group("PATTERN_2") != null ? "class-2" :
        //Others
        null;
        assert styleClass != null;
        spansBuilder.add(Collections.emptyList(), matcher.start() - lastKwEnd);
        spansBuilder.add(Collections.singleton(styleClass), matcher.end() - matcher.start());
        lastKwEnd = matcher.end();
}
spansBuilder.add(Collections.emptyList(), text.length() - lastKwEnd);
return spansBuilder.create();
```

Maybe, the problem is styling. I'm using:
```css
.area .class-1 {
    -fx-fill: color;
}
```

**Comment by JordanMartinez** [comment]
Did you add your CSS file to the scene graph like so in the demo? Something like the line below should be in the start method, which I don't see.
````java
Scene scene = new Scene(new StackPane(new VirtualizedScrollPane<>(codeArea)), 600, 400);
scene.getStylesheets().add(JavaKeywordsAsync.class.getResource("java-keywords.css").toExternalForm());
````

There might also be an issue in your `PATTERN` object. Otherwise, everything else seems to check out clean.

**Comment by iAmGio** [comment]
I forgot to write it, stylesheets are added through FXML

**Comment by JordanMartinez** [comment]
I'm not sure what to tell you then. It seems like something else is messing up your syntax highlighting from working.

**Comment by iAmGio** [comment]
The CodeArea is inside a Tab. Could this be the cause?

**Comment by iAmGio** [comment]
I was using the 'g' flag (global) on my patterns, now it works. Thank you so much for your quick responses!

**Comment by JordanMartinez** [comment]
Glad you got it figured out!
