### ISSUE TITLE
Change behavior of PageUp and PageDown keys

### ISSUE THREAD

**Issue by JFormDesigner** [FXMisc/RichTextFX#688]
The behavior of the `PageUp` and `PageDown` keys in RichTextFX is IMO very unusual compared to other editors (Eclipse, IntelliJ IDEA, etc).

Let's say the text is 1000 lines long and there are 50 lines visible.

Pressing `PageDown` key in RichTextFX **moves the caret down 50 lines** and then scrolls the caret into the visible area. In case the caret was at the top, RichTextFx **scrolls only one line down**. The caret is then at the bottom of the visible area.

In other editors, the **text always scrolls 50 lines down** and the caret is also moved 50 lines down.

Would it be possible to change this in RichTextFX?

**Comment by JordanMartinez** [comment]
Just to be clear, you're saying the new behavior should move viewport so that it goes from displaying lines B to D to displaying lines E to G, correct?
````
----------- < top of document
|A
|======= < top of viewport
|B       < first line in viewport
|C
|D       < last line in viewport
|======= < Bottom of viewport
|E
|F
|G
|------------- < bottom of document
````

I've wondered about this myself. I'm ok with changing it. If people want to change it back, they can override the default behavior to what it was before.

**Comment by JFormDesigner** [comment]
> Just to be clear, you're saying the new behavior should move viewport so that it goes from displaying lines B to D to displaying lines E to G, correct?

Yes, exactly.

**Comment by JordanMartinez** [comment]
@JFormDesigner mind submitting a PR for this? Shouldn't be too hard.

**Comment by Jugen** [comment]
@JFormDesigner no I'm not working on PR yet, so please go ahead ....
