### ISSUE TITLE
Question: How to add style/padding to individual ParagraphBox? 

### ISSUE THREAD

**Issue by kszilagyi** [FXMisc/RichTextFX#691]
Hi,

So I figured out how to set padding for all lines:
```
.styled-text-area .paragraph-box{
    -fx-padding: 10 0 0 0;
}
```
Works very well. Now the problem is that I want to set it for particular lines (determined in runtime). But I couldn't figure out how to set a class for a particular paragraph box. Is that possible? 

Thanks

**Comment by JordanMartinez** [comment]
No, it's not possible to set it for specific lines, except for the first and last paragraph in the area and the paragraph that has the caret.

**Comment by kszilagyi** [comment]
Thanks for your answer. Is this by design? If I wanted this would I be able to add it with relatively little effort?

**Comment by JordanMartinez** [comment]
It is a limitation in the current design. Such a feature would need to modify the internal code; you wouldn't be able to add it by building on top of this project (at least not in a non-hacky way). 

It could probably be added by defining a style class naming scheme like "paragraph-box-`n`" where `n` corresponds to the paragraph index. Then, whenever ParagraphBox's index is updated, the old style class is removed (e.g. "paragraph-box-3") from the paragraph and the new style class is added (e.g. "paragraph-box-4")

**Comment by kszilagyi** [comment]
I see, ok, thanks for explaining

**Comment by JordanMartinez** [comment]
Coming from #692:

> Basically what I want to do is this:
> Load a file. Based on the content set some paragraph spacing big and some small. Would that work?
> I would also need to recalculate all the spacing whenever the content changes.

Let me put this into my own words to insure I'm understanding you correctly:
- You want to load a file and display its contents in an area
- Depending on the content on each paragraph, you'll want the paragraph to have some or no amount of space separating it from the previous and/or next paragraph. You want to set this spacing amount dynamically and not statically through a CSS style class.
- As the contents are edited (whether programmatically or by the user), you want this spacing computation to be recalculated

If I'm understanding you correctly, then it seems that the feature you want is to configure each paragraph each time it is either rendered or modified. That implies a `Consumer<ParagraphBox>` field being set in an area and being called each time a new paragraph is rendered to the screen and each time it's index is updated.

**Comment by kszilagyi** [comment]
I think yes but to be sure, here is and [example](https://d2.alternativeto.net/dist/s/55264ff3-497d-48bf-bd14-a78993a3f410_2_full.png?format=jpg&width=1600&height=1600&mode=min&upscale=false) from BeyondCompare of something very close to what I want to do. 
So basically, I want to have two code area and I want to align the text in the two so the ones which I think belongs together will be next to each other. Setting the padding seemed to be a natural solution for this problem.
So in the example I would set the bottom padding in the left line 19 to be as big so that the next line is aligned with line 22 on the right.

**Comment by JordanMartinez** [comment]
Ok... I see what you mean. Yes, then this is an entirely different feature. Reading it again, I realized I didn't pay attention to your comment about determining this at runtime and therefore wanting a dynamic non-CSS-styleclass approach. Still, others might want this feature, so please open a new issue for what you want and we'll continue from there.

**Comment by kszilagyi** [comment]
OK: #693
