### ISSUE TITLE
Add support for Region-typed Paragraph Graphics, so custom padding can be factored into layout call

### ISSUE THREAD

**Issue by kszilagyi** [FXMisc/RichTextFX#693]
## Desired Feature

I want to be able to specify padding of any paragraph dynamically, changing it runtime based on arbitrary calculations. 

Context: 
Here is an [example](https://d2.alternativeto.net/dist/s/55264ff3-497d-48bf-bd14-a78993a3f410_2_full.png?format=jpg&width=1600&height=1600&mode=min&upscale=false) from BeyondCompare of something very close to what I want to do.
So basically, I want to have two code area and I want to align the text in the two so the ones which I think belongs together will be next to each other. Setting the padding seems to be a natural solution for this problem.
So in the example I would set the bottom padding in the left line 19 to be as big so that the next line is aligned with line 22 on the right.

## Current Workarounds

Don't know of any apart from the hacky solution in this [PR](https://github.com/FXMisc/RichTextFX/pull/692). 

## Implementation Costs

I don't know. Unless it's huge I am happy to do it myself in case guidance is given.

**Comment by JordanMartinez** [comment]
So, there actually is a current workaround. You could use a paragraph graphic factory (for an example, see [LineNumberFactory](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/LineNumberFactory.java)) to add the necessary space by setting the minimum height of the returned node to some computed amount. 

So, something like:
````java
    @Override
    public Node apply(int idx) {
        Val<String> formatted = nParagraphs.map(n -> format(idx+1, n));

        Label lineNo = new Label();
        lineNo.setFont(DEFAULT_FONT);
        lineNo.setBackground(DEFAULT_BACKGROUND);
        lineNo.setTextFill(DEFAULT_TEXT_FILL);
        lineNo.setPadding(DEFAULT_INSETS);
        lineNo.setAlignment(Pos.TOP_RIGHT);
        lineNo.getStyleClass().add("lineno");

        // bind label's text to a Val that stops observing area's paragraphs
        // when lineNo is removed from scene
        lineNo.textProperty().bind(formatted.conditionOnShowing(lineNo));

        Region r = new Region();
        r.getChildren().add(lineNo);
        double minHeight = calculateHeightFor(idx);
        r.setMinHeight(minHeight);

        return r;
    }
````

**Comment by kszilagyi** [comment]
Thanks for the suggestion. Tried it out (needed to change Region to Pane to make it compile) but minHeight doesn't seem to do anything...

**Comment by JordanMartinez** [comment]
> needed to change Region to Pane to make it compile

Oh right... Region doesn't expose its children publicly. 

The general approach should still work, though I'm not sure why that wouldn't work. Pane is sometimes weird about things. Does the spacing change if you use a StackPane? (That will affect where the line numbers appear, but my thought is in determining what is required to make this approach work.)

**Comment by kszilagyi** [comment]
Nope, using StackPane doesn't make any difference at all :(

**Comment by JordanMartinez** [comment]
Ok. I looked at the `layoutChildren()` method in ParagraphBox [and this line](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/ParagraphBox.java#L246) is probably the reason why that approach isn't working. [resizeRelocate](https://docs.oracle.com/javase/8/javafx/api/) overrides the minimum height I believe.

**Comment by kszilagyi** [comment]
I see. So what can I do about that?

**Comment by JordanMartinez** [comment]
After looking at this more, I think the issue is not setting padding on the `StackPane`. So, if you updated my prior example to the following, I think that would work:
````java
    @Override
    public Node apply(int idx) {
        Val<String> formatted = nParagraphs.map(n -> format(idx+1, n));

        Label lineNo = new Label();
        lineNo.setFont(DEFAULT_FONT);
        lineNo.setBackground(DEFAULT_BACKGROUND);
        lineNo.setTextFill(DEFAULT_TEXT_FILL);
        lineNo.setPadding(DEFAULT_INSETS);
        lineNo.setAlignment(Pos.TOP_RIGHT);
        lineNo.getStyleClass().add("lineno");

        // bind label's text to a Val that stops observing area's paragraphs
        // when lineNo is removed from scene
        lineNo.textProperty().bind(formatted.conditionOnShowing(lineNo));

        // or try StackPane if Pane doesn't work
        Pane p = new Pane();
        p.getChildren().add(lineNo);
        Insets padding = calculateHeightFor(idx);
        p.setPadding(padding);

        return p;
    }
````
Or, you might need to use GenericStyledArea's `applyParagraphStyle` to directly modify the `ParagraphBox`, which is passed in as a `TextFlowExt`:
````java
(textFlowExt, paragraphStyle) -> {
  // ignore paragraph style, but do something to textFlowExt
  textFlowExt.setPadding(yourPadding);
  textFlowExt.setMinHeight(yourHeight);
}
````

**Comment by kszilagyi** [comment]
Thanks for the ideas. The first doesn't seem to work I am not sure why.
The second is better, though setPadding and setMinHeight doesn't seem to do anything.
I can use `textFlowExt.setStyle("-fx-padding: 100 0 0 0;")` though and it does what I need. The text can be edited and the formatting stays the same. The only problem is that the line number is in the middle of the line but that's a small one and I can live with it for now.

Thanks for the help.

**Comment by JordanMartinez** [comment]
I checked this out further. While the `ParagraphBox` and its graphic factor in the `ParagraphBox`'s padding when both are laid out / resized, the graphic does not factor in its padding. This is why your `setStyle` approach will add the necessary space to the line but make the line number appear in the middle rather than at the top. Since the graphic type is `Node`, there's no way to call `getPadding()` on the returned object, which could then be factored into the layout call. 

The solution would be to change the type of the graphic from `Node` to `Region`, which does support the padding option. However, that would force developers who just need to create a line number to wrap it in a `Region`, which costs additional memory and resources. Thus, I'm leaning towards changing the type to  `Either<Node, Region>` and allowing a developer to set the property via methods that handle the Either type for you.

**Comment by JordanMartinez** [comment]
I tried out my solution from above, but it still doesn't do quite what is desired. I think the only real way this can be resolved is if there's a `Consumer<ParagraphBox>` that can be called to customize the `ParagraphBox` dynamically. This would add another parameter to `GenericStyledArea`'s constructor and all of its subclasses.

**Comment by kszilagyi** [comment]
OK, I have checked this out again and it turned out I was using the modified LineNumberFactory from the first solution and that caused the misalignment. Using with normal LineNumberFactory actually seem to work. Here is how it looks, I think this is exactly what I need:

![image](https://user-images.githubusercontent.com/29373148/37177905-c391b37c-2318-11e8-915d-32efabff4d47.png)

Sorry about the mistake and many thanks for your help!

**Comment by kszilagyi** [comment]
However I think there might be a problem: I don't think I have access to the line number in `applyParagraphStyle` so I can't know what the padding should be...

**Comment by kszilagyi** [comment]
Can you confirm that there is no progress with this? I worked on the logic part of my project and hacked around this issue so far but now the logic is done, so I need to make the UI better. I plan to go to a different look (which might be better anyway) which doesn't need this feature, unless for some reason there is a new  solution/workaround for this. If there isn't I think we can close this and #691

**Comment by JordanMartinez** [comment]
See #768

**Comment by kszilagyi** [comment]
Ah, OK, anyway, thanks for all the help and for maintaining this project so far and good luck with Halogen!
