### ISSUE TITLE
Get paragraphs from a IndexRange selection

### ISSUE THREAD

**Issue by orange451** [FXMisc/RichTextFX#694]
I am implementing a simple code editor using CodeArea as a base. I wanted to add nice tab support such that if a few lines of text are selected and the user presses tab, all of those lines are tabbed outwards.

I only need to know how I can take an IndexRange from the getSelection() method and return a list of all paragraphs that are included.

I.E.
![image](https://user-images.githubusercontent.com/5247778/36704721-94c030c8-1b2f-11e8-86b4-c92e15921701.png)
This selection should return paragraphs: 3, 4, 5, 6, 7

**Comment by JordanMartinez** [comment]
````java
Selection<?, ?, ?> selection = area.getCaretSelectionBind();
int startVisibleParIdx = area.allParToVisibleParIndex(selection.getStartParIndex());
int endVisibleParIdx = Math.min(selection.getParagraphSpan(), area.visibleParagraphs().size())
List<Paragraph<PS, SEG, S>> pars = area.visiblePars().subList(startVisibleParIdx, endVisibleParIdx);
````
Technically `selection.getDocument().getParagraphs()` could work, too, but some of those paragraphs won't be visible if the selection spans outside of the viewport...

**Comment by orange451** [comment]
Am I potentially on a different version?
![image](https://user-images.githubusercontent.com/5247778/36705650-4b6a2226-1b34-11e8-97c2-7dfdacd56409.png)
Seems like I can't find a lot of those functions and classes.

**Comment by JordanMartinez** [comment]
I may have abbreviated some of the methods in my response (e.g. the
starting paragraph index)

**Comment by orange451** [comment]
Haha, alright. I'll play around with that! :)

**Comment by orange451** [comment]
This is my implementation, if anyone stumbled across this in the future:
`// Overwrite tab
Nodes.addInputMap(this,
	InputMap.consume(
		EventPattern.keyPressed(KeyCode.TAB), e -> {
			Selection<?, ?, ?> selection = this.getCaretSelectionBind();
			int startVisibleParIdx = this.allParToVisibleParIndex(selection.getStartParagraphIndex()).get();
			int endVisibleParIdx = Math.min(startVisibleParIdx + selection.getParagraphSpan(), this.getVisibleParagraphs().size());
			
			if ( endVisibleParIdx-startVisibleParIdx > 1 ) {
				for (int i = startVisibleParIdx; i < endVisibleParIdx; i++) {
					this.replaceText(i, 0, i, 0, TAB);
				}
			} else {
				this.replaceSelection(TAB);
			}
		}
	)
);`

Thanks again, @JordanMartinez !

**Comment by JordanMartinez** [comment]
Glad it worked for you.
