### ISSUE TITLE
Question: Change Color of the bar generated by the Linenumber Factory

### ISSUE THREAD

**Issue by liz3** [FXMisc/RichTextFX#704]
Hey,

simple question: I changed the color of the Codearea with:
`.styled-text-area .text{
    -fx-fill: #dbe0dc;
}`
im using CodeArea, just if its needed.
but with changing that css property, the linenumber factory styling also changes making the numbers dissapear:
<img width="65" alt="screenshot_148" src="https://user-images.githubusercontent.com/21298625/37312570-cdb4ceda-264b-11e8-9c62-e4b932fb28c8.png">

Is there a way to fix this and can i also change the background color?

Regards
Yann "Liz3" HN

**Comment by JordanMartinez** [comment]
use the `.lineno` styleclass instead. For other CSS inquiries, see the CSS Reference guide in the project's wiki.

**Comment by JordanMartinez** [comment]
Closing due to lack of inactivity and since I believe your question has been addressed. Reopen if you think otherwise.
