### ISSUE TITLE
Question: CodeArea with infinite scroll + line numbers

### ISSUE THREAD

**Issue by pedroAlba** [FXMisc/RichTextFX#706]
Im trying to upgrade an interface, that is built using Swing, in Java FX.

The interface has the following text area:
![image](https://user-images.githubusercontent.com/23246530/37740396-5310a56c-2d3c-11e8-8faa-3d6377fd19aa.png)

The only way i found, in JavaFX, to display those line numbers, is using the `CodeArea` component.

`textArea.setParagraphGraphicFactory(LineNumberFactory.get(textArea));`

![image](https://user-images.githubusercontent.com/23246530/37740654-44309d58-2d3d-11e8-9a20-57c5f4bff913.png)

This indeed displays the line numbers on the left of the component, but, it does not show on all lines. just the ones that are written on.

Is there any way to display the line numbers on all lines?

Thanks for the support!

**Comment by JordanMartinez** [comment]
Not in the way I think you would like. The line numbers are generated for each paragraph that is displayed in the area. So, if your area is empty and has no content, then it only has a single empty paragraph, hence the single line number displayed.

You could get more line numbers to appear if you were to add multiple empty paragraphs to the area (e.g. a user pressed [Enter] a lot). Your other option would be to add a separate node to the left of the area that can display where the line numbers would be. That might be a bit trickier to do.

**Comment by JordanMartinez** [comment]
Closing this as the question has (at least in my opinion) been answered and I don't foresee supporting this (potential) feature anytime soon.
