### ISSUE TITLE
PsychSQL

### ISSUE THREAD

**Issue by tmptmpuser** [FXMisc/RichTextFX#708]
Hi Jordan

I have used RichTextFX to build a SQL client with source highlighting:

http://softbydoc.dx.am/?page_id=135

Please let me know if I referenced your work correctly.

Regards

**Comment by JordanMartinez** [comment]
(I'm no lawyer, but) Yeah, it looks like it. You might want to include a hyperlink to the GPLv2 w/ Classpath Exception as you do with the BSD-Clause 2 license.

**Comment by JordanMartinez** [comment]
Also, would you like us to include your work in the ReadMe's list of projects that use this one?

**Comment by tmptmpuser** [comment]
Hi Jordan

>You might want to include a hyperlink to the GPLv2 w/ Classpath Exception

I have done so.

> Also, would you like us to include your work in the ReadMe's list of projects that use this one?

That would be nice. PsychSQL is a simple-to-use SQL client on top of JDBC. Features include SQL source highlighting, error tracking, view zooming, exporting to CSV.

Thx

**Comment by JordanMartinez** [comment]
Would you be willing to submit a PR for that? Shouldn't take much time or effort.

**Comment by tmptmpuser** [comment]
https://github.com/FXMisc/RichTextFX/pull/713

Regards
