### ISSUE TITLE
Incorrect result of GenericStyledArea.getStyleRangeAtPosition(int position) in 0.8.*

### ISSUE THREAD

**Issue by kelgon** [FXMisc/RichTextFX#711]
I encountered some incorrect behavior of GenericStyledArea.getStyleRangeAtPosition(int position) in version 0.8.*

Here goes the detail:

    InlineCssTextArea area = new InlineCssTextArea();
    area.appendText("1234567890");
    area.setStyle(5, 7, "-fx-fill:red;");
    System.out.println(area.getStyleRangeAtPosition(6)); //expect '5,7' but print '0,5'
    System.out.println(area.getStyleRangeAtPosition(8)); //expect '7,10' but print '0,5'

If I switch to version 0.7-M5, the result meets my expectation, which is '5,7' and '7,10'. But with 0.8.0, 0.8.1 or 0.8.2, the result is wrong.

**Comment by JordanMartinez** [comment]
Just a quick guess, but I think the wrong `TwoPosition.Bias` value is being used somewhere (e.g. `BACKWARDS` instead of `FORWARDS`).

I'll have to look into it more later on.

**Comment by JordanMartinez** [comment]
Turns out the paragraph list's navigator, not the style spans' navigator, is being used to calculate the position within the `StyleSpans` object.

**Comment by JordanMartinez** [comment]
Thanks for reporting that!

**Comment by JordanMartinez** [comment]
I've released a new snapshot that includes the fix for you.
