### ISSUE TITLE
Feature Request: Code folding

### ISSUE THREAD

**Issue by liz3** [FXMisc/RichTextFX#722]
Hey, if i am not completely stupid, RichTextFX does not have a function to fold/collapse code.
Im requesting this, because of course i can code a system which removes the lines, adds a btn which lets me adding them again, but the problem is the Line number factory, of course it would remove the lines i "collapsed" and thats not how it should be.

I do not know the RichTextFX codebase and can not judge how much effort this is, but it would be a cool thing.

Kind Regards,
Liz3

**Comment by JordanMartinez** [comment]
Duplicate of #107
