### ISSUE TITLE
Using in commercial project

### ISSUE THREAD

**Issue by jojorabbit** [FXMisc/RichTextFX#723]
Hi,
This is more question about licensing than a bug. RIchTextFX is Dual-licensed under BSD 2-Clause License and GPLv2 with the Classpath Exception.

This is a bit confusing for me since am not so familiar with these two licenses. But could you please answer some of my questions.

I have a project that I am planning to sell probably on the yearly subscription plan. 
Since it is commercial project am I allowed to use RichTextFX in that kind of project with subscription plan or one of those licenses does not allow that?

Btw I don't want to redistribute source code of my project.

Thanks.

**Comment by Jugen** [comment]
If I'm not mistaken you can do this under both licenses. The difference being that under GPL you need to make your code available to the customer, where as under BSD you don't.

**Comment by jojorabbit** [comment]
Hi,

So basically I can choose whatever license I want to use be it GPL or BSD. Well, currently I don't want to make the code available to a customer. 

But plans might change and maybe project will be open sourced it is not yet final. In case it is open sourced do I have to keep my code under BSD or can I use for example Apache License or any other license? I guess I would have to provide Apache and BSD license text file with the source code or can I use dual licensing?

Thanks.

**Comment by Jugen** [comment]
Again I stand under correction here but I think that if you choose RichTextFX under GPL then your code also needs to be GPL, whereas if you choose RichTextFX under BSD then your code can be licensed however you want - so yes then you could use or change to Apache.

**Comment by jojorabbit** [comment]
Thanks for the info. I will try to study both GPL and BSD.

**Comment by JordanMartinez** [comment]
See Tomas' comment in #351.
