### ISSUE TITLE
the demo JavaKeywordsAsync.java have a bug

### ISSUE THREAD

**Issue by lhuangjs** [FXMisc/RichTextFX#725]
There is a bug in class `JavaKeywordsAsync.java`. The method `multiPlainChanges()` does not exist. The method must be replaced by method `plainTextChanges()`
```
public void start(Stage primaryStage) {
        executor = Executors.newSingleThreadExecutor();
        codeArea = new CodeArea();
        codeArea.setParagraphGraphicFactory(LineNumberFactory.get(codeArea));
        Subscription cleanupWhenDone = codeArea.multiPlainChanges()
                .successionEnds(Duration.ofMillis(500))
                .supplyTask(this::computeHighlightingAsync)
...
  ```

**Comment by JordanMartinez** [comment]
It exists. You're probably using the wrong RTFX version (there isn't a stable release that includes that method yet) or have an issue with your dependencies' cache.

**Comment by JordanMartinez** [comment]
Since I haven't heard back from you and the latest stable release `0.9.0` includes the API, I'm closing this issue.
