### ISSUE TITLE
Question: Is there a way to have a fixed width for the .lineno CSS rule?

### ISSUE THREAD

**Issue by karpimpski** [FXMisc/RichTextFX#731]
I am creating a text editor and the LineNumberFactory resizes upon reaching double digits, triple digits, etc. I've tried setting -fx-min-width on the .lineno CSS selector, but it didn't change anything. Are there any CSS rules (or anything I can do in Java) to fix its width?

**Comment by JordanMartinez** [comment]
You could probably implement the [`format`](https://github.com/FXMisc/RichTextFX/blob/26bf5c2bd68bef17f4df958a38c5470fc5fb5cdd/richtextfx/src/main/java/org/fxmisc/richtext/LineNumberFactory.java#L71-L74) method differently, so that it pads the text with space or something
