### ISSUE TITLE
CodeArea not support Chinese

### ISSUE THREAD

**Issue by JamesChungZLL** [FXMisc/RichTextFX#732]
Can't type Chinese for codeArea  in Mac. Is there any way to fix it?
It is OK in Windows.
Thanks

**Comment by JordanMartinez** [comment]
See #146

**Comment by JamesChungZLL** [comment]
Yeah，fix the input problem with your help, thanks. However, could the getTextLocation function return the right location of the cursor?

**Comment by JordanMartinez** [comment]
I'm not sure what `offset` represents (is it the character position or index in the text?), but you can try [this method](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java#L864)

**Comment by JamesChungZLL** [comment]
It looks like that this method returns the specific charactor's location in the screen, not the cursor.

**Comment by JordanMartinez** [comment]
By `cursor`, do you mean `caret`? That method allows one to get the bounds on screen for any character. So, if you pass in the caret's position into the arg and add one to it, that would get you what you need.
Still, I suppose `Caret#getCaretBounds()` works, too.

**Comment by JamesChungZLL** [comment]
Yeah，well done.`Caret#getCaretBounds()`works.
