### ISSUE TITLE
Feature: Change padding values at run time

### ISSUE THREAD

**Issue by saifalmutory** [FXMisc/RichTextFX#739]
at `InlineCssTextArea`
I need to set `px` values by java code not css, what are the methods?
   `.styled-text-area .paragraph-box .paragraph-text {
      -fx-padding: 0px 0px 0px 0px;
   }`

  ` .styled-text-area .paragraph-box:last-paragraph .paragraph-text {
       -fx-padding: 0px 0px 0px 0px;
   }`

   `.styled-text-area .paragraph-box:first-paragraph .paragraph-text {
       -fx-padding: 0px 0px 0px 0px;
   }`

I tried:
`setParagraphStyle(getCurrentParagraph(),"-fx-padding: 0px 0px 0px 10px;");`
But I need to set other values, how can I do this?
Also do you have documents explaining the methods? Where?

**Comment by JordanMartinez** [comment]
Such methods don't exist. Is there a reason you're using `InlineCssTextArea` over something like `StyleClassedTextArea`?

**Comment by saifalmutory** [comment]
@JordanMartinez 
No reason yet
But `InlineCssTextArea` extends from `StyleClassedTextArea`!!
Is there an error in `InlineCssTextArea`?
Also if there are no methods, how do I change the padding values at run time?

**Comment by saifalmutory** [comment]
I think it's important to add something like this (change the values at runtime).
Do you also have documents or books explaining classes and methods?
I'm a beginner in rich text fx and I want to learn. Thank you

**Comment by JordanMartinez** [comment]
> I think it's important to add something like this (change the values at runtime).

I agree (though it will take some work to do). I think this project supports a lot of CSS but doesn't always provide a property that one can modify to change such a value at runtime. 

I'm going to flag this is a feature request now. Please update the title to reflect that.

**Comment by JordanMartinez** [comment]
@saifalmutory I've taken my comment and integrated it into the Home page on the [wiki](https://github.com/FXMisc/RichTextFX/wiki) after glancing through some of those pages. Let me know what made sense / did not make sense so we can clean it up where needed.
