### ISSUE TITLE
How to get bounds caret?

### ISSUE THREAD

**Issue by saifalmutory** [FXMisc/RichTextFX#745]
at InlineCssTextArea 
I need to get Caretbounds on the area not the screen
How?
also thanks for all your help to me

**Comment by JordanMartinez** [comment]
Should be something like:
````java
area.getCaretBoundsOnScreen().map(b -> area.screenToLocal(b)).orElse(new BoundingBox(0, 0, 0, 0));
````

**Comment by JordanMartinez** [comment]
Still, this is API that could be added in `Caret`. I didn't do so since most of the time it's used to know where to display a popup. If you want to open a PR that adds such functionality in a more efficient manner, it would be welcomed.

**Comment by saifalmutory** [comment]
`getCaretBoundsOnScreen()`
It requires something like CarenNode and does not accept to leave it empty
But
` getCaretBounds().map(this::screenToLocal).orElse(this.getBoundsInParent())`
Already worked 
Thank you Jordan

**Comment by JordanMartinez** [comment]
Sorry! I was referring to the same API you used above (`getCaretBounds()`) but thought it was called by a different name.
