### ISSUE TITLE
Putting the caret behind the character and pressing the enter causes the creation of an empty space at first

### ISSUE THREAD

**Issue by saifalmutory** [FXMisc/RichTextFX#748]
I do not know if the bug has been reported,
I searched but could not find,
The application I'm working on is very difficult to move here but I have worked a miniature application that summarizes the problem,
I hope you understand me well:

<hr>

## Expected Behavior

1. Make the caret behind the number 0
2. Press enter repeatedly until you reach the end of the window, you will notice the text stops descending (continue to press enter)
3. Select text from 0 to above You will notice that there is a large blank space due to pressing enter

## Reproducible Demo

````java
public class Bug extends Application {

 public void start(Stage primaryStage) {
        var area= new InlineCssTextArea();
        area.setPrefSize(400,600);
        var pane= new AnchorPane(area);
        var scene= new Scene(pane);
        for(var i=0;i<25;i++){
            area.appendText("\n");
            area.appendText(String.valueOf(i));
        }
        primaryStage.setScene(scene);
        primaryStage.show();
 }

}
````

## Environment info:

- RichTextFX Version: \<0.9.0\>
- Operating System: \<Windows 10\>
- Java version: \<10\>

**Comment by JordanMartinez** [comment]
Unfortunately, I'm having a hard time understanding you.
After I run the above code, I am supposed to do the three steps you mention in "**Expected Behavior**," correct? However, since you put that under the "**Expected Behavior**" section, what actually occurs when I do that?

**Comment by saifalmutory** [comment]
Please can you tell me what you did not understand?
Maybe my English is bad
But if you do the three steps you'll notice creating a blank space above the text(in Top) instead of going down the text to the bottom
This is written in the title

**Comment by JordanMartinez** [comment]
Are you wrapping your area inside a VirtualizedScrollPane?

**Comment by saifalmutory** [comment]
No, this can not be in my project

**Comment by JordanMartinez** [comment]
> Please can you tell me what you did not understand?

Given this code below:
````java
public class Bug extends Application {

 public void start(Stage primaryStage) {
        var area= new InlineCssTextArea();
        area.setPrefSize(400,600);
        var pane= new AnchorPane(area);
        var scene= new Scene(pane);
        for(var i=0;i<25;i++){
            area.appendText("\n");
            area.appendText(String.valueOf(i));
        }
        primaryStage.setScene(scene);
        primaryStage.show();

        // User interaction
 }

}
````
which produces an area like the following:
````
|--- Area Top
|
|0
|1
|2
|...
|24
{

(empty space)

}
|--- Area Bottom
````
I understand that at the comment `// user interaction`, I am supposed to do three things:
1. Move the caret behind the number 0 (where `^` represents the caret):
````
|--- Area Top
|
|^0
|1
|2
|...
|24
{

(empty space)

}
|--- Area Bottom
````
2. Press enter repeatedly until the last line reaches the bottom of the viewport
````
|--- Area Top
|
|
|
|
|
|^0
|1
|2
|...
|24
|--- Area Bottom
````
> [My paraphrase of what you said:] If you continue to press enter, you will notice the text does not continue to descend. Also, if you select the text from 0 to above, you will notice that there is a large blank space due to pressing enter

Correct. This is entirely what I **expect** it to do. So, what is it **actually** supposed to do?

It sounds like you want the viewport to "freeze." In other words, something like this...
````
|--- Area Top
|
|
|
|
|
|^0
|1
|2
|...
|24
|--- Area Bottom
````
... will change to the following after pressing enter once:
````
|--- Area Top
|
|
|
|
|
|^0
|1
|2
|...
|23
|--- Area Bottom
|24 // not rendered
````

**Comment by saifalmutory** [comment]
Yes, that's exactly what I'm trying to say
is this normal?

**Comment by JordanMartinez** [comment]
See the `showParagraph` prefixed methods, which you'll need to call to insure the viewport does not change (e.g. get the last visible paragraph index, insert the newline, call `showParagrahAsLast` (something like that) using the argument `lastParagraphIndex - 1`). 
You might also want to override the default behavior with your own so that the enter does not trigger a `requestFollowCaret()` call.
