### ISSUE TITLE
Feature: Set padding between lines in multi-line paragraph

### ISSUE THREAD

**Issue by saifalmutory** [FXMisc/RichTextFX#749]
When wrapping text, does not create a new paragraph and this is normal,
But we need to set the padding between the lines in one paragraph
Here the padding is set between paragraphs:

`.styled-text-area .paragraph-box .paragraph-text { -fx-padding: 10px 0px 0px 0px; }`

What should I do?

**Comment by JordanMartinez** [comment]
It sounds like you want to be able to set the padding in-between lines in a multi-line paragraph when the text is being wrapped during runtime. Such a feature is not supported at this time.

I think this could be supported (though I'm not sure of all the drawbacks) but would require another generic type  in `GenericStyledArea` for the paragraph type (similar to how we use `SEG` for a custom segment type).

Such an API might also be easier to implement if `TextFlow` exposed such a thing.

**Comment by saifalmutory** [comment]
"during runtime"!! Does this mean that padding can be set before run-time?

If not please tell me what should I do? This feature is required

**Comment by JordanMartinez** [comment]
> "during runtime"!! Does this mean that padding can be set before run-time?

Nope, not even at compile time.

> If not please tell me what should I do? This feature is required

Only one thing and that may take a lot of time. Contribute to OpenJFX and change the `TextFlow` API to add another CSS property that adds space between rendered lines of wrapped text that does not contain by a newline character.

**Comment by saifalmutory** [comment]
Hey my friend

`.paragraph-text { -fx-line-spacing:30;}`
This thing is already working, why do you say the opposite in wiki?
Update

**Comment by saifalmutory** [comment]
This works on the spacing of the lines in one paragraph and not several paragraphs and this is wanted.

**Comment by JordanMartinez** [comment]
Wow.... You're right. I wrote that part of the wiki and tested it out, so perhaps I thought it referred to space between multiple paragraphs, not the lines between multi-line paragraphs...? I really don't know how that happened....

Regardless, the wiki has been updated. Thanks for the correction!

**Comment by JordanMartinez** [comment]
This isn't a feature as much as realizing that the ability for this already existed. However, so that this will show up in the list of new "Features" when a new release is made, I'm labeling this as a enhancement and renaming it to account for that.
