### ISSUE TITLE
subscript and superscript

### ISSUE THREAD

**Issue by saifalmutory** [FXMisc/RichTextFX#751]
Is it possible to make subscript and superscript available in RTFX?
This can be in html easily but javafx does not contain this feature.

**Comment by saifalmutory** [comment]
For two days I was looking for how to do this,
It was simpler than expected !!
All you have to do is raise the character above the text
The Internet does not give an answer to this,
I have to rely on myself more next time do not rely on google
Sorry for that

**Comment by JordanMartinez** [comment]
I'm not entirely sure what you mean by "raise the character above the text." Could you clarify?
