### ISSUE TITLE
Add a setFont method to CodeArea

### ISSUE THREAD

**Issue by RohitAwate** [FXMisc/RichTextFX#754]
## Desired Feature

A setFont() method for CodeArea would be really helpful. JavaFX's default TextArea also comes with it.

## Current Workarounds

I'm using CodeArea for [Everest](https://github.com/RohitAwate/Everest) and currently setting the font through CSS. However, I'm loading custom user settings from a file which include the font family and size. I tried setting these attributes with setStyle() but that didn't work. Looks like currently there's no way to set these values without adding a stylesheet. Hence, I've had to revoke this feature temporarily.

## Implementation Costs
I haven't gone through the source but since this is already possible via CSS, I think the groundwork is there, so this shouldn't be too massive of a request.
I'm also okay with a workaround if you have one, but I think a text control should have a setFont method.

Also, I was hoping you could add Everest to '[Who uses RichTextFX?](https://github.com/FXMisc/RichTextFX#who-uses-richtextfx)'.

Thanks! :)

**Comment by JordanMartinez** [comment]
> Also, I was hoping you could add Everest to 'Who uses RichTextFX?'.

Nice application! Usually, we just ask you to submit a PR that includes a link to it on the ReadMe.

I agree that this feature should be added. Would you be willing to do the work if I helped you do it?

**Comment by RohitAwate** [comment]
> Usually, we just ask you to submit a PR that includes a link to it on the ReadMe.

Oh, I thought I have to message you somehow. I'll do this. :+1:

> Would you be willing to do the work if I helped you do it?

Sure. I can certainly give it a shot. I hope its not too complex though.

**Comment by JordanMartinez** [comment]
> Unrelated to the issue but, I'm having a hard time parsing XML for Everest and I don't wish to invest too much time in regex. Is it cool if I use XMLEditorDemo?

This project is dual-licensed (as in, "choose which license you want to use") and that includes the demos. So, go for it as long as it abides by one of those licenses (probably the BSD-2)

> Oh, I thought I have to message you somehow. I'll do this. :+1: 

Great!

> Sure. I can certainly give it a shot. I hope its not too complex though.

It's really not. However, after thinking about it more, I'm not sure whether that would be desired/needed. If you did submit a PR, you'd need to..
- add a CSS property to `GenericStyledArea` (see [an example CSS property](https://github.com/FXMisc/RichTextFX/blob/b8b7afde4169c54bc875a07150f352b2c8eda72d/richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java#L316-L320) and [follow this example for how to add it to the area's CSS properties](https://github.com/FXMisc/RichTextFX/blob/b8b7afde4169c54bc875a07150f352b2c8eda72d/richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java#L1559-L1572)). 
- add a corresponding property in ParagraphText ([like this one](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java#L66-L69)) and set up ParagraphBox to expose that API [like here](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/ParagraphBox.java#L129)
- In `createCell`, which creates the ParagraphBox, bind a new cell's corresponding property to the area's property ([example](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java#L1370)) and have it unbind when the cell is disposed to prevent memory leaks ([example](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java#L1462)). 
- Then, to make it all work, we need to override the text's font property whenever the area's font property changes [in these lines](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java#L149-L158).

It's this last part that is up for discussion. Assuming a developer other than you wants each text's font to be different, then whatever we change should not interfere with that. In other words, if a given text object is styled in such a way that it should be rendered in one font (i.e. Arial) that's different from the area's font (i.e. Times New Roman), I think the text should be rendered in Arial, not Times New Roman.

And it's this last part that makes me wonder whether such a PR is even necessary (or desirable). For example, although there is no "set font" method on the area, you could easily create one in your custom area. How? By defining a custom style type that merges the "style a text by style class" and "style a text by setting its properties" methodologies described in [the wiki page on this topic](https://github.com/FXMisc/RichTextFX/wiki/Text-Styles%3A-Inline%2C-Style-Class%2C-and-Custom-Style-Objects). The following code is an example of how you could do that.

Given an immutable custom style object:
````java
public class FontAndStyle {
    private final Font font;
    private final String styleClass;

   // and getters

    public FontAndStyle(Font f, String, s) {
        this.font = f;
        this.styleClass = s
    }

    // and corresponding style class setter
    public FontAndStyle setFont(Font f) { new FontAndStyle(f, styleClass); }
}
````
and a custom `applyStyle` in [this method](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/StyledTextArea.java#L89-L100), which is what most use to create the Text object in the first place
````java
(TextExt text, FontAndStyle s) -> {
    text.setStyleClass(s.getStyleClass());
    text.setFont(s.getFont());
}
````
and by using [StyleSpans#mapStyles](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/model/StyleSpans.java#L168-L183), you could remap all the styles' font to a new one using this method in you area:
````java
public void setFont(Font f) {
    StyleSpans<FontAndStyle> spans = this.getStyleSpans();
    this.setStyleSpans(spans.mapStyles(s -> s.setFont(f));
}
````
The end result is that each text object that gets rendered would have the same font and you'd have an easy convenience method to do that.

**Comment by RohitAwate** [comment]
> This project is dual-licensed (as in, "choose which license you want to use") and that includes the demos. So, go for it as long as it abides by one of those licenses (probably the BSD-2)

Great! So is it enough if I include BSD-2 in the copyright header of my XML highlighter (with a link to the demo) along with my own Apache 2.0 since there are minor modifications to your demo?

I see your point regarding whether this method is really necessary and I agree that for StyledTextArea, the proposed method may be a problem. But I think it makes sense for CodeArea. I don't think anyone uses multiple fonts in their code editors. What do you think?

Also, thanks for the detailed guidelines for the PR and the workaround! :+1: 
They'll be really helpful whichever way we chose to go.

**Comment by JordanMartinez** [comment]
> Also, thanks for the detailed guidelines for the PR and the workaround! +1
They'll be really helpful whichever way we chose to go.

You're welcome!

> Great! So is it enough if I include BSD-2 in the copyright header of my XML highlighter (with a link to the demo) along with my own Apache 2.0 since there are minor modifications to your demo?

Mm... I'm not going to answer that question since it implies legal advice ;-). I think the license tells you what you need to do. AFAIK, Apache 2.0 can "absorb" the BSD-2 [according to this chart](https://stackoverflow.com/questions/1978511/is-there-a-chart-of-which-oss-license-is-compatible-with-which)

> But I think it makes sense for CodeArea. I don't think anyone uses multiple fonts in their code editors. What do you think?

But since `CodeArea` is a subclass of `GenericStyledArea`, the same issue would still arise. We'd still have to modify `GenericStyledArea` to allow `CodeArea` to do that. If you made your own custom `CodeArea` that specifies the `S` parameter of `GenericStyledArea` to the above code, then it'll still work as you'd like.

**Comment by RohitAwate** [comment]
> But since CodeArea is a subclass of GenericStyledArea, the same issue would still arise. We'd still have to modify GenericStyledArea to allow CodeArea to do that. If you made your own custom CodeArea that specifies the S parameter of GenericStyledArea to the above code, then it'll still work as you'd like.

I see. I've already subclassed CodeArea so I'll just follow your workaround.

> Mm... I'm not going to answer that question since it implies legal advice ;-). I think the license tells you what you need to do. AFAIK, Apache 2.0 can "absorb" the BSD-2 according to this chart

Haha right. Everest is my first serious public project so this legal stuff is a bit confusing. I'll still include your license and a link since the demo saved a week of my work and works perfectly. The Java demo was also really helpful in writing my JSON highlighter.

Closing this. 
This exchange was really informative. Thanks for your work! :)
Good luck.

**Comment by JordanMartinez** [comment]
Glad to have helped and wish you well on your project!

If you ever want to hack away at RTFX and need a deeper understanding of it, see [the wiki's home page](https://github.com/FXMisc/RichTextFX/wiki), which lists various things to read for various levels of understanding
