### ISSUE TITLE
Who uses RichTextFX ( XR3Player) 

### ISSUE THREAD

**Issue by goxr3plus** [FXMisc/RichTextFX#756]
The biggest and more complete JavaFX media player ( OpenSource) 

On Github :
https://github.com/goxr3plus/XR3Player

Website :
https://goxr3plus.github.io/xr3player.io/

Hope you add it :) Thank you so much for thia amazing library!!! ♥

**Comment by JordanMartinez** [comment]
Thanks! Actually, rather than I adding it, we ask you to submit a PR that adds it.

**Comment by goxr3plus** [comment]
Perfect :)

**Comment by goxr3plus** [comment]
@JordanMartinez  Ready :) #757

**Comment by JordanMartinez** [comment]
Closed by #757
