### ISSUE TITLE
Question: Change StyleClassedTextArea Text Color

### ISSUE THREAD

**Issue by SkyAphid** [FXMisc/RichTextFX#760]
Hello! I'm a bit of a CSS novice. So I apologize in advance if this turns out to be a stupid question.

I'm trying to change the color of the text in a StyleClassedTextArea. I've tried all sorts of things and nothing is changing it. It just stays black.

Here's all of the code:
```
StyleClassedTextArea projectNameField = new StyleClassedTextArea();
projectNameField.insertText(0, project.getName());
		
projectNameField.setBackground(Background.EMPTY);

String fontStyle 	= "-fx-font-family: '" + robotoRegular20.getFamily() + "'; -fx-font-size: " + robotoRegular20.getSize() + ";";
String colorStyle 	= "-fx-fill: " + Button.getTextColorCode() + ";";
String borderStyle 	= "-fx-border-color: " + Button.getTextColorCode() + "; -fx-border-width: 0 0 1 0;";
		
projectNameField.setStyle(fontStyle + colorStyle + borderStyle);
```

Just to clarify, the Button.getTextColorCode() works everywhere except on the text area color.

Why isn't -fx-fill working here? I also tried various other color commands. None of them do anything. 

Thanks for your time and the API!

**Comment by JordanMartinez** [comment]
Not a stupid question. I don't particularly like or always understand CSS either.

Please read through the [wiki page on styling](https://github.com/FXMisc/RichTextFX/wiki/Text-Styles%3A-Inline%2C-Style-Class%2C-and-Custom-Style-Objects). That should answer your question. It seems you are confusing inline css styling with style class styling.

**Comment by SkyAphid** [comment]
I managed to get it to work by changing it to an InlineCssTextArea and doing this based on a similar question I found on here:

`projectNameField.setStyle(0, projectNameField.getText().length(), "-fx-fill: " + Button.getTextColorCode() + ";");`

Have you guys made a cleaner way to do this yet? Otherwise I have to reset the style every time the field is modified.

**Comment by JordanMartinez** [comment]
> Have you guys made a cleaner way to do this yet? Otherwise I have to reset the style every time the field is modified. I tried just using -fx-fill normally but it wasn't working until I used this version with the range attached.

It sounds like you goal is to create an area whose text fill is updated during runtime using a value set by a user. Have you checked out [the RichText demo](https://github.com/FXMisc/RichTextFX/tree/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext) (see RichTextDemo.java and TextStyle.java) where we do the same thing?
