### ISSUE TITLE
controlling text area height dynamically based on content.

### ISSUE THREAD

**Issue by ghost** [FXMisc/RichTextFX#77]
Hi Tomas, I was wondering if it is possible to control the hieght of the text area dynamically by its content( number of lines and sizes if characters) as well as the width of the area. In a sense, I don't want a vertical scroll bar, but rather I want the text area height to grow based on the text itself and the width of the text area.

Is there a way to do this?
Thanks
Maher

**Comment by JordanMartinez** [comment]
This might be possible if one could determine the bounds of the visible paragraphs and adjust the area's size (up to a maximum/minimum size) whenever the visible paragraphs change.

**Comment by Jugen** [comment]
Closed via PR 944
