### ISSUE TITLE
OPEN_BRACKET - can't prevent the behavior

### ISSUE THREAD

**Issue by MrChebik** [FXMisc/RichTextFX#771]
Hi, I tried to prevent the behavior of pressing a key `OPEN_BRACKET` to add ability add `CLOSED_BRACKET`. But I can't do this.

```java
InputMap<Event> prevent = InputMap.consume(
    anyOf(
        keyPressed(OPEN_BRACKET, SHORTCUT_ANY, SHIFT_ANY)
    )
);
Nodes.addInputMap(this, prevent);

this.setOnKeyPressed(event -> {
    if (event.getCode() == KeyCode.OPEN_BRACKET) {
        int position = this.getCaretPosition();
        this.insertText(position, "[]");
        this.moveTo(position + 1);
    }
});
```

#### Expected behavior:
`[]`
#### Actual behavior:
`[[]`

The same situation for other characters, such as `' " < ( {`

**Comment by ekartoyev** [comment]
You will, because pressing keys sends several events, such as KEY_PRESSED, KEY_RELEASED, KEY_TYPED etc., and RichTextFX evidently fires off on any of them. Therefore, if you capture one event, but not another, most likely it will come through to your rich text view.

I managed to avoid that behavior by capturing ANY key event as follows:

```java
scene.addEventFilter(KeyEvent.ANY, ke -> {
            if (Keys.CTRL_Z.match(ke)) {
                ke.consume()
                doSomething();
                return;
            }

           if(Keys....
          ...
});
```

where Keys.CTRL_Z is:

```
public static final KeyCombination CTRL_Z = new KeyCodeCombination(KeyCode.Z, KeyCombination.CONTROL_DOWN);
```

**Comment by MrChebik** [comment]
A good way but this break all behavior.
It seems that during UNDEFINED - a symbol is inserted, but I can not find it, because even if I take the text from it, it will be empty. So I have to paste the text into the editor myself through catching up to this call, for example KEY_PRESSED.

```java
KeyCombination OPEN_BRACKET = new KeyCodeCombination(KeyCode.OPEN_BRACKET);

this.addEventFilter(KeyEvent.ANY, ke -> {
    if (!"UNDEFINED".equals(ke.getCode().toString())) {
        if (OPEN_BRACKET.match(ke)) {
            ke.consume();

            if ("KEY_RELEASED".equals(ke.getEventType().getName())) {
                int position = this.getCaretPosition();
                this.insertText(position, "[]");
                this.moveTo(position + 1);
            }
        } else if ("KEY_RELEASED".equals(ke.getEventType().getName()) &&
                ke.getText().charAt(0) != 8) {
            this.insertText(this.getCaretPosition(), ke.getText());
        }
    } else {
        ke.consume();
    }
});
```

Like this, it somehow works, including Backspace. But it also breaks the selection, and other keys that are familiar in writing the combination.

**Comment by ekartoyev** [comment]
I don't know what is UNDEFINED in key codes and why you involve it, but what semantically fully substitutes the setOnKeyPressed and consumes any subsequent events is this:

```java
KeyCombination OPEN_BRACKET = new KeyCodeCombination(KeyCode.OPEN_BRACKET);

this.addEventFilter(KeyEvent.ANY, ke -> {
            if (OPEN_BRACKET.match(ke)) {
                ke.consume();
		if (ke.getEventType() == KeyEvent.KEY_PRESSED) {
		        int position = this.getCaretPosition();
		        this.insertText(position, "[]");
		        this.moveTo(position + 1);        	}
                return;
            }
});
```
This code exactly matches the code you originally posted, except it is fired not on KEY_PRESSED, but  on ANY key event related to OPEN_BRACKET.

It shouldn't break any other keys, selections etc. because it doesn't consume that. It consumes **only** OPEN_BRACKET.

**Comment by MrChebik** [comment]
Tested with [JavaKeyWordsDemo](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/JavaKeywordsDemo.java), I also meet `UNDEFINED`.

By itself the example works like `setOnKeyPressed` but with `UNDEFINED` which add identicaly behavior at the header of problem: `[[]`, and my attempts to remove the extra square bracket  with `addEventFilter` in vain.

I found workaround:
```java
int position = codeArea.getCaretPosition();
codeArea.insertText(position, "]");
codeArea.moveTo(position);
```

**Comment by ekartoyev** [comment]
Hm... Seems like you still do not control the keyboard. Make sure you know why you need that UNDEFINED thing and if you need it at all. 

Also, make sure you add the event listener at the right level.

Probably, you should add it to the toppest level - the container or the scene that contains the rich text node, not to the rich text node itself. 

If you extend the rich text node (as I infer from your piece of code) and include it into your scene, then you could pass the reference to that scene in your class constructor, and add the event listener to the scene, there.

That workaround is not a solution. The bracket *must* be consumed, if you want it to work stably and flawlessly.

**Comment by MrChebik** [comment]
I tried add `addEventFilter` on the main stage - the window and make focus to `TreeView`. But also get `UNDEFINED`. I don't know what it.

I also noticed, that the workaround is slowly.

**Comment by MrChebik** [comment]
I found quickly workaround through change listener.
In principle, this method is not so much a workaround. This can close my problem.

```java
this.multiPlainChanges()
    .subscribe(autocomplete::callSnippet);

//...

public void callSnippet(List<PlainTextChange> changeList) {
    String inserted = changeList.get(0).getInserted();

    if (inserted.equals("[")) {
        int position = codeArea.getCaretPosition();
        codeArea.insertText(position, "]");
    }
}
```
