### ISSUE TITLE
Bug: Pasting Clipboard-Content when there is an active selection causes exception

### ISSUE THREAD

**Issue by Cyboot** [FXMisc/RichTextFX#786]
If the CodeArea contains an active selection (For example the word "hi" is selected) and you try to paste your clipboard content (For example the word "hello") an exception occures.

The bug is reproducable and I think I found already the location of the problem. In the class `org.fxmisc.richtext.SelectionImpl<PS, SEG, S>` in line 276 there is the following method call:
`selectRange(finalStart, finalEnd);` 
The problem seems to be that `finalEnd` is smaller than `finalStart`, this causes the exception later.
The values are computed a few lines above. I did not totally understand the logic, but the problem seems to be that `finalStart` is increased by some values but `finalEnd` is not updated correctly.

Version is: 0.9.1

**Comment by Cyboot** [comment]
Replacing the line 
`selectRange(finalStart, finalEnd);`
with
`selectRange(finalStart, Math.max(finalEnd, finalStart));`
seems to work. But I don't think this is the correct solution.

**Comment by Jugen** [comment]
Thanks, this has been reported in issue #774 and fixed with PR #775
