### ISSUE TITLE
[Unexpected behavior] Pressing mouse on empty lines inside selected text and moving mouse unselectes selection instead of initiating drag

### ISSUE THREAD

**Issue by MioRtia** [FXMisc/RichTextFX#787]
Hi
First of all, thank you for your work!
I have started using your API and while testing it, I think there is something wrong with the drag when trying to drag a selection containing empty lines. I described the issue below.
Thank you in advance !

## Expected Behavior

When pressing mouse inside the selection to drag it, the caret should move until the selection is dropped.

## Actual Behavior

When the mouse is pressed on empty lines **inside** the selection, it unselects it as if it was pressed outside the selection.

## Reproducible Demo
![issue_richtextfx 1](https://user-images.githubusercontent.com/15137981/48701903-e1096300-ebef-11e8-8284-96bf95cf0f3e.gif)

## Environment info:

- RichTextFX Version: 0.9.1
- Operating System: Linux

**Comment by Jugen** [comment]
This doesn't just happen on empty lines, but also wherever the mouse click position is after a line-break / carriage return character (i.e. wherever there aren't any white-space characters).

**Comment by Jugen** [comment]
I've had a quick look at various text editors, word processors, and IDE's and RichTextFX's behavior is consistent with some of them. So on the one hand for example Eclipse IDE behaves like RichTextFX, whereas MS Word 2013 has the behavior that @MioRtia is expecting.

So it seems to come down to a matter of personal preference. Can everybody that's interested please give their input and then we can take it from there .....
