### ISSUE TITLE
[0.9.2] Replace selected text with pasted text causes exception 

### ISSUE THREAD

**Issue by xweichen** [FXMisc/RichTextFX#788]
Replace selected text with pasted text causes exception aslo happen in 0.9.2

test steps：
1、input a\nb\nc
![2018-11-26_235755](https://user-images.githubusercontent.com/21127772/49025767-502a1d00-f1d7-11e8-8158-35dc9a3e6410.png)
2、ctrl+a select all and ctrl+c to copy all
3、select from end to start，select c\nb and ctrl+v
![2018-11-27_000129](https://user-images.githubusercontent.com/21127772/49026022-d2b2dc80-f1d7-11e8-8258-65c84faf1f60.png)
4、ctrl+a select all and ctrl+v

exception like this：

Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: [1, 0) is not a valid range within [0, 3)
	at org.reactfx.util.Lists.checkRange(Lists.java:128)
	at org.reactfx.util.Lists.checkRange(Lists.java:123)
	at org.reactfx.util.FingerTree$Branch$1.subList(FingerTree.java:489)
	at org.reactfx.collection.MaterializedListModification.lambda$0(MaterializedListModification.java:30)
	at org.reactfx.util.Tuple2.map(Tuple2.java:31)
	at org.reactfx.collection.MaterializedListModification.trim(MaterializedListModification.java:23)
	at org.fxmisc.richtext.model.GenericEditableStyledDocumentBase$ParagraphList.lambda$observeInputs$0(GenericEditableStyledDocumentBase.java:46)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$0(NotificationAccumulator.java:134)

**Comment by Jugen** [comment]
@xweichen thanks for reporting.

Observations I've made so far is that the exception only happens under the following conditions:
1. Two successive pastes with no edits in between
    (if edited then ctrl+z back to this point restores the exception condition)
2. The first paste must be at the very end of the document
3. The second paste must be to replace all text

**Comment by Jugen** [comment]
The following code produces the reported exception:

    String test = "a\nb\nc";
    area.replaceText( test );
    area.appendText( test +"d" );
    area.replaceText( test +"d" );

or

    String test = "a\nb\nc";
    area.replaceText( test );
    area.insertText( 0, test +"d" );
    area.replaceText( test );

**Comment by samhutchins** [comment]
This is still a problem in 0.10.3

```java
import org.fxmisc.richtext.CodeArea;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

public class FooBar
{
    public static void main(String[] args)
    {
        Application.launch(MainWindow.class);
    }

    public static class MainWindow extends Application
    {
        @Override
        public void start(final Stage primaryStage)
        {
            final CodeArea area = new CodeArea();

            final Button button = new Button("Throw exception");
            button.setOnAction(e ->
            {
                String test = "a\n";
                area.replaceText( test );
                area.appendText( test +"d" );
                area.replaceText( test +"d" );
            });


            final BorderPane root = new BorderPane(area);
            root.setBottom(button);
            final Scene scene = new Scene(root, 600, 400);
            primaryStage.setScene(scene);
            primaryStage.show();
        }
    }
}
```

If you press the "Throw exception" button, it performs the same steps as outlines by @Jugen [here](https://github.com/FXMisc/RichTextFX/issues/788#issuecomment-442049576) and it throws the same exception. I can also reproduce by hand

**Comment by Jugen** [comment]
I've checked into this with JRE 8 and JRE 11 using your code with 0.10.3 and it unfortunately doesn't throw the exception ?  Could you double check that your classpath is indeed using the latest RichTextFX jar and if so then could you please provide additional information that might help.

**Comment by samhutchins** [comment]
My apologies, I guess my IDE didn't pickup the change in the `pom.xml` or something was cached, I can't reproduce with 0.10.3
