### ISSUE TITLE
Drag-and-drop between multiple StyledTextAreas

### ISSUE THREAD

**Issue by alesp** [FXMisc/RichTextFX#796]
It appears that dragging text from one StyledTextArea to another doesn't work. Also, dragging / dropping from another application (e.g. a web browser) to a StyledTextArea doesn't work.

Ability to accept drops from elsewhere can be easily added using setOnDragOver / setOnDragDropped. But I can't figure out how to create a drag. I've tried with setOnDragDetected, setOnSelectionDrag, even addEventFilter... and nothing I tried worked - it also messed drag & drop within the same StyledTextArea.

What is the correct way to implement drag&drops from/to other applications via clipboard? Is it even possible? If not, could this be added in a fututre version? Pretty please. :-)

**Comment by Jugen** [comment]
@alesp, sorry for the delay ....

To do this you need to create an EventHandler for setOnDragDetected, setOnDragOver, and setOnDragDropped. First for **setOnDragDetected** as follows:

    private void dragDetected( MouseEvent ME )
    {
        String selectedText = "";
        Object source = ME.getSource();
        
        if ( source instanceof GenericStyledArea ) {
            selectedText = ((GenericStyledArea) source).getSelectedText();
        }
        else if ( source instanceof TextInputControl ) {
            selectedText = ((TextInputControl) source).getSelectedText();
            // Need to hold down either Ctrl or Shift when initiating
            // the drag otherwise the selected text gets adjusted ?
        }
        
        if( selectedText.length() <= 1 ) return; // Abort if busy selecting
        
        ClipboardContent  content = new ClipboardContent();
        content.putString( selectedText );
        
        Dragboard  board = ((Node) source).startDragAndDrop( TransferMode.COPY_OR_MOVE );
        board.setContent( content );
    }
Then for **setOnDragOver**:

    private void dragOver( DragEvent DE )
    {
        if ( DE.getDragboard().hasString() ) {
            DE.acceptTransferModes( TransferMode.COPY_OR_MOVE );
        }
    }
And lastly for **setOnDragDropped** (also works when dragging text from another application):

    private void dragDropped( DragEvent DE )
    {
        if ( DE.getDragboard().hasString() )
        {
            Object target = DE.getGestureTarget();
            
            if ( DE.getGestureSource() instanceof GenericStyledArea ) {
                GenericStyledArea source = (GenericStyledArea) DE.getGestureSource();
                if ( source == target )  source.deleteText( source.getSelection() );
            }
            
            if ( target instanceof GenericStyledArea ) {
                GenericStyledArea area = (GenericStyledArea) target;
                int insertIndex = area.hit( DE.getX(), DE.getY() ).getInsertionIndex();
                area.insertText( insertIndex, DE.getDragboard().getString() );
            }
            else if ( target instanceof TextArea ) {
                TextArea area = (TextArea) target;
                HitInfo hit = ((TextAreaSkin) area.getSkin()).getIndex( DE.getX(), DE.getY() );
                area.insertText( hit.getInsertionIndex(), DE.getDragboard().getString() );
            }
            else if ( target instanceof TextField ) {
                TextField field = (TextField) target;
                HitInfo hit = ((TextFieldSkin) field.getSkin()).getIndex( DE.getX(), DE.getY() );
                field.insertText( hit.getInsertionIndex(), DE.getDragboard().getString() );
            }
            
            DE.setDropCompleted( true );
        }
    }
_Note_ that if you don't need to drag and drop from/to TextInputControl, TextArea, and/or TextField then you can remove the code sections that refer to each in the above methods. Then use the above methods like so:

    area1.setOnDragDetected( this::dragDetected );
    area1.setOnDragOver( this::dragOver );
    area1.setOnDragDropped( this::dragDropped );

    area2.setOnDragDetected( this::dragDetected );
    area2.setOnDragOver( this::dragOver );
    area2.setOnDragDropped( this::dragDropped );

**Comment by alesp** [comment]
Thank you @Jugen. I tried many such things, but always on Linux (I have Ubuntu 18.04 with Oracle JDK 1.8.0_201).

This code works on Windows 10, but not on Linux. Any ideas?

**Comment by Jugen** [comment]
That's strange ?  Sorry I don't have Ubuntu set up, so can you maybe describe what happens ?
For starters are each of the three methods actually being called when appropriate ?
Can you maybe try running it with a debugger and seeing what is happening ?

**Comment by alesp** [comment]
Ugh, sorry. I had disableGrab=true for debugging and that was the reason it wasn't working.

It's working perfectly now, thank you!
