### ISSUE TITLE
How to have a scrollbar ?

### ISSUE THREAD

**Issue by bytecod3r** [FXMisc/RichTextFX#798]

**Comment by Jugen** [comment]
In code use:  `VirtualizedScrollPane scroll = new VirtualizedScrollPane(area);`
and in FXML use:

    <VirtualizedScrollPane>
       <content>
           <StyleClassedTextArea fx:id="richtext" wrapText="true" />
       </content>
    </VirtualizedScrollPane>

**Comment by bytecod3r** [comment]
Thanks, I dont understand your reply, I cant fit your code anywhere in your FXML. 

Here is my FXML.

```
<?xml version="1.0" encoding="UTF-8"?>

<?import javafx.scene.control.TextField?>
<?import javafx.scene.layout.BorderPane?>
<?import javafx.scene.layout.StackPane?>

<BorderPane fx:id="borderPane1" xmlns="http://javafx.com/javafx/10.0.1" xmlns:fx="http://javafx.com/fxml/1" fx:controller="TerminalController">
    <bottom>
        <BorderPane BorderPane.alignment="CENTER">
            <center>
                <StackPane maxHeight="33.0" minHeight="33.0" prefHeight="33.0" prefWidth="598.0" BorderPane.alignment="CENTER">
                    <children>
                        <TextField fx:id="commandTextField" maxHeight="6.0" onKeyPressed="#commandKeyPressed" prefHeight="6.0" prefWidth="598.0" promptText="Enter command" />
                    </children>
                </StackPane>
            </center>
        </BorderPane>
    </bottom>
</BorderPane>

```

And the below is how I initiated RichTextFX.

```
FXMLLoader loader = new FXMLLoader(getClass().getResource("TView.fxml"));
Parent tab = loader.load();
TController controller = loader.getController();
CodeArea codeArea = controller.loadControls();
StackPane stackPage = new StackPane(new VirtualizedScrollPane<>(codeArea));
controller.borderPane1.centerProperty().setValue(stackPage);
tabTerminal.setContent(tab);
```
and my controller.loadControls() just return a codeArea.

controller class:
```
private CodeArea codeArea;
.....
public CodeArea loadControls() {
        return codeArea;
    }
```

Could you please point out where the scrollbar should be?
Thanks!

**Comment by Jugen** [comment]
The scrollbars only become visible when needed. You can simplify your RichTextFX initiation by adding it to your FXML like so:

    <?xml version="1.0" encoding="UTF-8"?>
    <?import javafx.scene.control.TextField?>
    <?import javafx.scene.layout.BorderPane?>
    <?import javafx.scene.layout.StackPane?>
    <?import org.fxmisc.flowless.VirtualizedScrollPane?>

    <?import your.packageName.CodeArea?>

    <BorderPane fx:id="borderPane1" xmlns="http://javafx.com/javafx/10.0.1" xmlns:fx="http://javafx.com/fxml/1" fx:controller="TController">
        <center>
            <VirtualizedScrollPane>
               <content>
                   <CodeArea fx:id="codeArea" />
               </content>
            </VirtualizedScrollPane>
        </center>
        <bottom>
            <BorderPane BorderPane.alignment="CENTER">
                <center>
                    <StackPane maxHeight="33.0" minHeight="33.0" prefHeight="33.0" prefWidth="598.0" BorderPane.alignment="CENTER">
                        <children>
                            <TextField fx:id="cTextField" maxHeight="6.0" onKeyPressed="#cKeyPressed" prefHeight="6.0" prefWidth="598.0" promptText="Enter command" />
                        </children>
                    </StackPane>
                </center>
            </BorderPane>
        </bottom>
    </BorderPane>

If you do this then remember to add the FXML annotation to `private CodeArea codeArea;` in your controller and to correctly specify CodeArea package import details in the above FXML.

**Comment by bytecod3r** [comment]
Thanks a lot.

Another question, how to automatically scroll to the end of content?

**Comment by Jugen** [comment]
Try `codeArea.requestFollowCaret();`

**Comment by bytecod3r** [comment]
Thanks
