### ISSUE TITLE
Override texts in CodeArea

### ISSUE THREAD

**Issue by jld3103** [FXMisc/RichTextFX#800]
## Expected Behavior
I want to override the texts displayed in a CodeArea. Something like this:
"test" gets displayed as "123"

## Actual Behavior
It isn't possible to override the text which gets displayed.

## Environment info:

- RichTextFX Version: 0.9.2

<hr>

## Desired Feature
I want to override the texts which gets displayed in a CodeArea.
Edit: And the highlighting should highlight the displayed text and not the original text

**Comment by Jugen** [comment]
You could do this by using custom objects. Have a look [here](https://github.com/Jugen/StyledSegmentTextArea) (starting with CustomSegmentDemo.java) to see.

You could then use [TextSegment](https://github.com/Jugen/StyledSegmentTextArea/blob/master/lightware/richtext/TextSegment.java) (for ordinary text) and [LabelSegment](https://github.com/Jugen/StyledSegmentTextArea/blob/master/lightware/richtext/LabelSegment.java) for where you want to override the text displayed. You would achieve that by supplying LabelSegment with a special object that you would create where you override toString() to display the alternative text.
