### ISSUE TITLE
Custom editor, multiple custom objects.

### ISSUE THREAD

**Issue by Taenebron** [FXMisc/RichTextFX#803]
Hello!
First of all, thanks for your work on RichTextFX!

I'm quite new in RichTextFX and programming in complicated structure. I try to get functionalities that may be similar to Word. I'm using GenericStyledArea and RichEditor/Hyperlink demo as examples. However I'm stuck since some while: I'm not sure how I can and how I should implement multiple custom objects at once in one editor. I want to implement functions like LinkedImage, Hyperlink (from examples) and inline emoji. However, all demos and wiki articles are a bit unclear in that area to me: they use only one object at once. 
Also I want to add even more text based objects to interact with program: link that opens linked file in new tab, and dynamic text content that may be easy updated via reference.

So my questions are: how I can implement support for multiple objects at once in my case? Some examples or advice how I can proceed? Thanks!

**Comment by Jugen** [comment]
Hi @Taenebron, yes it gets a bit confusing/complicated extending the examples/demos to work with multiple custom objects. Have a look [here](https://github.com/Jugen/StyledSegmentTextArea) (starting with _CustomSegmentDemo.java_) to see an alternative way of doing it that should make it easier.

The basic idea is to have a _GenericStyledArea_ that takes [AbstractSegment](https://github.com/Jugen/StyledSegmentTextArea/blob/master/lightware/richtext/AbstractSegment.java)s which you extend for each of the custom objects you want. Take a look at [TextSegment](https://github.com/Jugen/StyledSegmentTextArea/blob/master/lightware/richtext/TextSegment.java) (for ordinary text) and [LabelSegment](https://github.com/Jugen/StyledSegmentTextArea/blob/master/lightware/richtext/LabelSegment.java) as examples to see how.

**Comment by Taenebron** [comment]
Thanks, it will surly help! Now I see the concept more clearly.

I just got weird, long NPE while I was running your example. It only happens when I'm copying and pasting objects from the editor.

[ErrorLog.txt](https://github.com/FXMisc/RichTextFX/files/2944154/ErrorLog.txt)

**Comment by Jugen** [comment]
What version of RichText are you using ? 
If not 0.9.3 then please try that and let me know.

**Comment by Taenebron** [comment]
I used 0.9.2 first, then I moved to 0.9.3 but same error occurred from what I remember. I simply replaced jars (with dependencies) in IntelliJ libraries. I checked some hours ago, so I would do it again just to make sure.

**Comment by Jugen** [comment]
Ok, found the problem and fixed it in [StyledSegmentTextArea ](https://github.com/Jugen/StyledSegmentTextArea/blob/fe1cc1d2df4dcdba5c33dcb103922eeb9ba29e56/lightware/richtext/StyledSegmentTextArea.java#L15) where _initialSegStyle_ was null and shouldn't be.

**Comment by Taenebron** [comment]
Thank you so much, your example helped a lot and spared a lot of my time! :)
I'm very happy how it goes for now. 

I have one additional question if it is ok: How I can override mouse behavior for these objects to make them more convenient? For example: normal / special cursor type on mouse-over and skipping caret move when object itself is clicked. I checked if it can be forced via "setOnMouseEntered" or similar, but it won't work simply as that.

**Comment by Jugen** [comment]
I think you would do that in the custom objects `public Node createNode( String style )` method. For example [here](https://github.com/Jugen/StyledSegmentTextArea/blob/fe1cc1d2df4dcdba5c33dcb103922eeb9ba29e56/lightware/richtext/LabelSegment.java#L17-L24). 

You may need to add your own custom methods (e.g. `setCursor` to _LabelSegment_ to hold the type of cursor you want) and then use that when createNode is called.

**Note:** the displayed object/node is created lazily. That means that `createNode` is only called when the object is going to be displayed (that is be visible). Or to put it another way `createNode` is not called if the object is far down in a document (that is not visible onscreen). This is done in order to save memory, so don't be tempted to create the Node (e.g. the Label) and assign it to a private field in the class.

**Comment by Taenebron** [comment]
Awesome! My current biggest problem is scrolling that I fight with since some while. It probably should be assigned as separate issue, but I want to avoid spamming for every single bigger/smaller issue.

I want to get rid of all vertical scrolling functions in my editor. Why? I want to get to specific structure: feel and functionality similar to [wiki](https://en.wikipedia.org/wiki/Oracle_Corporation) websites without rewriting a lot of RichTextFX to insert multiple layouts into it. 

My all layout components are inserted in Scrollpane, and some additional objects like VBox and HBox. Richeditor is inserted in Page object with fixed width, but scaling height. Editor and page scales depending on height and amount of text lines. I did some magic here, based on similar topic. It mostly works good, editor gets longer - internal scrolling functions are mostly cheated as size is increasing on demand.

However in some cases, GenericStyledArea scrolling still works. I have problems in situations like pasting a lot of content repeatably (out of area of Scrollpanes position), because some internal functions of GenericStyledArea scrolling kick in, and it's invisible scrolling happens. Currently I have no idea where to find and how to stop more of internal scrolling behaviors of GenericStyledArea. 

I was successful in removing GenericStyledAreas scrolling bars visually, and I send mouse scrolling information over to my main Scrollpane via addEventFiler (which also makes GenericStyledArea internal scrolling uncontrollable via mouse). It was thanks to [this thread](https://github.com/FXMisc/RichTextFX/issues/674). However, it seems that some functionalities are harder to hide or remove.

I know that sounds complicated, but said in simple way: I want to get rich text editor in pages (via inserting GenericStyledArea and expanding it), similar to Words system - but as one infinite page. Problem is that internal scrolling functionalities of GSA are problematic.
If it will help, I can attach more material. 
Clever ideas how to cheat this system or I'm doomed? It would be lovely to get GenericStyledArea without it's own internal scrolling system, even if use-cases for it may be rare. :D

**Comment by Jugen** [comment]
Note that the general behavior is that when the text area is changed programmatically no scrolling will occur, however when a user types or pastes into a text area then scrolling occurs to the where the change happened. See [Auto-Scrolling to Caret](http://fxmisc.github.io/richtext/javadoc/0.9.1/org/fxmisc/richtext/GenericStyledArea.html) section in GenericStyledArea doc.

To prevent this from happening override [GenericStyledArea.requestFollowCaret()](https://github.com/FXMisc/RichTextFX/blob/c1f702b6855a943a3c4d4883d03d53883ed12d63/richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java#L1093) in _StyledSegmentTextArea_ and just call `requestLayout()` like so:

    @Override
    public void requestFollowCaret() {
        requestLayout();
    }

**Comment by Taenebron** [comment]
I fixed everything and solutions work like wonder now, but I found one issue after a long time. I'm still avoiding creating new issue, it is related.

My solution that I posted sadly suffers from one drawback I didn't predict. When I'm showing whole GenericStyledArea (in another ScrollPane) with alot of content, responsiveness and performance of GenericStyledArea falls slightly. This is visible mostly when selecting text, where GPU usage even jumps to 30% and processor by few. This effect seem to diminish after longer time of repeating the action - I guess that application "warms up" in some way. My hypothesis is that whole text area is rendered/used in calculations, not only visible one. Resizing of GenericStyledArea itself doesn't seem to affect performance.

This effect is **not** present when text area uses it's own, default scrolling system (fixated on 800 height). So my guess is optimization of calculations.

Anything I can do? :(

**Comment by Jugen** [comment]
Instead of using ScrollPane try using `org.fxmisc.flowless.VirtualizedScrollPane` and see if that improves things.

**Comment by Taenebron** [comment]
Pardon for long wait, but I didn't have much time to test it correctly till recently.

It seems that I can't directly replace ScrollPane with VirtuatlizedScrollPane in my XML/java code as I get errors like: "javafx.scene.layout.AnchorPane cannot be cast to org.fxmisc.flowless.Virtualized"
I need better understanding on how things work here and how I can limit that rendering area so that GenericStyledArea will only render what it needs to render. As mentioned: I guess that ScrollPane is fooling editors own VirtualizedScrollPane area to render all contentents, even if they are not on screen.

Further ideas how to optimize that, somehow limit rendering space of GenericStyledArea itself to only display something in sight of ScrollPane? Or maybe I should take different approach? It seems quite complicated to find out how I can optimize this.

I think it will be best to demonstrate it somehow. This is my current approach:
![image](https://user-images.githubusercontent.com/48281591/57186192-c5162700-6eda-11e9-8fff-8e8f7d4d8649.png)

**Comment by Jugen** [comment]
OK, I see from your diagram now what you are trying to do.
I don't know if there is a simple elegant solution, but maybe you can try the following as next best.

So at the moment you have: ScrollPane(  HBox( GenericStyledArea, VBox? ) )
Instead try: HBox( VirtuatlizedScrollPane( GenericStyledArea ), ScrollPane( VBox ) )

You will then have two vertical scrollbars which you then bind together, so that if you scroll in the one then the other scrolls as well. If the two vertical scroll bars are unsightly then you can set the show vertical scroll bar policy on one of them so that only one scroll bar is displayed.
