### ISSUE TITLE
Can't get CodeArea to display line numbers

### ISSUE THREAD

**Issue by theJaxon** [FXMisc/RichTextFX#805]
In the JavaKeywordsDemo.java file, CodeArea is initialized in the MainApp.java class (it extends Application), i'm using it in my FXMLController.java so currently my code is:
public class FXMLController implements Initializable 
{
    @FXML private CodeArea codeArea;

    @Override
    public void initialize(URL url, ResourceBundle rb) 
    {
        codeArea = new CodeArea();
        codeArea.setParagraphGraphicFactory(LineNumberFactory.get(codeArea));
    }
}

when running, the line numbers aren't displayed.
In the Demo it was initialized in the start function with this line:
Scene scene = new Scene(new StackPane(new VirtualizedScrollPane<>(codeArea)), 600, 400);
now this line is missing from my class as it's not the main class, how can i solve this ? 

i want to use it in a different class , sorry if my question is stupid.

**Comment by Jugen** [comment]
You need to remove the line `codeArea = new CodeArea();` as it should already be defined in your **FXML** file as something like this:

    <VirtualizedScrollPane>
        <content>
            <CodeArea fx:id="codeArea" />
        </content>
    </VirtualizedScrollPane>

Remember to add the FXML import lines for CodeArea and VirtualizedScrollPane, e.g.:
`<?import org.fxmisc.flowless.VirtualizedScrollPane?>`

**Comment by theJaxon** [comment]
That worked, i removed the codeArea = new CodeArea(); line, in the FXMLController i'm now left with just:
public class FXMLController implements Initializable 
{
    @FXML private CodeArea codeArea;

    @Override
    public void initialize(URL url, ResourceBundle rb) 
    {
        codeArea.setParagraphGraphicFactory(LineNumberFactory.get(codeArea));
    }
}

However in the FXML the only import lines added as a result of dragging CodeArea from SceneBuilder are:
<?import org.fxmisc.richtext.CodeArea?>
<CodeArea fx:id="codeArea" layoutX="515.0" layoutY="137.0" prefHeight="223.0" prefWidth="430.0" />

so there was no need for the VirtualizedScrollPane import.
Thank you so much.
