### ISSUE TITLE
CodeArea caretBounds graphic bug

### ISSUE THREAD

**Issue by nashousni** [FXMisc/RichTextFX#812]
Using CodeArea getCaretBounds() method within big scripts makes a blue selection appear.
for example:
The following code: 
**codeArea.textProperty().addListener((observable, oldvalue, newvalue) -> {
    codeArea.getCaretBounds().ifPresent(caretBounds -> {
    });
});**
creates this blue highlight:
![caretBounds_bug](https://user-images.githubusercontent.com/42155465/56137854-f6639d00-5f95-11e9-9484-d24382a2fbf7.png)
 This issue appears in the version **0.9.3** but not in the **0.9.2** version

**Comment by Jugen** [comment]
@nashousni could you please provide more detailed steps and code as I can't replicate the problem with what you have provided so far. Also with which OS and Java version are you experiencing this ?

**Comment by nashousni** [comment]
@Jugen  the issue often occurs within a long script .
**OS** : Fedora release 27 (Twenty Seven)
**JAVA version** : java version "1.8.0_181"
      Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
      Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
**richtextfx** :  <richtextfx.version>0.9.3</richtextfx.version>

**Comment by Jugen** [comment]
@nashousni thanks for the details, could you please try and see if this happens on Windows - then we'll know if it's got something to do with the OS.

If it does happen on Windows then could you please tell me exactly what it is that you do to reproduce the problem - thanks.

**Comment by nashousni** [comment]
@Jugen the same bug also happens on Windows.
Just create a long text  and try to write something in the codeArea (inside). and use the method  **codeArea.getCaretBounds().ifPresent(caretBounds -> {
});**  in your script. you should see this blue highlight

**Comment by Jugen** [comment]
Fixed in PR #819
