### ISSUE TITLE
How to make a Pane follow caret?

### ISSUE THREAD

**Issue by SpyceTewan** [FXMisc/RichTextFX#813]
I want to create a Pane that follows the caret. Using a StackPane, I position my Pane on top of the text area and via `setTranslationX()` and `setTranslationY` I could potentially set it to the same position as the caret. I'm having problem with getting the position of the caret relative to my StackPane (Or to the rich text area). Using the Bounds of the caret doesn't help, because they are relative to the screen's origin.
How would I go about getting the position? Is there a better way to approach this?

**Comment by Jugen** [comment]
You could try something like:

    textArea.caretBoundsProperty().addListener( (ob,old,newVal) -> newVal.ifPresent( screen -> 
    {
        Bounds local = textArea.screenToLocal( screen );
        floatPane.relocate( local.getMinX(), local.getMinY() );
    }));

**Comment by SpyceTewan** [comment]
`relocate()` doesn't seem to work, but `setTranslateX()` and `setTranslateY()` does! Thanks, I got it working.
