### ISSUE TITLE
"successionEnds" method couldn't be resolved in my IntelliJ IDEA

### ISSUE THREAD

**Issue by serim47** [FXMisc/RichTextFX#816]
Can't build this project in IDEA ?

**Comment by serim47** [comment]
I'm not sure if this should ever havae been raised as an issue, it's probably an error from my part, but anyways It would be great if someone could resolve this problem of mine. Here it is, I'm trying to build the project in IDEA using its default build (without Gradle) and I'm getting the prior error, IDEA is saying it couldn't resolve the method "successionEnds"

**Comment by Jugen** [comment]
You are probably missing the **reactfx** library. 
See [here](https://mvnrepository.com/artifact/org.fxmisc.richtext/richtextfx/0.10.0) for RichTextFX 0.10 compile dependencies. You'll need to get all of them.

**Comment by serim47** [comment]
I downloaded the dependencies : ReactFX, flowless, undoFX, wellbehavedFX. but I don't really know how to include them in the java build path in IntelliJ

**Comment by Jugen** [comment]
Sorry I use Eclipse so I don't know how it's done in IntelliJ. Try asking on a forum (e.g. [StackOverflow](https://stackoverflow.com/search?q=IntelliJ))
