### ISSUE TITLE
how can i set style(font,size,color,weight,style) of selected area using set style and just string css style code for codeArea

### ISSUE THREAD

**Issue by sashamironovich** [FXMisc/RichTextFX#820]
i am totally new here so im sorry for that
i mean something like this 

 IndexRange indexRange = codeArea.getSelection();
        codeArea.setStyle(indexRange.getStart(),indexRange.getEnd(),"-fx-font-family: " +this.font+ " ;-fx-font-size: "+currSize+"px; -fx-text-fill: " + color +" ; -fx-font-style: "+style + " ; -fx-font-weight: " + weight  );

**Comment by sashamironovich** [comment]
i mean something like this 


 IndexRange indexRange = textArea.getSelection();
        textArea.setStyle(indexRange.getStart(),indexRange.getEnd(),"-fx-font-family: " +this.font+ " ;-fx-font-size: "+currSize+"px; -fx-text-fill: " + color +" ; -fx-font-style: "+style + " ; -fx-font-weight: " + weight  );

**Comment by Jugen** [comment]
To do it as per your example use an _InlineCssTextArea_ alternatively you can use a _StyleClassedTextArea_ then use _area.**setStyleClass**( start, end, styleclass )_ where styleclass is specified in your css file. 

See [here in the wiki](https://github.com/FXMisc/RichTextFX/wiki/Text-Styles%3A-Inline%2C-Style-Class%2C-and-Custom-Style-Objects) for more info.

**Comment by sashamironovich** [comment]
ok, i am not really into css and that stuff , but as i understand i need to already have some css style to apply , but what if this style was generated in with java code, can i somehow create css style from java class and apply it? or how i need to do this

**Comment by Jugen** [comment]
Then use an `InlineCssTextArea` and call `setStyle` as you showed in your own example.

**Comment by sashamironovich** [comment]
oh6 its working
thank you so much!!!!!<3

**Comment by sashamironovich** [comment]
@Jugen but for some reason the color doesnt change if i do this
```
IndexRange indexRange = textArea.getSelection();
textArea.setStyle(indexRange.getStart(),indexRange.getEnd(),"-fx-font-family: " +font+ " ;-fx-font-size: "+currSize+"px; -fx-text-fill: " + color +" ; -fx-font-style: "+style + " ; -fx-font-weight: " + weight );
```

**Comment by Jugen** [comment]
For color try using `-fx-fill` instead of -fx-text-fill

**Comment by sashamironovich** [comment]
@Jugen you are my hero, thank you so much <3 you are the best
