### ISSUE TITLE
Question: how to change background color for TAB character (\u0009)?

### ISSUE THREAD

**Issue by evgenpatiy** [FXMisc/RichTextFX#824]
Dear developers, I'm really enjoying RichTextFX, but couldn't find a way, how to change background color for tabulation character using CSS? It is pretty easy to do for any char and even for SPACE, but what about \0009? Is it possible? Sorry, didn't find a solution.

**Comment by Jugen** [comment]
Use `-rtfx-background-color` in your CSS instead of the regular _-fx-background-color_ and see if that works.

**Comment by evgenpatiy** [comment]
no success for \u0009 :( for example, \u0020 works ok

**Comment by Jugen** [comment]
Can you please provide some code and CSS to have a look at .... thanks.

**Comment by evgenpatiy** [comment]
Sure! css part very simple:
`.highlight {
   -rtfx-background-color: yellow;
}`

java:

`
private static StyleSpans<Collection<String>> highlight(String text) {
        Matcher matcher = PATTERN.matcher(text);
        int lastKwEnd = 0;
        StyleSpansBuilder<Collection<String>> spansBuilder = new StyleSpansBuilder<>();
        while (matcher.find()) {
            String styleClass = matcher.group("HIGHLIGHT") != null ? "highlight" : null;
            assert styleClass != null;
            spansBuilder.add(Collections.emptyList(), matcher.start() - lastKwEnd);
            spansBuilder.add(Collections.singleton(styleClass), matcher.end() - matcher.start());
            lastKwEnd = matcher.end();
        }
        spansBuilder.add(Collections.emptyList(), text.length() - lastKwEnd);
        return spansBuilder.create();
    }
...
textArea.setCache(true);
        textArea.setEditable(false);
        textArea.setParagraphGraphicFactory(LineNumberFactory.get(textArea));
        textArea.textProperty().addListener((obs, oldText, newText) -> {
            textArea.setStyleSpans(0, highlight(newText));
        });
`

**Comment by Jugen** [comment]
Thanks, I see you're using the same code from the JavaKeywords demo :-)
Can you please post the code section where you construct the PATTERN, as I think the problem might be there.

**Comment by evgenpatiy** [comment]
Yep, piece of code without changes :) Almost same story with pattern:
```
private static final String[] HIGHLIGHT = new String[] { String.valueOf('\u0020'), String.valueOf('\u0009') };
    private static final String HIGHLIGHT_PATTERN = "\\b(" + String.join("|", HIGHLIGHT) + ")\\b";
    private static final Pattern PATTERN = Pattern.compile("(?<HIGHLIGHT>" + HIGHLIGHT_PATTERN + ")");
```

**Comment by Jugen** [comment]
So the problem is with the pattern, specifically with the word boundary token **\\b** which the tabulation character is being recognized/absorbed as. The result then, is that there is no \u0009 character to match.

If you remove the first one, it may behave more according to what you want, like so:
`HIGHLIGHT_PATTERN = "(" + String.join("|", HIGHLIGHT) + ")\\b";`

**Comment by evgenpatiy** [comment]
Wow man, you're wizard! Solved!
Thank you very much!
