### ISSUE TITLE
Ways to speed up jTextArea in java swing when loading a lot of text

### ISSUE THREAD

**Issue by chimco89** [FXMisc/RichTextFX#827]
I'm using JavaSwing for UI. I'm having to put a lot of text inside of a jTextArea; loading anywhere from 500KB to 5MB of text file into the jTextArea
```sh
BufferedReader br = new BufferedReader (new FileReader("filename.txt"));
txtarea.read(br,null);
br.close;
txtarea.requestFocus();
```
but when read filename.txt then append to txtarea is verry slow.
Thanks for any attention in advance!

**Comment by Jugen** [comment]
Hi @chimco89,  you've unfortunately posted to the wrong project.
RichTextFx is a JavaFx component and not the JTextArea Swing component.
