### ISSUE TITLE
Caret Position Error on Wrapped Multiline

### ISSUE THREAD

**Issue by javaware777** [FXMisc/RichTextFX#833]
Often on wrapped multiline texts (such as the one shown below), the caret position is unable to be moved with the mouse along to encapsulate the entirety of the line. The caret position appears, at its maximum to be 1 character off from the actual requested end of line position

![Capture](https://user-images.githubusercontent.com/46385754/62016462-561a3880-b180-11e9-9990-7c05314d3133.PNG)

This was produced using the RichTextDemo

**Comment by javaware777** [comment]
This was produced using the RichTextDemo

**Comment by Jugen** [comment]
Does this behavior only happen with version 0.10.x using Java 9 or higher, and only on short lines ?

**Comment by javaware777** [comment]
Java version: 10.0.2
RichTextFX: 0.10.1

**Comment by javaware777** [comment]
Can we expect a new release soon with this fix in it? This bug is quite major for rich-text editing

**Comment by Jugen** [comment]
Yes, I'll try and have the new release out by the end of next week.

**Comment by Jugen** [comment]
Just a note to say I haven't forgotten and to apologize for the delay, but I wanted to include some other things in this next release as well. Sorry that I didn't keep my original deadline.

**Comment by Jugen** [comment]
RichTextFX 0.10.2 has been released with this fixed.
