### ISSUE TITLE
Question: can I have a more detailed example of dynamic highlighting mechanism?

### ISSUE THREAD

**Issue by edubolis** [FXMisc/RichTextFX#835]
Hi.
I have a small java code editor as a script window inside my application and I wish to highlight the names of classes, interfaces, constants, etc, of my API and it's instances created by user. I read the issue "Dynamic keyword highlighting" (#147) but I was unable to understand how to use it. So, I wish to ask a more detailed or full example, if possible.
Thanks.

**Comment by Jugen** [comment]
Sure, have a look at the [JavaKeywordsDemo](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/JavaKeywordsDemo.java).

**Comment by edubolis** [comment]
Thanks for your reply, but I had already seen and used this example for highlighting static items (keywords, comments ...) But what I need to do is during program execution. If the user creates an object from a class of my API, I would like to mark it automatically. The question I quoted (# 147) says how to do it but not enough for me to know how to turn it into functional code.

**Comment by Jugen** [comment]
I suppose the tricky part is how to get the `ObservaleValues` if you haven't done this before and you don't know about the [JavaFX Bindings helper API](https://docs.oracle.com/javase/9/docs/api/index.html?javafx/beans/binding/Bindings.html) ( javafx.beans.binding.Bindings).

So I assume you don't have a problem with the first step as given:

``` java
private static final ObservableList<String> KEYWORDS = FXCollections.observableArrayList(
    // ...
);
```

The next step is where the Bindings helper API is your friend using the _createStringBinding_ method:

``` java
private static final ObservableValue<String> KEYWORD_PATTERN = Bindings
.createStringBinding( () -> "\\b(" + String.join("|", KEYWORDS) + ")\\b", KEYWORDS );
```
Just in case this is unfamiliar to you what's happening here is that everytime the KEYWORDS list changes the given lambda function will be executed to regenerate the value of KEYWORD_PATTERN.

Then do the same for PATTERN but now we use the _createObjectBinding_ method instead:

```java
private static final ObservableValue<Pattern> PATTERN = Bindings.
createObjectBinding( () -> Pattern.compile( 
    "(?<KEYWORD>" + KEYWORD_PATTERN.getValue() + ")"
   +"|(?<PAREN>" + PAREN_PATTERN + ")"
    // ...
), KEYWORD_PATTERN );
```
Note that we are using KEYWORD_PATTERN.**getValue**() now, and that you'll need to do the same for PATTERN in the _computeHighlighting_ method of the demo.

Finally in the demo's start method, add a listener to PATTERN to trigger highlighting when it changes:

```java
PATTERN.addListener( (ob,ov,nv) -> codeArea.setStyleSpans(
   0, computeHighlighting( codeArea.getText() )
));
```
And that`s it, now every time a word is dynamically added or removed from the list the highlighting will be recomputed.

**Comment by edubolis** [comment]
Thanks a lot.
I don't implemented it yet, but now I understand how it works. So, I guess I will have no troubles with this anymore.
