### ISSUE TITLE
ViewActions.getCharacterBoundsOnScreen returning NaN for minX/minY/maxX/maxY

### ISSUE THREAD

**Issue by garybentley** [FXMisc/RichTextFX#838]
I am using a custom paragraph graphic factory with a GenericStyledArea, the factory is displaying icons in the "margin" based upon positions within the text.  So a position of 0 will show an icon against the first line of text.

However when the margin is first rendered it is unable to find the correct position because ViewActions.getCharacterBoundsOnScreen is returning:

`BoundingBox [minX:NaN, minY:NaN, minZ:0.0, width:NaN, height:NaN, depth:0.0, maxX:NaN, maxY:NaN, maxZ:0.0]`

However the javadoc comment for that method says it should return the bounds or null.

The margin is able to find the correct position when the margin is re-rendered later (if the view is scrolled and the margin disappears then comes back into view) and the icons display.  

My question is how do I get around the first render issue?

My code is roughly doing the following (not the actual code):

```
area = new GenericStyledArea().insertText(0, someText);
area.setParagraphGraphicFactory(para ->
{
    return new Pane()
    {
         @Override
         protected void layoutChildren()
         {
               items.stream ().forEach(it -> area.getCharacterBoundsOnScreen(it.position); );
         }
    }    
});
```

**Comment by Jugen** [comment]
I did some tests and it appears that this happens if `new GenericStyledArea().insertText` is called before the Stage that contains the TextArea is showing. So try showing your Stage first and only after that call `insertText`

**Comment by garybentley** [comment]
Yes that worked, thanks.
