### ISSUE TITLE
How to force a re-layout of the area or why do I have to create a new style object to have it apply?

### ISSUE THREAD

**Issue by garybentley** [FXMisc/RichTextFX#839]
I'm currently using [RichTextDemo.java](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext/RichTextDemo.java) and it uses [TextStyle.java](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext/TextStyle.java) for styling of the text.  I've changed the example in my code to just update the current StyleSpans instead of creating new TextStyles, the styles are being applied but the view is not repainting to display the change.  I have to scroll the area to get the updated styles displayed in the view.

Example code:

```
    private void updateStyleToAll(Function<TextStyle, TextStyle> updater)
    {

        StyleSpans<TextStyle> styles = this.getStyleSpans(0, this.getText ().length());
        StyleSpans<TextStyle> newStyles = styles.mapStyles(style -> updater.apply(style));
        this.setStyleSpans(0, newStyles);
}
```

If, as in the RichTextDemo example, I create new TextStyle objects then the styles are immediately applied (implying a listener on an ObservableList) however I'd like to avoid the overhead of having to create new objects all the time.  Is this possible or am I stuck with creating new objects?

Or, how can I force a repaint of the area to make the updated styles apply?  (I tried requestLayout, layout and setNeedsLayout but nothing works)

**Comment by Jugen** [comment]
To force a repaint of the area to make the updated styles apply you can clear the previous style before applying the new. Using your code above it would look something like:
```java
private void updateStyleToAll( Function<TextStyle,TextStyle> updater )
{
    StyleSpans<TextStyle> styles = getStyleSpans( 0, getText().length() );
    StyleSpans<TextStyle> newStyles = styles.mapStyles( style -> updater.apply(style) );
    clearStyle( 0, getText().length() );
    setStyleSpans( 0, newStyles );
}
```

**Comment by garybentley** [comment]
Yes that worked, thanks.
