### ISSUE TITLE
In a multi-line paragraph how to highlight the line the caret is on?

### ISSUE THREAD

**Issue by garybentley** [FXMisc/RichTextFX#841]
I'm wanting to have the line the caret is currently on be highlighted.  I've asked this before #611 but a lot has changed since I first asked and now I'm thinking of doing:

1. Add a listener to the caret position.
2. In that listener get the line the caret is current on.
3. Adding a selection with a custom style for the start/end positions of the line.

Would this approach work?

The main issue I can see is that there doesn't seem to be any way to get the text offsets of the start and end of the line.  Is there any way to get those offsets?

**Comment by garybentley** [comment]
I've now implemented this but using a different method.  I'm listening to the caret bounds and then drawing and positioning a Pane behind the area for the bounds position.

Thus:

```
Pane background = new Pane();
Pane highlight = new Pane();
background.getChildren().add(highlight);
GenericStyledArea<?, ?, ?> area = new GenericStyledArea(...);
StackPane sp = new StackPane();
sp.getChildren().addAll(background, area);
area.caretBoundsProperty().addListener((pr, oldv, newv) ->
{
   Bounds b = background.screenToLocal(newv.get());
   highlight.relocate(0, b.getMinY());
   highlight.setPrefHeight(b.getHeight());
   highlight.setPrefWidth(area.getWidth());
});
```

This produces something like the following:

![text-line-highlight](https://user-images.githubusercontent.com/921991/63134322-4ddd4c80-c00c-11e9-93ea-dcb894d84c7a.jpg)

Note: sometimes the caret bounds aren't present.

While this works, it would be nice to have an "in area" method of doing this.  This type of feature is common in writing applications and code editors.

**Comment by Jugen** [comment]
That's a good hack :-)

I've had a look at this and I'm planning on adding the following API to `GenericStyledArea`:
```java
setLineHighlighterColor( Color highlight )
showLineHighlighter( boolean show )
getCurrentLineStartInParargraph()
getCurrentLineEndInParargraph()
```
Any thoughts or comments welcome.

**Comment by garybentley** [comment]
That would be some great additions.  It might be better to have a Paint rather than a Color though, for those who want to do something a little fancier.

The only problem with my workaround is that I'm now seeing this problem #842.

**Comment by Jugen** [comment]
RichTextFX 0.10.2 has been released with this feature.
