### ISSUE TITLE
Bug: Can not put caret at the end of the paragraph

### ISSUE THREAD

**Issue by kuzmenkoGift** [FXMisc/RichTextFX#848]
I renewed RichTextFX version from 0.9.3 to 0.10.1 and find one problem. I am using InlineCssTextArea, and when i trying to move caret to the end of paragraph by mouse click, caret move one symbol to the left.
It is look like this:
![1](https://user-images.githubusercontent.com/28759843/63744274-894b0700-c8a7-11e9-949b-ecb955b4f1ba.png)
 

And, when i go to version 0.9.3, everything work normal. And i was testing this bug, and find out that it is reproducing only if there more than one line in paragraph.

## Environment info:

- RichTextFX Version: 0.10.1
- Operating System: WIndows, Linux, MacOS
- Java version: 11

**Comment by Jugen** [comment]
Thank you for reporting this bug. It has already been [fixed](https://github.com/FXMisc/RichTextFX/pull/834) for the next release.

**Comment by Jugen** [comment]
RichTextFX 0.10.2 has been released with this fixed.
