### ISSUE TITLE
NavigationActions uses the default locale for navigating text

### ISSUE THREAD

**Issue by garybentley** [FXMisc/RichTextFX#851]
[NavigationActions](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/NavigationActions.java) methods such as wordBreaksBackwards, wordBreaksForwards and so on use:

`BreakIterator.getWordInstance()`

which uses the default jvm locale but the text may not be written in that locale, for instance I know of many writers who are not native English speakers who write in English.  It would be good to be able to specify the locale for the iterators used.  Even better it would be good to be able to mark a section of text as using a specific locale, there are writers who write in multiple different languages.

The locale setting would need to be on a per area basis since there is no guarantee that the text for all areas in a jvm would be using the same locale.

**Comment by shoaniki** [comment]
More generally, it would be good to be able to just modify the word break rules for a text area.  There are some things that need content awareness: for example, in a CodeArea, "5.0" should be a single word but "foo.bar" really should be two in most cases.  And it would be good to be able to handle things like in some IDEs where "CodeArea" itself would be treated as two words.

I can probably work around this by overriding all the affected methods, but it's not trivial when I don't understand how it all interacts!

**Comment by Jugen** [comment]
Hi @shoaniki  to modify the word break rules just override the the following methods:
```java
public void wordBreaksBackwards( int boundaryCount, SelectionPolicy policy ) { ... }
public void wordBreaksForwards( int boundaryCount, SelectionPolicy policy ) { ... }
```
These first two need to end with something like: `moveTo( paragraph, position, policy );`
Then also override the following if needed:
```java
public void selectWord() {
    CaretSelectionBind<?,?,?> csb = getCaretSelectionBind();
    ...
    csb.selectRange( paragraph, start, paragraph, end );
}
```
Here are some methods that will assist you:
```java
 CaretSelectionBind<?,?,?> csb = getCaretSelectionBind();
 int currentParagraph = csb.getParagraphIndex();
 String paragraphText = getText( currentParagraph );
 int positionInParagraph = csb.getColumnPosition(); 
```
You shouldn't have any problems. If there's a way you think that rules can be specified then we can also explore something like that.

**Comment by Jugen** [comment]
@garybentley I've added `setLocale` and `getLocale` methods.

If locale settings are needed on a per paragraph or sentence basis then make sure that there's some way of storing and retrieving the sentence or paragraph's locale from the text or paragraph's **style**. Then override `getLocale` to access the locale from the style and return it.

**Comment by shoaniki** [comment]
Belatedly: thanks for the advice - can confirm that I have it working now.
