### ISSUE TITLE
Bug: Korean input problem on Mac

### ISSUE THREAD

**Issue by song9063** [FXMisc/RichTextFX#852]
Hi,
RichTextFX is amazing. Thanks to all contributors.
I've got a problem to use the Korean input method on OS X.

When I type a Korean (ex: "한") in the org.fxmisc.richtext.
The RichTextFX displays it to "ㅎㅏㄴ".
but JavaFX's TextArea and TextField are processing it to correctly("한").
The Korean keyboard method has a complexed structure than English.
I don't know how RichTextFX process keyboard input event. If you can solve this problem, Korean developers will make many projects using RichTextFX in Korea.

Thanks.

## Environment info:
- RichTextFX Version: 0.10.2
- Operating System: OS X
- Java version: JavaSE-11

**Comment by Jugen** [comment]
To type the character 한 do you press multiple keys on your keyboard eg: ㅎㅏㄴwhich then combines into one ?  If so is there a key like Alt that you press while typing those keys ?

**Comment by song9063** [comment]
We use the "Shift" key to input some characters. but not for all.
I hope an article from Wikipedia will help you.

[https://en.wikipedia.org/wiki/Korean_language_and_computers](https://en.wikipedia.org/wiki/Korean_language_and_computers)

Thanks.

**Comment by song9063** [comment]
Hi If you guys need a Korean keyboard to solve this problem, I can send it. please feel free to tell me if you want it.

**Comment by xulihang** [comment]
This is for Chinese input methods, but it may help as well: https://github.com/FXMisc/RichTextFX/issues/146

I have tried to input 한 with the windows's default korean input method (typing g, k, s) and it works.

It also works without this workaround but the commited text will not show in the area.
