### ISSUE TITLE
[Unexpected behavior]: Highlighting triggers MouseOverTextEvent.MOUSE_OVER_TEXT_END event

### ISSUE THREAD

**Issue by NickRafy** [FXMisc/RichTextFX#853]
First, thank you for your work! 

I'm an amateur, and this is my first comment here, so please don't judge. 

I combine methods demonstrated in two demo files: TooltipDemo and MultiCaretAndSelectionDemo. Namely, when a tooltip shows an error message, another part of the code is highlighted using `codeArea.setStyle(...)`. This did not work as I expected, because `codeArea.setStyle(...)` triggered  `MouseOverTextEvent.MOUSE_OVER_TEXT_END` event, which hides the tooltip, so the tooltip is never shown. 

I patched this problem by substituting  `MouseOverTextEvent.MOUSE_OVER_TEXT_END` event with the following two events: `javafx.scene.input.MouseEvent.ANY` and `javafx.scene.input.KeyEvent.KeyEvent.ANY`, where in the `MouseEvent.ANY` I do not hide the tooltip if the event is either `MOUSE_EXITED_TARGET` or `MOUSE_ENTERED_TARGET`. Not sure if this will produce any issues later.

Is this behavior designed this way or this is an issue that should be fixed in the RichTextFX package? May be there is a more natural way to deal with it?

**Comment by Jugen** [comment]
I think this is by design, so using MouseEvent and KeyEvent as you have done is the way to go.
However you are more than welcome to post some code for review if you want.

**Comment by NickRafy** [comment]
Thank you, Jugen!
