### ISSUE TITLE
How to force a relayout?

### ISSUE THREAD

**Issue by garybentley** [FXMisc/RichTextFX#854]
I've asked a similar question to this before: #839 but I now have a different use case that I can't get around by setting a style.

In this case I am modifying what is drawn in a paragraph graphic when the user makes a change in the text.  Specifically I am drawing a line in the paragraph graphic to match where the user selected a position in the text.  See the image below:

![edit-marker](https://user-images.githubusercontent.com/921991/66709255-b2feb580-eda3-11e9-96b9-e81e06acb6e6.jpg)

The grey area is the paragraph graphic, the blue line is the "marker" to indicate how far into the text the user has edited.

My issue is that when the user changes the "edit position" I need to also update the marker but the marker is only changed on the next layout pass.  I tried calling "requestLayout" on the area and the paragraph graphic but neither caused another layout.

So any suggestions on how to force a layout?

(Note: I do have a workaround but it involves a nasty removing/adding of a component to the graphic which is FAR from ideal, I'd ideally like to have a proper way of handling this situation, especially since I have a number of use cases that have the same issue.)

**Comment by Jugen** [comment]
Currently the paragraph graphic is only refreshed by RichTextFX if either the paragraph index or paragraph factory changes. The graphic is also refreshed when JavaFX detects a change to the scene graph, which is basically what you are triggering.

So I'm thinking of adding a method that will **_recreate_** a specific paragraph graphic, something like:
`recreateParagraphGraphic( parIdx )` or `refreshParagraphGraphic( parIdx )`

What do you think ? Which method name is preferable ?
Or do you have a different method name suggestion ?

**Comment by Jugen** [comment]
Alternatively you could use `area.setParagraphStyle( parNdx, paragraphStyle )` to trigger a refresh.

**Comment by garybentley** [comment]
Sorry for the delay, it's been a busy week.  I think "recreate" would probably be better since it more closely represents the intent/purpose of the method.

Also, would you be able to add a "getParagraphGraphic(int)" method that will return the current paragraph graphic for a paragraph.  I currently have a convoluted mess of caching and scene watching in place to try and get the current paragraph graphic for a paragraph.  My use case is that the user clicks on something outside of the editor and that will open a popup at the location of a node in the paragraph graphic.  See below.

![item-popup](https://user-images.githubusercontent.com/921991/67651522-29e3a300-f98d-11e9-819f-4d99b0bbfb67.jpg)

In this case the user clicked on "Item 1" in the tree in the left hand pane and the editor jumps to the correct location for the item and then displays a popup next to the appropriate icon.

**Comment by Jugen** [comment]
Could you maybe try this out and see if it works for you ?

**Comment by garybentley** [comment]
Yep they both work well, thanks for adding them.

**Comment by Jugen** [comment]
Great, I've fixed the typos in a new PR.
