### ISSUE TITLE
Cannot input Chinese when using nested swing interface

### ISSUE THREAD

**Issue by yanzhao77** [FXMisc/RichTextFX#858]
````
import javafx.application.Application;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.stage.Stage;
import org.fxmisc.richtext.CodeArea;

import javax.swing.*;

public class test1 extends Application {
    @Override
    public void start(Stage primaryStage) throws Exception {
        JFrame jFrame=new JFrame();

        JFXPanel jfxPanel=new JFXPanel();
        CodeArea codeArea=new CodeArea();
        jfxPanel.setScene(new Scene(codeArea));

        jFrame.setContentPane(jfxPanel);
        jFrame.pack();
        jFrame.setVisible(true);
        jFrame.setSize(600,500);
    }

    public static void main(String[] args) {
        launch(args);
    }
}
````
Cannot input Chinese when using nested swing interface，
It is normal in fxml, and can be input.

**Comment by Jugen** [comment]
It would seem then that either Swing or JFXPanel is interfering with the input to the CodeArea.

I'm sorry but I don't have any ideas to help you :-(

**Comment by yanzhao77** [comment]
Well, let's think about something else.
              \     /
              \\   //
               )\-/(
               /e e\
              ( =T= )
              /`---'\
         ____/ /___\ \
    \   /   '''     ```~~"--.,_
 `-._\ /                       `~~"--.,_
------>|                                `~~"--.,_
 _.-'/ \                            ___,,,---""~~``'
    /   \____,,,,....----""""~~~~````

**Comment by GordonGgx** [comment]
> Well, let's think about something else.

在Fx中可以嵌入swing node 来嵌入swing，为什么要swing来嵌入fx呢？

**Comment by yanzhao77** [comment]
> > Well, let's think about something else.
> 
> 在Fx中可以嵌入swing node 来嵌入swing，为什么要swing来嵌入fx呢？

我的界面主要有swing构成的，所以要这么操作

**Comment by GordonGgx** [comment]
> > > Well, let's think about something else.
> > 
> > 
> > 在Fx中可以嵌入swing node 来嵌入swing，为什么要swing来嵌入fx呢？
> 
> 我的界面主要有swing构成的，所以要这么操作

我的意思是你可以把你的swing界面，嵌入到fx的 swing node中

**Comment by yanzhao77** [comment]
> > > > Well, let's think about something else.
> > > 
> > > 
> > > 在Fx中可以嵌入swing node 来嵌入swing，为什么要swing来嵌入fx呢？
> > 
> > 
> > 我的界面主要有swing构成的，所以要这么操作
> 
> 我的意思是你可以把你的swing界面，嵌入到fx的 swing node中

并没有这么容易，这个界面有一个swing的ui框架，非常重要，没有办法移植，所以只能想别的办法
