### ISSUE TITLE
Is there way to control the size of a tab?

### ISSUE THREAD

**Issue by jeffreyguenther** [FXMisc/RichTextFX#86]
Hi Tomas, 

Is there a way to control the size of the space emit in `CodeArea` when I press <kbd>tab</kbd>? By default, it looks like it is about two tabs in length. Is there any way to change it to spaces?

**Comment by isjns** [comment]
This fix is not sufficient when you're displaying the content of a file in `CodeArea`. If the file contains tabs, those will still be presented as 8 white spaces when the file is presented. Only tabs that you've created yourself in the `CodeArea` will be presented as 4 white spaces.

Is there any solution to this that copes with that scenario as well?

**Comment by JordanMartinez** [comment]
You could via 2 mapping functions. The first maps from model-to-view: given a TAB in the model (the ESD), display N spaces in the view (the STA), where N = user's desired spaces count. The second maps from view-to-model: when user moves the caret around and N spaces are encountered, determine whether those spaces are N literal spaces or whether they represent a tab character, then deal with the movement accordingly. 
As you can see, this would increase complexity in the logic and lead to unexpected bugs if not done properly.

Additionally, you could if you "reinvent the wheel" by designing a move nimble `TextFlow` with that support.

**Comment by abaginski** [comment]
Hi, is there an update on this issue? I can't find the class "EventHandlerHelper" in wellbehavedFX 0.3 :/

**Comment by stevedefazio** [comment]
I know that this is closed, but I wanted to chime in and say that simply by changing to a non-monospace font, you can solve your problem. So before you put too much work into it, look at if you really need that font type.

**Comment by swpalmer** [comment]
This is https://bugs.openjdk.java.net/browse/JDK-8130738

**Comment by swpalmer** [comment]
Now that JavaFX 14 is delivered with https://bugs.openjdk.java.net/browse/JDK-8130738 addressed, can we get an API for this in RichTextFX?

**Comment by Jugen** [comment]
Will look into it. In the meantime you should be able to use the following CSS `-fx-tab-size:` in JavaFX 14.

**Comment by swpalmer** [comment]
@Jugen I've used that CSS successfully for TextExt, but I can't get it to work in a CodeArea. Would you have any idea why that is?

**Comment by Jugen** [comment]
See if this [section](https://github.com/FXMisc/RichTextFX/wiki/RichTextFX-CSS-Reference-Guide#issue-with-styleclassed-based-css-default-styling) in the Wiki helps .... ?

**Comment by swpalmer** [comment]
I still haven't figured out the magic combination, even with that info.  Note also the section about TextFlow CSS is wrong.  There is no ".text-flow" class.  You can change TextFlow using the simple class name, e.g.:  "TextFlow { -fx-tab-size: 4; }" .

It is also worth noting that the ".text" CSS does not work for plain Text nodes. As it hints in the docs, it is for text inside controls,  Text is not a Control, it is a Shape. So "Text { -fx-tab-size: 4;}" works for it, but ".text { -fx-tab-size: 4 }" does not.

I can get tabs to change in plain TextExt instances with "TextExt { -fx-tab-size: 4; }", but that doesn't affect the tab size in any StyledClassedTextAreas.  This may be related to how some attributes for Text doesn't affect Text nodes inside a TextFlow.  You have to set that attribute on the TextFlow for it to work.  As the docs for TextFlow state: "When a Text node is inside of a TextFlow, some of its properties are ignored."

**Comment by swpalmer** [comment]
Note that what does work is "* { -fx-tab-size: 2; }", but seeing as that effects tabs everywhere in the UI, I still want to find the correct selector.

**Comment by swpalmer** [comment]
Ah... "ParagraphText { -fx-tab-size: 4 }"  I had to look above the section you linked, as I new about TextExt, but I missed that TextFlow was extended as ParagrahText.  Sorry for the noise.

**Comment by blaze-centurion** [comment]
Can you please share the css of changing the tab size. Because nothing works for me. I mean, I have tried to change the tab size with all the selector which you have mentioned, like - ParagraphText, TextExt, TextFlow, but none of them worked 😭😭 . So can you share your css 🙏.

**Comment by swpalmer** [comment]
ParagraphText {
              -fx-tab-size: %s;
            }

**Comment by blaze-centurion** [comment]
Thank you for your respond @swpalmer. But still this code is not working for me. Is there any other method to change the tab size in StyleClassedTextArea.

**Comment by swpalmer** [comment]
@blaze-centurion I suggest asking on stackoverflow where you can go in to more detail.

**Comment by blaze-centurion** [comment]
I think you are right. Btw thank you for your help.

**Comment by mat4pat** [comment]
i added the following line to my css file, and it worked:

.paragraph-text {
    -fx-tab-size: 4;
}

Best of luck!
