### ISSUE TITLE
Question: Is there a way to add default Undo,Redo,Cut,Copy,Paste,Select All context menu? 

### ISSUE THREAD

**Issue by ameti** [FXMisc/RichTextFX#861]
I am using a custom class extending GenericStyledArea. I need the default context menu of TextArea and currently I created a new context menu and used the UndoManager for undo/redo, but I feel like there is some better way to do it.

**Comment by Jugen** [comment]
The way you are doing it is the way to do it. :-)

**Comment by ameti** [comment]
Ah okay.. thnx. I thought since there are already functions for those in ClipboardActions I was missing something.
