### ISSUE TITLE
How to apply style so that subsequent text is using it?

### ISSUE THREAD

**Issue by garybentley** [FXMisc/RichTextFX#864]
I am trying to set the text style (using GenericStyledArea) such that text that follows will inherit/use that style.

To set some text as bold I'm doing:

 ```java
   private void toggle(Consumer<TextStyle> mixin)
    {
        IndexRange r = this.getSelection();
        this.setStyleSpans(r.getStart(), this.getStyleSpans(r).mapStyles(ss ->
        {
            TextStyle _s = new TextStyle(ss);
            mixin.accept(_s);
            return _s;
        }));
    }

    public void toggleBold()
    {
        IndexRange r = this.getSelection();
        TextStyle s = this.getStyleAtPosition(r.getStart());
        boolean t = !s.isBold();
        this.toggle (_s -> _s.setBold(t));
    }
```

This code will let me bold a piece of selected text but not set the style to be used for the text that follows the style change, except when I apply the bold at the start of an empty paragraph.

The question is, how do I set the style so that text that follows it will use the style?

The image below hopefully highlights what I mean.

![style-change](https://user-images.githubusercontent.com/921991/68553897-99b75a80-0470-11ea-9348-e3b9337bf7e1.jpg)

**Comment by Jugen** [comment]
So I've spent some time looking into this and come up with the following:

There's a method `setUseInitialStyleForInsertion( boolean )` which when switched on currently uses whatever the initial text style was set to via the GenericStyledArea constructor.

There's also a `getInitialTextStyle()` method but **no** `setInitialTextStyle( style )` as for some reason the initial style is marked as **final** ?

So either the initial style object needs to be mutable or a `setInitialTextStyle( style )` method needs to be added and the final modifier removed. The latter being preferred I think.

Then to set the style so that any text that follows will use that style we do the following:
````java
   TextStyle theStyle = .....
   area.setInitialTextStyle( theStyle );
   area.setUseInitialStyleForInsertion( true );
````
And to switch it off a listener is added to the cursor with something like:
````java
   area.caretPositionProperty().addListener( (ob,ov,nv) ->
   {
       area.setUseInitialStyleForInsertion( false );
       area.setInitialTextStyle( DEFAULT_STYLE );
   }); 
````
Do you think this would be a logical and acceptable way of doing it ?
Any other thoughts ?

**Comment by garybentley** [comment]
I think adding separate "insertion style" methods would probably be best.  If the "insertion style" isn't set then use the current behavior.  Then as the caret moves I can update the insertion style.

So something like:

```
setTextInsertionStyle(S) {}
S getTextInsertionStyle() {}

public void toggleBold(IndexRange r)
{
    if (r.getStart() == r.getEnd()) 
    {
          TextStyle s = new TextStyle(area.getStyleAtPosition(r.getStart()));
          s.toggleBold();
          area.setTextInsertionStyle(s);
    } else { /* set style spans for range */ }
}

area.caretPositionProperty().addListener ((pr, oldv, newv) -> area.setTextInsertionStyle(area.getStyleAtPosition(newv)));
```

Probably need similar methods for paragraph insertion.

I tried modifying the initial text style directly and it decided to style all the unstyled text in a paragraph with the initial style.  So any behavior would need to be limited to insertions only and shouldn't affect any other text.

**Comment by Jugen** [comment]
Please have a quick look at the changes in the PR (it's very simple).
Then if needed propose changes or comment on any concerns.
Thanks

**Comment by garybentley** [comment]
Ok, got this working now with the following code that is here for reference for others.

To begin I have a class called TextStyle that models the styling of the text, I am using GenericStyledArea.

To set the style, say to switch on bold at a location in the text you do:

```
// Get the style of the character currently under the caret.
TextStyle s = area.getStyleAtPosition(area.getSelection().getStart());

// Create a new style object based on the current style (essentially a deep clone).
TextStyle n = new TextStyle(s);

// Update the new style to be bold.
n.setBold(true);

// Switch off using the initial style for insertions.  Can do this once elsewhere if needed.
area.setUseInitialStyleForInsertion(false);

// Set the text insertion style.
area.setTextInsertionStyle(n);
```

The only issue here is that this will set the insertion style for ALL future insertions, so you then need to switch the style off after the insertion has occurred, the area will then default back to using the style at the current location, i.e. inherit the current style.

To switch off the insertion add a caret property listener.

`area.caretPositionProperty().addListener((pr, oldv, newv) -> area.setTextInsertionStyle(null));`
