### ISSUE TITLE
Question: Append text with different style.

### ISSUE THREAD

**Issue by bytecod3r** [FXMisc/RichTextFX#868]
Hi there,

I want to append texts with different style.  E.g. the below code, I want the first "Hello" to be appended in bold, and the second "world" to in Italic, how can I set such styling for each append?
by the way, this library is awesome! 

```
@FXML
private StyleClassedTextArea testTextArea;

void test(){
    testTextArea.appendText("Hello"); //to append Hello in Bold.
    testTextArea.appendText("World"); //to append Hello in Italic.
}
```

I tried looking into other issues and questions by others, but unfortunately didn't find the answer. 

And second question, Which one is using less memory? InlineCssTextArea or StyleClassedTextArea  or CodeArea?

**Comment by Jugen** [comment]
The simplest would be something like:
```java
   int pos = testTextArea.getLength();
   testTextArea.replace( pos, pos, "Hello", Collections.singleton( "bold" ) );
   // Where "bold" refers to a style defined in your CSS file.
```
An alternative way to do it in two steps, is:
```java
   int pos = testTextArea.getLength();
   testTextArea.appendText( "Hello" );
   testTextArea.setStyleClass( pos, testTextArea.getLength(), "bold" );
   // Where "bold" refers to a style defined in your CSS file.
```
With the next release you could also do it like so:
```java
   testTextArea.setUseInitialStyleForInsertion( false );
   testTextArea.setTextInsertionStyle( Collections.singleton( "bold" ) );
   // Where "bold" refers to a style defined in your CSS file.
   testTextArea.appendText( "Hello" );
   testTextArea.setUseInitialStyleForInsertion( true );
```

**Comment by Jugen** [comment]
With regards to which one uses the least memory, it would technically probably be InlineCssTextArea but I think we are talking KiloBytes and not MegaBytes. You'd have to do some tests and see if there is a significant difference with your application.

All three are extended off GenericStyledArea with the only difference being how styling is handled.
So InlineCssTextArea uses pure Strings for styling whereas StyleClassedTextArea style strings are wrapped in a List, hence slightly more memory usage.

**Comment by Jugen** [comment]
I've added the following API for the next release to simplify this:
```java
  append( text, styleClass )
  insert( position, text, styleClass )
  replace( start, end, text, styleClass )
```

**Comment by bytecod3r** [comment]
Hi Jugen, 

Thanks for the reply. having append with style will be awesome!. Do you have any estimation when the next release would be out?

**Comment by Jugen** [comment]
Maybe this week, otherwise next week.
