### ISSUE TITLE
Memory leak/issue while vertical scrolling in CodeArea with LineNumberFactory

### ISSUE THREAD

**Issue by veN1337** [FXMisc/RichTextFX#878]
## Expected Behavior

Scrolling in a CodeArea with a LineNumberFactory as ParagraphGraphicFactory works smoothly without any memory issues even for large single line strings.

## Actual Behavior

When a specific file (swagger-ui-standalone-preset.js) is loaded into the CodeArea, vertical scrolling (eg. just a single click on the right arrow) makes the application use huge amount of memory.

## Reproducible Demo

See attachment: [memleak_sample.zip](https://github.com/FXMisc/RichTextFX/files/3908291/memleak_sample.zip)
Button click loads the "payload.js" file. As soon as you start to scroll vertically the memory usage explodes.

## Environment info:

- RichTextFX Version: 0.10.2
- Operating System: Windows 10
- Java version: 8 and 11

## Additional info

Doesnt happen when you dont set the ParagraphGraphicFactory/LineNumberFactory.
Doesnt happen with multiple lines / when the js file is formatted.
Doesnt happen with a random string as long as the file, but seems to happen with random strings greater than 1 million characters.

Im not very experienced with profiling application but I also attached a JProfiler analysis file/screenshots:
[JProfilerObjects](https://user-images.githubusercontent.com/950466/69915320-fb565d80-144d-11ea-8c5d-5d87ee2de58b.png)
[JProfilerAllocationCallTree1](https://user-images.githubusercontent.com/950466/69915326-fee9e480-144d-11ea-9db6-ced852ff70de.png)
[JProfilerAllocationCallTree2](https://user-images.githubusercontent.com/950466/69915327-00b3a800-144e-11ea-8a13-187fcfc692a8.png)
[JProfilerAnalysis.zip](https://github.com/FXMisc/RichTextFX/files/3908294/JProfilerAnalysis.zip)

After scrolling there are around 7600 flot-arrays which take up 963MB in size and around 5600 int-arrays which take up 490MB in size.
According to the Allocation Callt Tree the root cause ist the method "org.fxmisc.richtext.ParagraphBox.computePrefHeight"

A wild guess is that this is somehow related to some unicode characters which are in the file.

**Comment by Jugen** [comment]
Thank you very much for the thorough feedback I really appreciate it.
I'll have a look and see if I can figure it out ....

**Comment by Jugen** [comment]
So I ran your sample app as you described with Java 8, 9 & 11 and I unfortunately don't get the memory usage that your profiling shows. With Oracle's Java 8 & 9 it uses around 200MB and with [Azul's Java](https://www.azul.com/downloads/zulu-community/) 11 it only uses around 100MB.

The only difference is that I used the latest RichTextFX **0.10.3**, so maybe you can try that.

**Comment by veN1337** [comment]
Thanks for the quick response.

I tried RichTextFX 0.10.3 but still got the issue.
I also used Oracles Java 8 (jre1.8.0_171 & jre1.8.0_231).
For Java 11 I used Oracles Java 11.0.5 and added javafx as a library to the sample project.

Then I tried to use Azul's Java 11, removed javafx as lib and used Azul's JRE FX but the problem got worse. Now the memory usage was around 2,5GB as soon as i press the button to load the .js file. Scrolling makes things worse.

So i compiled the sample manually and ran it from console.
Now i couldn't reproduce it either.

I was using IntelliJ IDEA before and noticed, IntelliJ uses the flag `-Dfile.encoding=UTF-8` when running a java programm. Using this flag when running the sample manually from console gives me the memory problem again.

Can you also reproduce the problem when adding `-Dfile.encoding=UTF-8`?

**Comment by Jugen** [comment]
Yip, when using `-Dfile.encoding=UTF-8` there's a memory issue arising via ParagraphBox.computePrefHeight() as you reported:

> Exception in thread "JavaFX Application Thread" java.lang.OutOfMemoryError: Java heap space
> 	at javafx.graphics/com.sun.javafx.text.TextRun.split(Unknown Source)
> 	at javafx.graphics/com.sun.javafx.text.PrismTextLayout.layout(Unknown Source)
> 	at javafx.graphics/com.sun.javafx.text.PrismTextLayout.ensureLayout(Unknown Source)
> 	at javafx.graphics/com.sun.javafx.text.PrismTextLayout.getBounds(Unknown Source)
> 	at javafx.graphics/javafx.scene.text.TextFlow.computePrefHeight(Unknown Source)
> 	at javafx.graphics/javafx.scene.Parent.prefHeight(Unknown Source)
> 	at javafx.graphics/javafx.scene.layout.Region.prefHeight(Unknown Source)
> 	at org.fxmisc.richtext.ParagraphBox.computePrefHeight(ParagraphBox.java:241)
> 

After doing some experiments it seems that the problem could be in JavaFX's `TextRun.split` method.

Do you explicitly need to use `-Dfile.encoding=UTF-8` as I've read somewhere that apparently 
>"the newer APIs like those in java.nio.file.Files do not use the default charset. The methods in these APIs read or write character streams with charset as UTF-8 rather than the default charset."

**Comment by veN1337** [comment]
Sorry for the late response.

I don't need the `-Dfile.encoding=UTF-8`. But in the real app im not doing file reading at all. Im doing HTTP requests and put the response in a CodeArea.
When there is no charset given in the `Content-Type` header (most of the cases) im using the default charset UTF-8. Of course this leads to the same problem.

Too bad this seems like a JavaFX problem. Guess I will try to find some workaround.

Nevertheless thank you for your efforts.
