### ISSUE TITLE
Getting exception when using GenericStyledArea in a TabPane

### ISSUE THREAD

**Issue by garybentley** [FXMisc/RichTextFX#891]
I'm getting the following exception when using a GenericStyledArea in a TabPane AND I have multiple tabs and switch away from the tab containing the area to another tab then back to the tab with the area.

java.lang.IllegalArgumentException: This ParagraphText is not the parent of the given shape (CaretNode(name=main-caret position=42070 paragraphIndex=482 columnPosition=0 Path[elements=[MoveTo[x=0.0, y=0.0], LineTo[x=0.0, y=29.0]], fill=null, fillRule=NON_ZERO, stroke=0x000000ff, strokeWidth=1.0])):
Expected: ParagraphText@1163381150(paragraph=Par[[]; StyledSegment(segment=com.quollwriter.ui.fx.components.TextEditor$TextSegment@27f55eb2 style=18,Arial Narrow,0xf1d956ff)])
Actual:   ParagraphText@1940940(paragraph=Par[[]; StyledSegment(segment=com.quollwriter.ui.fx.components.TextEditor$TextSegment@27f55eb2 style=18,Arial Narrow,0xf1d956ff)])
        at org.fxmisc.richtext.ParagraphText.checkWithinParagraph(ParagraphText.java:305)
        at org.fxmisc.richtext.ParagraphText.getCaretBounds(ParagraphText.java:244)
        at org.fxmisc.richtext.ParagraphBox.getCaretBounds(ParagraphBox.java:204)
        at org.fxmisc.richtext.GenericStyledArea.followCaret(GenericStyledArea.java:1627)
        at org.fxmisc.richtext.GenericStyledArea.lambda$layoutChildren$41(GenericStyledArea.java:1392)
        at org.reactfx.Suspendable.suspendWhile(Suspendable.java:49)
        at org.fxmisc.richtext.GenericStyledArea.layoutChildren(GenericStyledArea.java:1384)

This only happens when I change the tab back to the GenericStyledArea.  I've switched off anything to do with the focus or the caret in my code.  My own code isn't being touched in this exception.  This seems to be a layout issue.

Any ideas what is going wrong?

**Comment by Jugen** [comment]
Sorry for the delayed response. I also use RichText in multiple tabs but I'm not getting this error.
What version are you using and could you maybe provide more info ?

**Comment by garybentley** [comment]
It's actually stopped doing it now, so it's probably something I'm doing but I've no idea why.  I didn't actually change anything so I've no idea why it's transient.  Because it's not being triggered by my code directly it's very frustrating since I don't know where to start to try and resolve it.

**Comment by Jugen** [comment]
Are you maybe using a/the SNAPSHOT version, because I have recently seen this exception while working on a memory leak PR ..... ?

**Comment by garybentley** [comment]
Yes I am using the snapshot version.  I haven't made any changes to it though so it's the same code as in github.
