### ISSUE TITLE
Example adding custom object to CodeArea

### ISSUE THREAD

**Issue by alienatorZ** [FXMisc/RichTextFX#898]
I would like to add a custom object to a CodeArea. I can see how to do it with a GenericStyledArea but  I cannot see how to do it using CodeArea since it uses String as the generic. 

Thank you

**Comment by Jugen** [comment]
As you have noted CodeArea uses String as the generic, so custom objects cannot be added to it.
So unfortunately you will have to extend GenericStyledArea to create your own custom code area to fit your needs.

If you want to be able to add multiple different types of objects I recommend looking [here](https://github.com/Jugen/StyledSegmentTextArea) (starting with _CustomSegmentDemo.java_) to see an alternative way of doing it that should make it easier.

**Comment by alienatorZ** [comment]
Yea I figured that was the case. Ill extend GenericStyledArea. Thank you so much for your response!
