### ISSUE TITLE
Manipulate RichTextFx

### ISSUE THREAD

**Issue by glllions** [FXMisc/RichTextFX#901]
Hey,
thanks for your great work!!

I am using it for developing a specified html editor. Therefor I need to convert the GenericStyledArea to html and the other way round (using jsoup). Seems simple but as I try to modify the area (like adding paragraphs or styled segments in paragraphs) its not possible cause the lists are implemented as unmodifiable...

Do you have a specific way of modifying the elements?
Hope you can help :)

**Comment by Jugen** [comment]
Can you please provide a short example ("working" code) of what you are trying to do and that show the problem you are having.

**Comment by glllions** [comment]
Hey Jugen,
thx for the quick response! Here is my problem as code example, if you need more let me know (btw. element is a jsoup object)

```
    private void update(GenericStyledArea<ParStyle, String, RichTextFxStyle> genericStyledArea, RichTextFxStyle parentTextStyle, Element element) {
        element.childNodes().forEach((node) -> {
            
            if (node instanceof TextNode) {                
                TextNode castedTextNode = (TextNode) node;                
                String text = castedTextNode.text();
                genericStyledArea.append(text, parentTextStyle);
                
            } else if (node instanceof Element) {                
                Element castedElement = (Element) node;                
                if (HtmlTag.htmlTagOfString(castedElement.tagName()) == HtmlTag.BREAK) {
                    
                    /**
                     * Here's my problem
                     * I need to add a new line.
                     */
                    
                    //1: this was my first intuitive way: simply adding a new paragraph. But this does not work because of the unmodifyable list 
                    genericStyledArea.getParagraphs().add(new Paragraph(ParStyle.EMPTY, SegmentOps.styledTextOps(), "\n", parentTextStyle));
                    
                    //2/3: these two options seem to have no effect at all
                    genericStyledArea.append(new GenericEditableStyledDocument(new Paragraph(ParStyle.EMPTY, SegmentOps.styledTextOps(), "\n", parentTextStyle)));
                    genericStyledArea.getContent().concat(new GenericEditableStyledDocument(new Paragraph(ParStyle.EMPTY, SegmentOps.styledTextOps(), "\n", parentTextStyle)));
                    
                    //4: kind of a work-arround but leads to problems at 'back-converting' to html because '\n' is no new paragraph
                    genericStyledArea.append("\n", parentTextStyle);
                    
                    /**
                     * End of problem.
                     */
                
                } else {
                    update(genericStyledArea, getUpdatedHtmlTagStyle(parentTextStyle, castedElement), castedElement);
                }
            } else {
                log.warn("no action for instances of class: " + node.getClass().getSimpleName());
            }
        });
    }
```

**Comment by Jugen** [comment]
Ok, I think the thing to bear in mind is that "**\n**" is not part of a paragraph but lies between paragraphs. So if you do `area.getParagraphs().get(x).getText();` you'll find that it never contains a "**\n**".

To get an empty paragraph you need to end the previous one with "**\n**" and then add another to end the empty paragraph and start a new one: `area.appendText("\n\n");` The problem with this if I'm not mistaken is that this would look more like `<p>` in HTML than like `<br>`.

Not sure if this is feasible but I think in your case every paragraph ending represents a `<br>`.

**Comment by glllions** [comment]
Hey thanks for the answer!
Yes my main problem was to append a new paragraph... i did it with simply append "\n" (what didn't create a new paragraph), just had to parse for "\n" when converting it back to html. (In my project it the segments of a paragraph do contain "\n").
This kind of workarround worked for my projects requirements.
