### ISSUE TITLE
Blocking UI thread during append of CodeArea

### ISSUE THREAD

**Issue by lanthale** [FXMisc/RichTextFX#905]
I am using the CodeArea to load very big files (line by line). The loading itself is done inside of a javafx Task but I have to call with Platform.runLater the method "textArea.appendText(text)" to add the text to the Codearea.

The appendText method blocks the complete UI thread and I cannot do anything during loading of the file. If I do before calling the method a Thread.sleep(5) the ui is updated but this is not a good practise because I am slowing down the file loading process. I guess the UI thread is flooded with update requests.

Can anybody help me how can I do that without blocking the UI thread with Codearea and appendText() ?

**Comment by Jugen** [comment]
I think the problem is that you are loading the file in a javafx Task. Rather try loading the file in a regular thread, inside of which you call `Platform.runLater( () -> textArea.appendText(text) );` as you are doing now.

Otherwise maybe only update the textArea every 100 lines or 500ms .... ?

**Comment by sirop** [comment]
Hello.
Any possibility that this behaviour (inserting/replacing/appending big files into textArea) improved with JAVA 9 or later JAVA versions?

Thanks.
