### ISSUE TITLE
Does CodeArea support multiple selection ranges?

### ISSUE THREAD

**Issue by adxl** [FXMisc/RichTextFX#906]
Tried to follow [MultiCaretAndSelectionDemo](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/MultiCaretAndSelectionDemo.java), but since I'm using a CodeArea, this doesn't seem to work.

Even with one selection :
```
Selection<String, String, String> selection;
selection = new SelectionImpl<>("selection",currentCodeArea,0,10);
```
Is it possible to select multiple ranges in **CodeArea**? Or am I doing something wrong?

Thanks!

**Comment by Jugen** [comment]
It seems that when the range is specified with the constructor that the selection isn't displayed in the correct location. Use the following workaround in the mean time:
```java
    Selection extra = new SelectionImpl( "extra", codeArea );
    codeArea.addSelection( extra );  // add it first
    extra.selectRange( 29, 38 );  // then set range
```
