### ISSUE TITLE
After undo/redo, new text is inserted at the end

### ISSUE THREAD

**Issue by cengels** [FXMisc/RichTextFX#912]
## Expected Behavior

When a text change is undone or redone, the `selection` should stay where the caret is so that subsequent text insertions originate from the caret position.

## Actual Behavior

When a text change is undone or redone, the `selection` jumps to the end of the document (from what I can tell, neither `caretPosition` nor `anchor` are affected). Subsequent text insertions (if the caret is not manually moved in the meantime) place new text at the end rather than at the caret position.

Note that, from what I can tell, this only occurs on text changes, not style changes.

## Reproducible Demo

Occurs as-is in the latest version (revision c9a002b) of the RichTextDemo.

### Steps:

1. Open the RichTextDemo
2. Write some text, preferably with multiple paragraphs
3. Change some text in a position that is *not* the end (removing or adding characters both works)
4. Undo the change
5. Type another character
6. The new character is inserted at the very end of the document

Might be related to #780 / #785.

**Comment by Jugen** [comment]
Thanks for reporting have started looking into it, will continue next week.

**Comment by Jugen** [comment]
Hi Christopher,
If you can, give this a spin and let me know if there are any problems.
Thanks.

**Comment by cengels** [comment]
Hey @Jugen, thanks for looking into this!

From what I can tell, the problem is indeed resolved. There is one oddity I noticed, however: when undoing a text removal or undoing a style change over a segment of text, the cursor is then placed at the *beginning* of that change segment. The standard behaviour for this kind of an undo change is to conclude the undo operation with the entire range of text being selected, so RichTextFX's behaviour feels a bit strange here.

I do realize, however, that this does not really fall within the purview of this issue. If it were possible to tell whether a change is an undo/redo or a normal text change (as in from a paste), this would definitely be something I would implement on my own, but I don't believe there is any way to distinguish the two, is there?

**Comment by Jugen** [comment]
> If it were possible to tell whether a change is an undo/redo or a normal text change (as in from a paste)

The changes I made are in `UndoUtils` and are only invoked during undo/redo. So you could put something like `area.selectRange( pos, len );` after the following [line](https://github.com/Jugen/RichTextFX/blob/5bcb34a72f4d6b2fcbd78650317c3a7d316dd24c/richtextfx/src/main/java/org/fxmisc/richtext/util/UndoUtils.java#L276) to accomplish what you want.

If I'm not mistaken I think `len` can be negative sometimes so you'll need to experiment and account for that.
