### ISSUE TITLE
Korean / Japanise Text

### ISSUE THREAD

**Issue by wise-coders** [FXMisc/RichTextFX#923]
Typing Korean or Japanise text a special popup is showing on top/right. Look this screenshot.
In this case typing 'wk' results in a single language character.

![image](https://user-images.githubusercontent.com/60284259/79256751-d4427a80-7e88-11ea-989b-52f275e98478.png)

This behavior is different in the standard JavaFx components, like TextArea. Here no pop-up is shown, the character is edited directly in the TextArea.

![image](https://user-images.githubusercontent.com/60284259/79256458-5aaa8c80-7e88-11ea-87fe-c456c954987c.png)

Do you know, can be this changed in RichText area (that typing asian characters is done directly in the editor, not in the pop-up ) _

Also looking in Java, this behavior seems to be related to KeyTyped vs KeyPressed. Do you know how Java handle this ?

**Comment by xulihang** [comment]
Hi, I am working with CJK input methods as well.

See the related issues: https://github.com/FXMisc/RichTextFX/issues/980

**Comment by wise-coders** [comment]
I hope on the latest version this works now fine. We had some fixes. Thank you for closing the issue and for your feedback.
