### ISSUE TITLE
Detect change in textarea

### ISSUE THREAD

**Issue by lanthale** [FXMisc/RichTextFX#925]
I am using CodeArea and just want to detect if the textarea was changed ?

What I have tried and it is not working:
`textarea.plainTextChanges().addObserver((t3) -> {
                System.out.println("event plainTextChanges");
            });
textarea.plainTextChanges().hook((z) -> {
                System.out.println("event key2");
            });
`
How can I detect if the CodeArea has been changed ?

**Comment by Jugen** [comment]
You could use the undo manager like so:
```java
  boolean hasChanges = codeArea.getUndoManager().isUndoAvailable();
```

**Comment by lanthale** [comment]
Thank you for the help. This works very well.
