### ISSUE TITLE
[Question] CodeArea and ScrollEvent

### ISSUE THREAD

**Issue by CreatorEzio214** [FXMisc/RichTextFX#928]
I just started using RichTextFx and I love it. But everyone knows if you start with something new you'll have some questions and so do I. I want the font size to increase when the mouse wheel goes up while holding control and when it goes down the font size should decrease. The only problem I got is getting the state of the mouse wheel.

```
codeArea.addEventFilter(ScrollEvent.ANY, e -> {
	if(e.isControlDown()) {
		if(e.getDeltaX() != 0) {
			fontSize += 2;
			changeFontSize(fontSize, filePane);
		}
		if(e.getDeltaY() != 0) {
			fontSize -= 2;
			changeFontSize(fontSize, filePane);
		}
	}
});
```

How can I check if the mousewheel goes up or down?

**Comment by Jugen** [comment]
Note from the JavaDocs is that `getDeltaY()` returns positive values for up and negative values for down. You can also have a look at the values that `getTextDeltaY()` returns, as an alternative.
