### ISSUE TITLE
Redirect CodeArea Mouse Scoll event capture to Parent

### ISSUE THREAD

**Issue by saulpalv** [FXMisc/RichTextFX#931]
i have some CodeArea inside a scroll pane but when mouse is over CodeArea, the scroll on the ScollPane parent doesn't work, CodeArea is capturing the event, how to redirect scroll event from CodeArea to parent ScollPane?

**Comment by Jugen** [comment]
@saulpalv did you need this for your autoheight issue, if so can we close this then ?
