### ISSUE TITLE
Area not immediately updating with new style, will update if I scroll the area

### ISSUE THREAD

**Issue by garybentley** [FXMisc/RichTextFX#936]
I'm updating a GenericStyledArea to use a new style using the following code:

```
    private void updateTextStyle (Function<TextStyle, TextStyle> updater)
    {

        StyleSpans<TextStyle> styles = this.getStyleSpans (0, this.getText ().length ());
        StyleSpans<TextStyle> newStyles = styles.mapStyles (style ->
        {
            style = updater.apply (style);
            return style;
        });
        this.clearStyle (0, this.getText ().length ());
        this.setStyleSpans (0, newStyles);

    }
```
However the area doesn't get updated with the new style (such as a change to the font color or the font family or size).  The new style is applied when I scroll the area, I presume the paragraph is then being recreated.  The same code applies the initial style to the area and that displays correctly.  

Am I doing something wrong in the code above or is there something else I need to do to force the area to update to the new style?  I have tried a requestLayout but that doesn't do anything.  I've checked that the "newStyles" contains the correct style information.

**Comment by Jugen** [comment]
Sorry for the delayed response. Can you please check and make sure that your `updater.apply( style )` method is returning a **new** TextStyle object and _**not** a modified one_.

**Comment by garybentley** [comment]
Yep thanks, creating new objects mostly solved my issue.

I am having trouble setting the paragraph styles however, I'm doing:

```
        for(int i = 0; i < area.getParagraphs ().size (); ++i)
        {

            Paragraph<ParaStyle, AbstractSegment, TextStyle> p = area.getParagraph(i);
            ParaStyle ps = new ParaStyle (p.getParagraphStyle ());
            ps = updater.apply (ps);
            area.setParagraphStyle (i, ps);

        }
```
But the paragraph style isn't being set on the paragraph, but when I update the text style (using the code I originally set) it also updates the paragraph styles.  I am setting up the paragraph styles initially, before I insert any text, and the paragraph style is getting picked up, just not when I update the style later.

Any ideas what I'm doing wrong with the paragraph styling?

**Comment by Jugen** [comment]
@garybentley sorry for the delayed response. After doing some tests I think that the problem lies with the `ParaStyle.equals` method. You need to make sure that it takes all possible styles/attributes into account when doing an equality test.

Note that the current RichTextFX demo version of `ParaStyle` doesn't do this properly, which I'll fix shortly with a PR.

**Comment by garybentley** [comment]
Yes that fixed it.  I didn't have an equals/hashCode override at all.  Thanks.
