### ISSUE TITLE
appendText(String text) method add text with previously used style by setStyleClass or append(String text,String styleclass) methods 

### ISSUE THREAD

**Issue by logesh0304** [FXMisc/RichTextFX#938]
see the code
```
StyleClassTextArea textarea=new StyleClassedTextArea();
textarea.appendText("no-style");
textarea.append("with-style","error");
textarea.appendText("no-style");
```
i think the output would be (for the style i used bold text)
>  no-style **with-style** no-style

but the actual output is
>  no-style **with-style no style**

it add style to normal that added after this method  .
**insert** and **replace** methods also had this problem.

**Comment by logesh0304** [comment]
I think the problem is with appendText(String text) method. I also tried  
```
output_area.appendText("hello");  
String toappend="hello";  
output_area.appendText(toappend);  
output_area.setStyleClass(output_area.getLength()-toappend.length(), output_area.getLength(), "error");  
output_area.appendText("hello");  
```  
this also produced the same result.
The **appendText** method add text with previously used style

**Comment by Jugen** [comment]
Yeh, from the API it's maybe not what you would expect - but the same methods are used when typing. So when you have styled some text and then start typing with the cursor immediately after the styled text then the newly typed text takes on the current style of the previous text. (Hope that makes sense.)

One way to accomplish what you want is to do the following:

```
textarea.appendText("no-style");
textarea.append("with-style","error");

textarea.setUseInitialStyleForInsertion( true );
textarea.appendText("no-style");
textarea.setUseInitialStyleForInsertion( false );  // Otherwise newly typed text won't use current style
```

**Comment by logesh0304** [comment]
yeah, i agree that.
but, i done the following:  
```
textarea.append("no-style", "none");  
textarea.append("with-style","error");  
textarea.append("no-style", "none");  
```  
where none is a empty style class  
`.none{}`  
it worked well.

**Comment by logesh0304** [comment]
how can i represent **space**  and **new line** in code area.  
i am making a **regexTester** and i want to represent space and new line character with a **background character** or some background representation.  
can codearea support image?  
please, tell me a solution for this.

**Comment by logesh0304** [comment]
This issue is solved. So, I close this issue
