### ISSUE TITLE
Where is 'xml-highlighting.css'?

### ISSUE THREAD

**Issue by DesertCookie** [FXMisc/RichTextFX#940]
I am follwoing the [XMLEditorDemo](https://github.com/FXMisc/RichTextFX/blob/5d64bd7ef211292ec096b5b152aa79ee934e4678/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/XMLEditorDemo.java) to implement an XML editor into my GUI. I cannot seem to find `xml-highlighting.css` using GitHub's search function though.

Where is the stylesheet that was used to achieve the syntax highlighting showcased on the [demo landing page](https://github.com/FXMisc/RichTextFX/tree/5d64bd7ef211292ec096b5b152aa79ee934e4678/richtextfx-demos#xml-editor)?

**Comment by Jugen** [comment]
That's strange ? Look here: https://github.com/FXMisc/RichTextFX/blob/master/richtextfx-demos/src/main/resources/org/fxmisc/richtext/demo
