### ISSUE TITLE
Syntax highlighting default text color? 

### ISSUE THREAD

**Issue by PainDeMie64** [FXMisc/RichTextFX#942]
Hello, my question is the exact same as this one: https://github.com/FXMisc/RichTextFX/issues/442

However, I don't understand how the guy ended up making it work. I want to set the default text color, but when I do so, highlighting doesn't work anymore, and all the words are the same color. 

Any help would be much appreciated! Thanks for taking time and reading this.

**Comment by Jugen** [comment]
Try the following modified "**java-keywords.css**":

```
.text {
	-fx-fill: red;
	/* default */
}

.styled-text-area .keyword {
    -fx-fill: purple;
    -fx-font-weight: bold;
}
.styled-text-area .semicolon {
    -fx-font-weight: bold;
}
.styled-text-area .paren {
    -fx-fill: firebrick;
    -fx-font-weight: bold;
}
.styled-text-area .bracket {
    -fx-fill: darkgreen;
    -fx-font-weight: bold;
}
.styled-text-area .brace {
    -fx-fill: teal;
    -fx-font-weight: bold;
}
.styled-text-area .string {
    -fx-fill: blue;
}
.styled-text-area .comment {
	-fx-fill: cadetblue;
}

.paragraph-box:has-caret {
    -fx-background-color: #f2f9fc;
}
```

It's different from the original in that each keyword class is prefixed with `.styled-text-area`

**Comment by Jugen** [comment]
The line numbers were coming out as red too, so I modified the CSS to make them black. (See updated comment on web)

**Comment by PainDeMie64** [comment]
Sorry for the late answer, I was on vacation. But thank you so much, it works!

**Comment by mat4pat** [comment]
Hello, I have the exact problem.

I have tried this solution, however, it seems that the .text property changes the text for Menu-Bars as well:

Before, setting .text property:
![image](https://user-images.githubusercontent.com/85194618/150666114-a136bd39-06a7-44dc-a814-a104ec6a76e2.png)
![image](https://user-images.githubusercontent.com/85194618/150666141-0535af95-c566-4526-bf75-e59958bc9b61.png)

After, setting .text property:
![image](https://user-images.githubusercontent.com/85194618/150666166-602bfcf8-7490-466e-bee4-08633d106c7c.png)
![image](https://user-images.githubusercontent.com/85194618/150666186-c3fbfc88-abdd-40c5-9738-5f083ffbd7cc.png)

As @PainDeMie64 has mentioned, yes the lines are also coming as the same color. But your fix covers it.

However the .text property apparently covers Menu-Bars' text color too.
I have seen this question quite a lot.

Thank you very much for you time and have a great day!
