### ISSUE TITLE
OSX: Entering curly braces and brackets is broken in 0.10.5 while 0.10.4 works (javafx14)

### ISSUE THREAD

**Issue by Siedlerchr** [FXMisc/RichTextFX#967]
## Expected Behavior

On a Macbook with Mac OSX 10.15  I am able to enter curly braces and brackets. `[]{}`.  using the `Option (or Alt) ⌥` key

## Actual Behavior

With version 0.10.5 I am unable to enter curly braces and brackets , when I downgrade to 0.10.4 it works.

## Reproducible Demo

[Orgiinal code](https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/entryeditor/SourceTab.java)

````java
public class Bug extends Application {

 public void start(Stage primaryStage) {

	StackPane root = new StackPane();
       Scene scene = new Scene(root,400,400);

        CodeArea codeArea = new CodeArea();
        codeArea.setWrapText(true);
        codeArea.setInputMethodRequests(new InputMethodRequestsObject());
        codeArea.setOnInputMethodTextChanged(event -> {
            String committed = event.getCommitted();
            if (!committed.isEmpty()) {
                codeArea.insertText(codeArea.getCaretPosition(), committed);
            }
        });


        codeArea.setId("bibtexSourceCodeArea");
         root.getChildren().add(codeArea);
 primaryStage.setScene(scene);

  primaryStage.show();



 }
 /* Work around for different input methods.
     * https://github.com/FXMisc/RichTextFX/issues/146
     */
    private static class InputMethodRequestsObject implements InputMethodRequests {

        @Override
        public String getSelectedText() {
            return "";
        }

        @Override
        public int getLocationOffset(int x, int y) {
            return 0;
        }

        @Override
        public void cancelLatestCommittedText() {
            return;
        }

        @Override
        public Point2D getTextLocation(int offset) {
            return new Point2D(0, 0);
        }
    }
}
````

## Environment info:

- RichTextFX Version: 0.10.5
- Operating System: OSX 10.15.7
- Java version: 14 + openjfx14 

<hr>

## Current Workarounds

Downgrade to 0.10.4

**Comment by Jugen** [comment]
I think this is related to PR [#922](https://github.com/FXMisc/RichTextFX/pull/922) ?  I think the offending code may be `!e.isAltDown()` [here](https://github.com/gaeqs/RichTextFX/blob/0d5bf324bfe3f9795dc7313d86dade199cf2fcb5/richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledAreaBehavior.java#L183) which, if I'm not mistaken, wasn't there before. I'll submit a new PR to address this.

**Comment by Jugen** [comment]
Can you please look at (and try) the fix in the PR and let me know if it works. Thanks.

**Comment by Siedlerchr** [comment]
Thanks for the quick fix, I will test it later today

**Comment by Siedlerchr** [comment]
@Jugen  Would you provide me a build snapshot of the lib with your fix? I am having troubles building it (because I probably only have a newer version of jdk installed)

**Comment by Jugen** [comment]
Sure here it is: [richtextfx-0.10.6-beta.zip](https://github.com/FXMisc/RichTextFX/files/5324002/richtextfx-0.10.6-beta.zip)
(Just rename the zip to jar)

**Comment by Siedlerchr** [comment]
@Jugen  Confirmed, works now again! Would be nice if you could release a new version with that fix.

**Comment by Jugen** [comment]
Great, will release new version probably later this week or the next.
