### ISSUE TITLE
How to display a hint without it being a part of plain text?

### ISSUE THREAD

**Issue by atoktoto** [FXMisc/RichTextFX#973]
I'm looking to implement something similar to what IntellJ does with `returnObject` and `exit`:
![obraz](https://user-images.githubusercontent.com/34739613/96220725-8f0f1a80-0f89-11eb-82fa-f63821ba75fe.png)
At the same time, I would prefer not to have those show up when saving the text.

I'm looking for any pointers, event hacky ones :D

**Comment by Jugen** [comment]
Instead of using _getText()_ when saving, you could filter out the `tags` like so:

```java
StringBuilder sb = new StringBuilder( area.getLength() );

for ( Paragraph<?,String, Collection<String>> p : area.getParagraphs() )
{
    for ( StyledSegment<String, Collection<String>> seg : p.getStyledSegments() )
    {
        if ( ! seg.getStyle().contains( "tag" ) ) // replace tag with your style name
        {
            sb.append( seg.getSegment() );
        }
    }
    sb.append( "\n" );
}

save( sb.toString() );
```

**Comment by atoktoto** [comment]
O, so just remove it as a post-processing step when saving. Makes sense. 
I guess the difference is that those tags are read-only (the caret skips over them as if they are one char) and are not copied when selected. The first thing can probably be done similar to images/links in demos.

**Comment by Jugen** [comment]
Also look at [CustomSegmentDemo](https://github.com/Jugen/StyledSegmentTextArea/blob/master/lightware/richtext/CustomSegmentDemo.java) for another way to implement read only tags.

**Comment by Jugen** [comment]
If you use the technique in _CustomSegmentDemo_, the saving snippet above would look something like so instead:

```java
StringBuilder sb = new StringBuilder( area.getLength() );

for ( Paragraph<?, AbstractSegment, ?> p : area.getParagraphs() )
{
    for ( StyledSegment<AbstractSegment, ?> seg : p.getStyledSegments() )
    {
        if ( ! (seg.getSegment() instanceof LabelSegment) )
        {
            sb.append( seg.getSegment().getText() );
        }
    }
    sb.append( "\n" );
}
```
