### ISSUE TITLE
how can set  Line break is \r\n not \n! i want get the \r\n text not \n text form codeArea

### ISSUE THREAD

**Issue by qq1053831109** [FXMisc/RichTextFX#975]
how can set  Line break is \r\n not \n! i want get the \r\n text not \n text form codeArea

**Comment by Jugen** [comment]
I think the relevant code is here in [ReadOnlyStyledDocument.getText()](https://github.com/FXMisc/RichTextFX/blob/1659a16049ae147b496d806bc26e29ba453a2c90/richtextfx/src/main/java/org/fxmisc/richtext/model/ReadOnlyStyledDocument.java#L238).

So you can do what's been done there, like so:
```java
String text = area.getParagraphs().stream()
    .map( Paragraph::getText )
    .collect( Collectors.joining( "\r\n" ) );
```

**Comment by qq1053831109** [comment]
3q
