### ISSUE TITLE
RTL languages (e.g. Arabic) support

### ISSUE THREAD

**Issue by xulihang** [FXMisc/RichTextFX#976]
Hi there,

I want to know if RichTextFX supports right to left languages.  I do not know Arabic but my users are requesting this support. See the [issue](https://github.com/xulihang/BasicCAT/issues/24).

The default TextArea of JavaFX supports this. I just need to set a proper font (like Arial) and set the nodeOrientation to RIGHT_TO_LEFT.

I tried to set the orientation of RichTextFX to RTL, but I found the caret position is not correct.

**Comment by Jugen** [comment]
See #836 and #97 
PR are welcome.

**Comment by xulihang** [comment]
After some experimenting, I found that to support RTL languages. I just need to make the control right-aligned.

With the css code below, TextArea can be right aligned.
```
.rightTextArea .scroll-pane .content .text {
    -fx-text-alignment: right;
}
```

But I haven't found how to do this for RichTextFX.

**Comment by Jugen** [comment]
You can try:
```css
.rightTextArea .text-flow {
    -fx-text-alignment: right;
}
```
See the RichTextFX CSS [wiki page](https://github.com/FXMisc/RichTextFX/wiki/RichTextFX-CSS-Reference-Guide)

**Comment by xulihang** [comment]
I tried this css and it works.

```
.paragraph-text{
    -fx-text-alignment: right;
}
```

Above is a codearea and below is a textarea.

![image](https://user-images.githubusercontent.com/5462205/98330214-dc385680-2034-11eb-8766-660e2ecc7ec7.png)
