### ISSUE TITLE
How to embed an image in RichTextFX?

### ISSUE THREAD

**Issue by nicoi15** [FXMisc/RichTextFX#978]
I am trying to use the code in RichTextDemo to be able to attach some image, but it is only linking the image to the its path.

Is it possible to embed an image to the RichTextFX instead (like in html <img src="data:image/png;base64>)? Because I am trying to achieve to save the content (not as a file) of the editor that can contain an image into the database, and be able to retrieve it and display exactly how it is saved.
 
This is the sample code that I copied from the demo.
````java
String filePath = System.getProperty("user.home") + "\\Desktop\\dailyreport.rtfx";
File file = new File(filePath);
StyledDocument<ParStyle, Either<String, LinkedImage>, TextStyle> doc = view.getCodeArea().getDocument();
// Use the Codec to save the document in a binary format
view.getCodeArea().getStyleCodecs().ifPresent(codecs -> {
     Codec<StyledDocument<ParStyle, Either<String, LinkedImage>, TextStyle>> codec =
          ReadOnlyStyledDocument.codec(codecs._1, codecs._2, view.getCodeArea().getSegOps());
     try {
          FileOutputStream fos = new FileOutputStream(file);
          DataOutputStream dos = new DataOutputStream(fos);
          codec.encode(dos, doc);
          fos.close();
     } catch (IOException fnfe) {
          fnfe.printStackTrace();
     }
});
````
Please help. Thanks!

**Comment by Jugen** [comment]
I think you should look at modifying the encode and decode methods in [LinkedImage.java](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext/LinkedImage.java) then.
