### ISSUE TITLE
Fold indicator styling via CSS not working

### ISSUE THREAD

**Issue by ultimaterichy** [FXMisc/RichTextFX#988]
From the documentation in LineNumberFactory class, I should be able to change the fold indicator ("+")  styling using the CSS class ".fold-indicator". I tried doing that but nothing changed. Here is my styling

`.fold-indicator{
      -fx-text-fill: green;
}`

and I also tried

`.fold-indicator{
      -fx-fill: green;
}`
 But it doesn't still work.

**Comment by Jugen** [comment]
I don't know why but if you edit [styled-text-area.css](https://github.com/FXMisc/RichTextFX/blob/45dc5e250bfc6b43c47ef8782f128b04e868fe18/richtextfx/src/main/resources/org/fxmisc/richtext/styled-text-area.css#L22) and remove the `.fold-indicator` style then it works ?

**Comment by ultimaterichy** [comment]
> I don't know why but if you edit [styled-text-area.css](https://github.com/FXMisc/RichTextFX/blob/45dc5e250bfc6b43c47ef8782f128b04e868fe18/richtextfx/src/main/resources/org/fxmisc/richtext/styled-text-area.css#L22) and remove the `.fold-indicator` style then it works ?

**Comment by ultimaterichy** [comment]
Thanks. It worked by removing the `fold-indicator` class from styled-text-area.css
I just wish there could be another way to

**Comment by Jugen** [comment]
Submitted PR #1000 that will fix and close this issue.
