### ISSUE TITLE
Question: How to get the index of a paragraph containing a given char index?

### ISSUE THREAD

**Issue by drinkitup777** [FXMisc/RichTextFX#993]
Say I have a text char index, `int i`. What in the API do I call to get the index of the paragraph that contains the char index `i`?

(This is for markdown syntax highlighting. The markdown parser I'm using returns code blocks as `start-index` to `end-index`. I want to highlight the respective paragraphs in the editor.)

**Comment by Jugen** [comment]
Try using `area.offsetToPosition( i, Bias.Backward ).getMajor()` which returns the paragraph.
