### ISSUE TITLE
How to edit the text of a hyperlink

### ISSUE THREAD

**Issue by FranzDeschler** [FXMisc/RichTextFX#994]
So far, I managed to implement a custom hyperlink segment and I am able to edit the text and the url of the hyperlink in a dialog window. But now I want to make editing the text even more simpler by just setting the cursor in the hyperlink segment and start typing.
But when I do this, the hyperlink segment is split into two separate hyperlinks and plain text between.

This behaviour is also reproducible in the [Hyperlink Demo](https://github.com/FXMisc/RichTextFX/tree/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/hyperlink).

To reproduce this, simply run the demo with an editable textarea.
Place the carent in the middle of the hyperlink (using the arrow keys - clicking would open the link) and start typing.
You will end up with somethink like this:
![grafik](https://user-images.githubusercontent.com/54034737/103415821-1aa94800-4b84-11eb-8b77-416c7a8e770a.png)

Is there some way to edit the text of the hyperlink this way?

**Comment by Jugen** [comment]
See submitted PR 955 to address this. It may still need some tweaking .... but the basic functionality is there now.
