### ISSUE TITLE
Tooltip not hiding Windows 10

### ISSUE THREAD

**Issue by LuccaPrado** [FXMisc/RichTextFX#996]
## Expected Behavior

When minimize JavaFX window by clicking other window, hide the popup/tooltip.

## Actual Behavior

When minimize the window by clicking other window the popup/tooltip still displaying.

## Reproducible Demo
To reproduce just run this code then click on any window that is under the JavaFX window
````java
public class TooltipDemo extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage) {
        StyleClassedTextArea area = new StyleClassedTextArea();
        area.setWrapText(true);
        area.appendText("Pause the mouse over the text for 1 second.");

        Popup popup = new Popup();
        Label popupMsg = new Label();
        popupMsg.setStyle(
                "-fx-background-color: black;" +
                "-fx-text-fill: white;" +
                "-fx-padding: 5;");
        popup.getContent().add(popupMsg);

        area.setMouseOverTextDelay(Duration.ofSeconds(1));
        area.addEventHandler(MouseOverTextEvent.MOUSE_OVER_TEXT_BEGIN, e -> {
            int chIdx = e.getCharacterIndex();
            Point2D pos = e.getScreenPosition();
            popupMsg.setText("Character '" + area.getText(chIdx, chIdx+1) + "' at " + pos);
            popup.show(area, pos.getX(), pos.getY() + 10);
        });

        Scene scene = new Scene(area, 600, 400);
        stage.setScene(scene);
        stage.setTitle("Tooltip Demo");
        stage.show();
    }
}
````

## Environment info:

- RichTextFX Version: \<0.10.5\>
- Operating System: \<Windows 10\>
- Java version: \<11.0.8\>

## Additional info

I made and video on my current project just to help to visualize.
https://drive.google.com/file/d/1yJ64btdxVQelCEzT23SkIqx43LsXi3El/view?usp=sharing

**Comment by LuccaPrado** [comment]
Now I'm noticing that this repo isn't the best location, as the Popup is from JavaFx and not from RichTextFX, someone can confirm if I'm right?

**Comment by Jugen** [comment]
Yeah, you're right .... try adding `popup.setAutoHide( true );`
